-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity route_concat_engine_route_concat_engine_Pipeline_SRC1_COPY is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_RD_BUS_0_AWVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_0_AWREADY : IN STD_LOGIC;
    m_axi_RD_BUS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_RD_BUS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_WVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_0_WREADY : IN STD_LOGIC;
    m_axi_RD_BUS_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_WLAST : OUT STD_LOGIC;
    m_axi_RD_BUS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_ARVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_0_ARREADY : IN STD_LOGIC;
    m_axi_RD_BUS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_RD_BUS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_RVALID : IN STD_LOGIC;
    m_axi_RD_BUS_0_RREADY : OUT STD_LOGIC;
    m_axi_RD_BUS_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_RLAST : IN STD_LOGIC;
    m_axi_RD_BUS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_RD_BUS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_BVALID : IN STD_LOGIC;
    m_axi_RD_BUS_0_BREADY : OUT STD_LOGIC;
    m_axi_RD_BUS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_AWVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_0_AWREADY : IN STD_LOGIC;
    m_axi_WR_BUS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WR_BUS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_WVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_0_WREADY : IN STD_LOGIC;
    m_axi_WR_BUS_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_WLAST : OUT STD_LOGIC;
    m_axi_WR_BUS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_ARVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_0_ARREADY : IN STD_LOGIC;
    m_axi_WR_BUS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WR_BUS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_RVALID : IN STD_LOGIC;
    m_axi_WR_BUS_0_RREADY : OUT STD_LOGIC;
    m_axi_WR_BUS_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_RLAST : IN STD_LOGIC;
    m_axi_WR_BUS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_WR_BUS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_BVALID : IN STD_LOGIC;
    m_axi_WR_BUS_0_BREADY : OUT STD_LOGIC;
    m_axi_WR_BUS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ch1_words : IN STD_LOGIC_VECTOR (13 downto 0);
    sext_ln163 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln163_1 : IN STD_LOGIC_VECTOR (61 downto 0);
    src1_requant_multiplier_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    sub_i_i124_i_i : IN STD_LOGIC_VECTOR (6 downto 0);
    half_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    shl_i_i_i_i : IN STD_LOGIC_VECTOR (62 downto 0);
    s_1_cast41 : IN STD_LOGIC_VECTOR (5 downto 0);
    src1_requant_enable : IN STD_LOGIC_VECTOR (7 downto 0);
    empty : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of route_concat_engine_route_concat_engine_Pipeline_SRC1_COPY is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv57_0 : STD_LOGIC_VECTOR (56 downto 0) := "000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_FFFFFFFFFFFFFF80 : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111110000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln163_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal WR_BUS_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal RD_BUS_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal s_1_cast41_cast_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal s_1_cast41_cast_reg_846 : STD_LOGIC_VECTOR (63 downto 0);
    signal src1_requant_multiplier_cast_cast_fu_239_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal src1_requant_multiplier_cast_cast_reg_858 : STD_LOGIC_VECTOR (39 downto 0);
    signal half_2_cast_fu_251_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal half_2_cast_reg_876 : STD_LOGIC_VECTOR (62 downto 0);
    signal enable_assign_1_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal enable_assign_1_reg_881 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i_i_i_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i_i_i_reg_890 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal v_fu_298_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_reg_903 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_reg_903_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_reg_903_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_1_reg_909 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_1_reg_909_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_1_reg_909_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_2_reg_915 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_2_reg_915_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_2_reg_915_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_3_reg_921 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_3_reg_921_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_3_reg_921_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal scaled_fu_219_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_reg_927 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_reg_927_pp0_iter3_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_1_fu_223_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_1_reg_933 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_1_reg_933_pp0_iter3_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_2_fu_227_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_2_reg_939 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_2_reg_939_pp0_iter3_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_3_fu_231_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal scaled_3_reg_945 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln60_1_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln60_1_reg_951 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln60_3_fu_345_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln60_3_reg_956 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln60_5_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln60_5_reg_961 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln28_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln28_reg_966 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_fu_377_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_reg_971 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_fu_388_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_reg_976 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_1_fu_399_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_1_reg_981 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_1_fu_410_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_1_reg_986 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_2_fu_421_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_2_reg_991 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_2_fu_432_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_2_reg_996 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_3_fu_450_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln34_3_reg_1001 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_3_fu_461_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln36_3_reg_1006 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln33_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln33_reg_1011 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_tmp50_5112_fu_759_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp50_5112_reg_1016 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp50_192104110_fu_765_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp50_192104110_reg_1021 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp50_3106108_fu_771_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp50_3106108_reg_1026 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_5_fu_795_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_5_reg_1031 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal w_fu_142 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln163_fu_281_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_w_1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal scaled_fu_219_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_1_fu_223_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_2_fu_227_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_3_fu_231_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal half_fu_361_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln34_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln34_fu_371_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln36_fu_382_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln34_1_fu_393_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln36_2_fu_404_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln34_2_fu_415_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln36_4_fu_426_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln34_3_fu_444_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln36_6_fu_455_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_fu_437_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln33_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_477_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln36_1_fu_484_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_496_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln36_3_fu_503_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_515_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln36_5_fu_522_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal agg_tmp_i_1_2_ph_fu_527_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal agg_tmp_i_1_ph_fu_489_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal agg_tmp_i_1_1_ph_fu_508_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_4_fu_563_p6 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_4_fu_563_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_4_fu_563_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal agg_tmp_i_182026_fu_545_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_6_fu_581_p4 : STD_LOGIC_VECTOR (56 downto 0);
    signal icmp_ln20_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_fu_607_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln22_fu_603_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp_i_1_12224_fu_551_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_fu_629_p4 : STD_LOGIC_VECTOR (56 downto 0);
    signal icmp_ln20_1_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_1_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_1_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_2_fu_655_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln22_1_fu_651_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_tmp_i_1_228_fu_539_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_8_fu_677_p4 : STD_LOGIC_VECTOR (56 downto 0);
    signal icmp_ln20_2_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_2_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_2_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_4_fu_703_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln22_2_fu_699_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_4_fu_563_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_fu_725_p4 : STD_LOGIC_VECTOR (56 downto 0);
    signal icmp_ln21_3_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln22_3_fu_747_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln20_5_fu_717_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln20_1_fu_621_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln20_3_fu_669_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln20_3_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln20_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_5_fu_795_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_5_fu_795_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_5_fu_795_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal v_4_fu_563_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_4_fu_563_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_4_fu_563_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_5_fu_795_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_5_fu_795_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_5_fu_795_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component route_concat_engine_mul_32s_8s_40_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component route_concat_engine_sparsemux_7_2_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component route_concat_engine_sparsemux_7_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component route_concat_engine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_8s_40_1_1_U22 : component route_concat_engine_mul_32s_8s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 40)
    port map (
        din0 => scaled_fu_219_p0,
        din1 => v_reg_903,
        dout => scaled_fu_219_p2);

    mul_32s_8s_40_1_1_U23 : component route_concat_engine_mul_32s_8s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 40)
    port map (
        din0 => scaled_1_fu_223_p0,
        din1 => v_1_reg_909,
        dout => scaled_1_fu_223_p2);

    mul_32s_8s_40_1_1_U24 : component route_concat_engine_mul_32s_8s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 40)
    port map (
        din0 => scaled_2_fu_227_p0,
        din1 => v_2_reg_915,
        dout => scaled_2_fu_227_p2);

    mul_32s_8s_40_1_1_U25 : component route_concat_engine_mul_32s_8s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 40)
    port map (
        din0 => scaled_3_fu_231_p0,
        din1 => v_3_reg_921,
        dout => scaled_3_fu_231_p2);

    sparsemux_7_2_64_1_1_U26 : component route_concat_engine_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => sext_ln28_reg_966,
        din1 => ashr_ln34_3_reg_1001,
        din2 => v_4_fu_563_p6,
        def => v_4_fu_563_p7,
        sel => v_4_fu_563_p8,
        dout => v_4_fu_563_p9);

    sparsemux_7_2_8_1_1_U27 : component route_concat_engine_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => v_3_reg_921_pp0_iter3_reg,
        din1 => ap_const_lv8_7F,
        din2 => v_5_fu_795_p6,
        def => v_5_fu_795_p7,
        sel => v_5_fu_795_p8,
        dout => v_5_fu_795_p9);

    flow_control_loop_pipe_sequential_init_U : component route_concat_engine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    w_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln163_fu_275_p2 = ap_const_lv1_0))) then 
                    w_fu_142 <= add_ln163_fu_281_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_142 <= ap_const_lv14_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                agg_tmp50_192104110_reg_1021 <= agg_tmp50_192104110_fu_765_p3;
                agg_tmp50_3106108_reg_1026 <= agg_tmp50_3106108_fu_771_p3;
                agg_tmp50_5112_reg_1016 <= agg_tmp50_5112_fu_759_p3;
                ashr_ln34_1_reg_981 <= ashr_ln34_1_fu_399_p2;
                ashr_ln34_2_reg_991 <= ashr_ln34_2_fu_421_p2;
                ashr_ln34_3_reg_1001 <= ashr_ln34_3_fu_450_p2;
                ashr_ln34_reg_971 <= ashr_ln34_fu_377_p2;
                ashr_ln36_1_reg_986 <= ashr_ln36_1_fu_410_p2;
                ashr_ln36_2_reg_996 <= ashr_ln36_2_fu_432_p2;
                ashr_ln36_3_reg_1006 <= ashr_ln36_3_fu_461_p2;
                ashr_ln36_reg_976 <= ashr_ln36_fu_388_p2;
                scaled_1_reg_933 <= scaled_1_fu_223_p2;
                scaled_1_reg_933_pp0_iter3_reg <= scaled_1_reg_933;
                scaled_2_reg_939 <= scaled_2_fu_227_p2;
                scaled_2_reg_939_pp0_iter3_reg <= scaled_2_reg_939;
                scaled_3_reg_945 <= scaled_3_fu_231_p2;
                scaled_reg_927 <= scaled_fu_219_p2;
                scaled_reg_927_pp0_iter3_reg <= scaled_reg_927;
                sext_ln28_reg_966 <= sext_ln28_fu_351_p1;
                sext_ln60_1_reg_951 <= sext_ln60_1_fu_342_p1;
                sext_ln60_3_reg_956 <= sext_ln60_3_fu_345_p1;
                sext_ln60_5_reg_961 <= sext_ln60_5_fu_348_p1;
                v_1_reg_909_pp0_iter2_reg <= v_1_reg_909;
                v_1_reg_909_pp0_iter3_reg <= v_1_reg_909_pp0_iter2_reg;
                v_2_reg_915_pp0_iter2_reg <= v_2_reg_915;
                v_2_reg_915_pp0_iter3_reg <= v_2_reg_915_pp0_iter2_reg;
                v_3_reg_921_pp0_iter2_reg <= v_3_reg_921;
                v_3_reg_921_pp0_iter3_reg <= v_3_reg_921_pp0_iter2_reg;
                v_5_reg_1031 <= v_5_fu_795_p9;
                v_reg_903_pp0_iter2_reg <= v_reg_903;
                v_reg_903_pp0_iter3_reg <= v_reg_903_pp0_iter2_reg;
                xor_ln33_reg_1011 <= xor_ln33_fu_471_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                cmp_i_i_i_i_reg_890 <= cmp_i_i_i_i_fu_261_p2;
                enable_assign_1_reg_881 <= enable_assign_1_fu_255_p2;
                    half_2_cast_reg_876(0) <= half_2_cast_fu_251_p1(0);
                    s_1_cast41_cast_reg_846(5 downto 0) <= s_1_cast41_cast_fu_235_p1(5 downto 0);
                src1_requant_multiplier_cast_cast_reg_858 <= src1_requant_multiplier_cast_cast_fu_239_p1;
                v_1_reg_909 <= m_axi_RD_BUS_0_RDATA(15 downto 8);
                v_2_reg_915 <= m_axi_RD_BUS_0_RDATA(23 downto 16);
                v_3_reg_921 <= m_axi_RD_BUS_0_RDATA(31 downto 24);
                v_reg_903 <= v_fu_298_p1;
            end if;
        end if;
    end process;
    s_1_cast41_cast_reg_846(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    half_2_cast_reg_876(62 downto 1) <= "00000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    RD_BUS_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_RD_BUS_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            RD_BUS_blk_n_R <= m_axi_RD_BUS_0_RVALID;
        else 
            RD_BUS_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    WR_BUS_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_WR_BUS_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            WR_BUS_blk_n_W <= m_axi_WR_BUS_0_WREADY;
        else 
            WR_BUS_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln163_fu_281_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_w_1) + unsigned(ap_const_lv14_1));
    add_ln34_1_fu_393_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) + unsigned(sext_ln60_3_fu_345_p1));
    add_ln34_2_fu_415_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) + unsigned(sext_ln60_5_fu_348_p1));
    add_ln34_3_fu_444_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) + unsigned(sext_ln28_fu_351_p1));
    add_ln34_fu_371_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) + unsigned(sext_ln60_1_fu_342_p1));
    agg_tmp50_192104110_fu_765_p3 <= 
        v_reg_903_pp0_iter3_reg when (enable_assign_1_reg_881(0) = '1') else 
        select_ln20_1_fu_621_p3;
    agg_tmp50_3106108_fu_771_p3 <= 
        v_1_reg_909_pp0_iter3_reg when (enable_assign_1_reg_881(0) = '1') else 
        select_ln20_3_fu_669_p3;
    agg_tmp50_5112_fu_759_p3 <= 
        v_2_reg_915_pp0_iter3_reg when (enable_assign_1_reg_881(0) = '1') else 
        select_ln20_5_fu_717_p3;
    agg_tmp_i_182026_fu_545_p3 <= 
        sext_ln60_1_reg_951 when (cmp_i_i_i_i_reg_890(0) = '1') else 
        agg_tmp_i_1_ph_fu_489_p3;
    agg_tmp_i_1_12224_fu_551_p3 <= 
        sext_ln60_3_reg_956 when (cmp_i_i_i_i_reg_890(0) = '1') else 
        agg_tmp_i_1_1_ph_fu_508_p3;
    agg_tmp_i_1_1_ph_fu_508_p3 <= 
        sub_ln36_3_fu_503_p2 when (tmp_3_fu_496_p3(0) = '1') else 
        ashr_ln34_1_reg_981;
    agg_tmp_i_1_228_fu_539_p3 <= 
        sext_ln60_5_reg_961 when (cmp_i_i_i_i_reg_890(0) = '1') else 
        agg_tmp_i_1_2_ph_fu_527_p3;
    agg_tmp_i_1_2_ph_fu_527_p3 <= 
        sub_ln36_5_fu_522_p2 when (tmp_4_fu_515_p3(0) = '1') else 
        ashr_ln34_2_reg_991;
    agg_tmp_i_1_ph_fu_489_p3 <= 
        sub_ln36_1_fu_484_p2 when (tmp_2_fu_477_p3(0) = '1') else 
        ashr_ln34_reg_971;
    and_ln20_fu_782_p2 <= (sel_tmp24_fu_777_p2 and icmp_ln20_3_fu_735_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_RD_BUS_0_RVALID)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((m_axi_RD_BUS_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, m_axi_RD_BUS_0_RVALID, m_axi_WR_BUS_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (m_axi_WR_BUS_0_WREADY = ap_const_logic_0)) or ((m_axi_RD_BUS_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, m_axi_RD_BUS_0_RVALID, m_axi_WR_BUS_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (m_axi_WR_BUS_0_WREADY = ap_const_logic_0)) or ((m_axi_RD_BUS_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, m_axi_RD_BUS_0_RVALID, m_axi_WR_BUS_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (m_axi_WR_BUS_0_WREADY = ap_const_logic_0)) or ((m_axi_RD_BUS_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln163_fu_275_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln163_fu_275_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_w_1_assign_proc : process(ap_CS_fsm_pp0_stage0, w_fu_142, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_w_1 <= ap_const_lv14_0;
        else 
            ap_sig_allocacmp_w_1 <= w_fu_142;
        end if; 
    end process;

    ashr_ln34_1_fu_399_p2 <= std_logic_vector(shift_right(signed(add_ln34_1_fu_393_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln34_2_fu_421_p2 <= std_logic_vector(shift_right(signed(add_ln34_2_fu_415_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln34_3_fu_450_p2 <= std_logic_vector(shift_right(signed(add_ln34_3_fu_444_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln34_fu_377_p2 <= std_logic_vector(shift_right(signed(add_ln34_fu_371_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln36_1_fu_410_p2 <= std_logic_vector(shift_right(signed(sub_ln36_2_fu_404_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln36_2_fu_432_p2 <= std_logic_vector(shift_right(signed(sub_ln36_4_fu_426_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln36_3_fu_461_p2 <= std_logic_vector(shift_right(signed(sub_ln36_6_fu_455_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    ashr_ln36_fu_388_p2 <= std_logic_vector(shift_right(signed(sub_ln36_fu_382_p2),to_integer(unsigned('0' & s_1_cast41_cast_reg_846(31-1 downto 0)))));
    cmp_i_i_i_i_fu_261_p2 <= "1" when (empty = ap_const_lv6_0) else "0";
    enable_assign_1_fu_255_p2 <= "1" when (src1_requant_enable = ap_const_lv8_0) else "0";
    half_2_cast_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(half_2),63));
    half_fu_361_p3 <= 
        half_2_cast_reg_876 when (tmp_1_fu_354_p3(0) = '1') else 
        shl_i_i_i_i;
    icmp_ln163_fu_275_p2 <= "1" when (ap_sig_allocacmp_w_1 = ch1_words) else "0";
    icmp_ln20_1_fu_639_p2 <= "1" when (signed(tmp_7_fu_629_p4) > signed(ap_const_lv57_0)) else "0";
    icmp_ln20_2_fu_687_p2 <= "1" when (signed(tmp_8_fu_677_p4) > signed(ap_const_lv57_0)) else "0";
    icmp_ln20_3_fu_735_p2 <= "1" when (signed(tmp_9_fu_725_p4) > signed(ap_const_lv57_0)) else "0";
    icmp_ln20_fu_591_p2 <= "1" when (signed(tmp_6_fu_581_p4) > signed(ap_const_lv57_0)) else "0";
    icmp_ln21_1_fu_645_p2 <= "1" when (signed(agg_tmp_i_1_12224_fu_551_p3) < signed(ap_const_lv64_FFFFFFFFFFFFFF80)) else "0";
    icmp_ln21_2_fu_693_p2 <= "1" when (signed(agg_tmp_i_1_228_fu_539_p3) < signed(ap_const_lv64_FFFFFFFFFFFFFF80)) else "0";
    icmp_ln21_3_fu_741_p2 <= "1" when (signed(v_4_fu_563_p9) < signed(ap_const_lv64_FFFFFFFFFFFFFF80)) else "0";
    icmp_ln21_fu_597_p2 <= "1" when (signed(agg_tmp_i_182026_fu_545_p3) < signed(ap_const_lv64_FFFFFFFFFFFFFF80)) else "0";
    m_axi_RD_BUS_0_ARADDR <= ap_const_lv64_0;
    m_axi_RD_BUS_0_ARBURST <= ap_const_lv2_0;
    m_axi_RD_BUS_0_ARCACHE <= ap_const_lv4_0;
    m_axi_RD_BUS_0_ARID <= ap_const_lv1_0;
    m_axi_RD_BUS_0_ARLEN <= ap_const_lv32_0;
    m_axi_RD_BUS_0_ARLOCK <= ap_const_lv2_0;
    m_axi_RD_BUS_0_ARPROT <= ap_const_lv3_0;
    m_axi_RD_BUS_0_ARQOS <= ap_const_lv4_0;
    m_axi_RD_BUS_0_ARREGION <= ap_const_lv4_0;
    m_axi_RD_BUS_0_ARSIZE <= ap_const_lv3_0;
    m_axi_RD_BUS_0_ARUSER <= ap_const_lv1_0;
    m_axi_RD_BUS_0_ARVALID <= ap_const_logic_0;
    m_axi_RD_BUS_0_AWADDR <= ap_const_lv64_0;
    m_axi_RD_BUS_0_AWBURST <= ap_const_lv2_0;
    m_axi_RD_BUS_0_AWCACHE <= ap_const_lv4_0;
    m_axi_RD_BUS_0_AWID <= ap_const_lv1_0;
    m_axi_RD_BUS_0_AWLEN <= ap_const_lv32_0;
    m_axi_RD_BUS_0_AWLOCK <= ap_const_lv2_0;
    m_axi_RD_BUS_0_AWPROT <= ap_const_lv3_0;
    m_axi_RD_BUS_0_AWQOS <= ap_const_lv4_0;
    m_axi_RD_BUS_0_AWREGION <= ap_const_lv4_0;
    m_axi_RD_BUS_0_AWSIZE <= ap_const_lv3_0;
    m_axi_RD_BUS_0_AWUSER <= ap_const_lv1_0;
    m_axi_RD_BUS_0_AWVALID <= ap_const_logic_0;
    m_axi_RD_BUS_0_BREADY <= ap_const_logic_0;

    m_axi_RD_BUS_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_RD_BUS_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_RD_BUS_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_RD_BUS_0_WDATA <= ap_const_lv32_0;
    m_axi_RD_BUS_0_WID <= ap_const_lv1_0;
    m_axi_RD_BUS_0_WLAST <= ap_const_logic_0;
    m_axi_RD_BUS_0_WSTRB <= ap_const_lv4_0;
    m_axi_RD_BUS_0_WUSER <= ap_const_lv1_0;
    m_axi_RD_BUS_0_WVALID <= ap_const_logic_0;
    m_axi_WR_BUS_0_ARADDR <= ap_const_lv64_0;
    m_axi_WR_BUS_0_ARBURST <= ap_const_lv2_0;
    m_axi_WR_BUS_0_ARCACHE <= ap_const_lv4_0;
    m_axi_WR_BUS_0_ARID <= ap_const_lv1_0;
    m_axi_WR_BUS_0_ARLEN <= ap_const_lv32_0;
    m_axi_WR_BUS_0_ARLOCK <= ap_const_lv2_0;
    m_axi_WR_BUS_0_ARPROT <= ap_const_lv3_0;
    m_axi_WR_BUS_0_ARQOS <= ap_const_lv4_0;
    m_axi_WR_BUS_0_ARREGION <= ap_const_lv4_0;
    m_axi_WR_BUS_0_ARSIZE <= ap_const_lv3_0;
    m_axi_WR_BUS_0_ARUSER <= ap_const_lv1_0;
    m_axi_WR_BUS_0_ARVALID <= ap_const_logic_0;
    m_axi_WR_BUS_0_AWADDR <= ap_const_lv64_0;
    m_axi_WR_BUS_0_AWBURST <= ap_const_lv2_0;
    m_axi_WR_BUS_0_AWCACHE <= ap_const_lv4_0;
    m_axi_WR_BUS_0_AWID <= ap_const_lv1_0;
    m_axi_WR_BUS_0_AWLEN <= ap_const_lv32_0;
    m_axi_WR_BUS_0_AWLOCK <= ap_const_lv2_0;
    m_axi_WR_BUS_0_AWPROT <= ap_const_lv3_0;
    m_axi_WR_BUS_0_AWQOS <= ap_const_lv4_0;
    m_axi_WR_BUS_0_AWREGION <= ap_const_lv4_0;
    m_axi_WR_BUS_0_AWSIZE <= ap_const_lv3_0;
    m_axi_WR_BUS_0_AWUSER <= ap_const_lv1_0;
    m_axi_WR_BUS_0_AWVALID <= ap_const_logic_0;
    m_axi_WR_BUS_0_BREADY <= ap_const_logic_0;
    m_axi_WR_BUS_0_RREADY <= ap_const_logic_0;
    m_axi_WR_BUS_0_WDATA <= (((v_5_reg_1031 & agg_tmp50_5112_reg_1016) & agg_tmp50_3106108_reg_1026) & agg_tmp50_192104110_reg_1021);
    m_axi_WR_BUS_0_WID <= ap_const_lv1_0;
    m_axi_WR_BUS_0_WLAST <= ap_const_logic_0;
    m_axi_WR_BUS_0_WSTRB <= ap_const_lv4_F;
    m_axi_WR_BUS_0_WUSER <= ap_const_lv1_0;

    m_axi_WR_BUS_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_WR_BUS_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_WR_BUS_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln20_1_fu_663_p2 <= (icmp_ln21_1_fu_645_p2 or icmp_ln20_1_fu_639_p2);
    or_ln20_2_fu_711_p2 <= (icmp_ln21_2_fu_693_p2 or icmp_ln20_2_fu_687_p2);
    or_ln20_fu_615_p2 <= (icmp_ln21_fu_597_p2 or icmp_ln20_fu_591_p2);
    or_ln33_fu_466_p2 <= (tmp_5_fu_437_p3 or cmp_i_i_i_i_reg_890);
    s_1_cast41_cast_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(s_1_cast41),64));
    scaled_1_fu_223_p0 <= src1_requant_multiplier_cast_cast_reg_858(32 - 1 downto 0);
    scaled_2_fu_227_p0 <= src1_requant_multiplier_cast_cast_reg_858(32 - 1 downto 0);
    scaled_3_fu_231_p0 <= src1_requant_multiplier_cast_cast_reg_858(32 - 1 downto 0);
    scaled_fu_219_p0 <= src1_requant_multiplier_cast_cast_reg_858(32 - 1 downto 0);
    sel_tmp24_fu_777_p2 <= (enable_assign_1_reg_881 xor ap_const_lv1_1);
    select_ln20_1_fu_621_p3 <= 
        select_ln20_fu_607_p3 when (or_ln20_fu_615_p2(0) = '1') else 
        trunc_ln22_fu_603_p1;
    select_ln20_2_fu_655_p3 <= 
        ap_const_lv8_7F when (icmp_ln20_1_fu_639_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln20_3_fu_669_p3 <= 
        select_ln20_2_fu_655_p3 when (or_ln20_1_fu_663_p2(0) = '1') else 
        trunc_ln22_1_fu_651_p1;
    select_ln20_4_fu_703_p3 <= 
        ap_const_lv8_7F when (icmp_ln20_2_fu_687_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln20_5_fu_717_p3 <= 
        select_ln20_4_fu_703_p3 when (or_ln20_2_fu_711_p2(0) = '1') else 
        trunc_ln22_2_fu_699_p1;
    select_ln20_fu_607_p3 <= 
        ap_const_lv8_7F when (icmp_ln20_fu_591_p2(0) = '1') else 
        ap_const_lv8_80;
        sext_ln28_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_3_reg_945),64));

        sext_ln60_1_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_reg_927),64));

        sext_ln60_3_fu_345_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_1_reg_933),64));

        sext_ln60_5_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_2_reg_939),64));

        src1_requant_multiplier_cast_cast_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src1_requant_multiplier_cast),40));

    sub_ln36_1_fu_484_p2 <= std_logic_vector(unsigned(ap_const_lv64_0) - unsigned(ashr_ln36_reg_976));
    sub_ln36_2_fu_404_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) - unsigned(sext_ln60_3_fu_345_p1));
    sub_ln36_3_fu_503_p2 <= std_logic_vector(unsigned(ap_const_lv64_0) - unsigned(ashr_ln36_1_reg_986));
    sub_ln36_4_fu_426_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) - unsigned(sext_ln60_5_fu_348_p1));
    sub_ln36_5_fu_522_p2 <= std_logic_vector(unsigned(ap_const_lv64_0) - unsigned(ashr_ln36_2_reg_996));
    sub_ln36_6_fu_455_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) - unsigned(sext_ln28_fu_351_p1));
    sub_ln36_fu_382_p2 <= std_logic_vector(unsigned(zext_ln34_fu_367_p1) - unsigned(sext_ln60_1_fu_342_p1));
    tmp_1_fu_354_p3 <= sub_i_i124_i_i(6 downto 6);
    tmp_2_fu_477_p3 <= scaled_reg_927_pp0_iter3_reg(39 downto 39);
    tmp_3_fu_496_p3 <= scaled_1_reg_933_pp0_iter3_reg(39 downto 39);
    tmp_4_fu_515_p3 <= scaled_2_reg_939_pp0_iter3_reg(39 downto 39);
    tmp_5_fu_437_p3 <= scaled_3_reg_945(39 downto 39);
    tmp_6_fu_581_p4 <= agg_tmp_i_182026_fu_545_p3(63 downto 7);
    tmp_7_fu_629_p4 <= agg_tmp_i_1_12224_fu_551_p3(63 downto 7);
    tmp_8_fu_677_p4 <= agg_tmp_i_1_228_fu_539_p3(63 downto 7);
    tmp_9_fu_725_p4 <= v_4_fu_563_p9(63 downto 7);
    trunc_ln22_1_fu_651_p1 <= agg_tmp_i_1_12224_fu_551_p3(8 - 1 downto 0);
    trunc_ln22_2_fu_699_p1 <= agg_tmp_i_1_228_fu_539_p3(8 - 1 downto 0);
    trunc_ln22_3_fu_747_p1 <= v_4_fu_563_p9(8 - 1 downto 0);
    trunc_ln22_fu_603_p1 <= agg_tmp_i_182026_fu_545_p3(8 - 1 downto 0);
    v_4_fu_563_p6 <= std_logic_vector(unsigned(ap_const_lv64_0) - unsigned(ashr_ln36_3_reg_1006));
    v_4_fu_563_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    v_4_fu_563_p8 <= (cmp_i_i_i_i_reg_890 & xor_ln33_reg_1011);
    v_5_fu_795_p6 <= 
        ap_const_lv8_80 when (icmp_ln21_3_fu_741_p2(0) = '1') else 
        trunc_ln22_3_fu_747_p1;
    v_5_fu_795_p7 <= "XXXXXXXX";
    v_5_fu_795_p8 <= (enable_assign_1_reg_881 & and_ln20_fu_782_p2);
    v_fu_298_p1 <= m_axi_RD_BUS_0_RDATA(8 - 1 downto 0);
    xor_ln33_fu_471_p2 <= (or_ln33_fu_466_p2 xor ap_const_lv1_1);
    zext_ln34_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(half_fu_361_p3),64));
end behav;
