-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity upsample_engine is
generic (
    C_M_AXI_RD_BUS_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_RD_BUS_ID_WIDTH : INTEGER := 1;
    C_M_AXI_RD_BUS_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_RD_BUS_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_RD_BUS_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_RD_BUS_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_RD_BUS_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_RD_BUS_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_WR_BUS_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_WR_BUS_ID_WIDTH : INTEGER := 1;
    C_M_AXI_WR_BUS_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_WR_BUS_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_WR_BUS_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_WR_BUS_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_WR_BUS_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_WR_BUS_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_RD_BUS_USER_VALUE : INTEGER := 0;
    C_M_AXI_RD_BUS_PROT_VALUE : INTEGER := 0;
    C_M_AXI_RD_BUS_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_WR_BUS_USER_VALUE : INTEGER := 0;
    C_M_AXI_WR_BUS_PROT_VALUE : INTEGER := 0;
    C_M_AXI_WR_BUS_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_RD_BUS_AWVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_AWREADY : IN STD_LOGIC;
    m_axi_RD_BUS_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_RD_BUS_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ID_WIDTH-1 downto 0);
    m_axi_RD_BUS_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_RD_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_AWUSER_WIDTH-1 downto 0);
    m_axi_RD_BUS_WVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_WREADY : IN STD_LOGIC;
    m_axi_RD_BUS_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_DATA_WIDTH-1 downto 0);
    m_axi_RD_BUS_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_DATA_WIDTH/8-1 downto 0);
    m_axi_RD_BUS_WLAST : OUT STD_LOGIC;
    m_axi_RD_BUS_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ID_WIDTH-1 downto 0);
    m_axi_RD_BUS_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_WUSER_WIDTH-1 downto 0);
    m_axi_RD_BUS_ARVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_ARREADY : IN STD_LOGIC;
    m_axi_RD_BUS_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_RD_BUS_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ID_WIDTH-1 downto 0);
    m_axi_RD_BUS_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_RD_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ARUSER_WIDTH-1 downto 0);
    m_axi_RD_BUS_RVALID : IN STD_LOGIC;
    m_axi_RD_BUS_RREADY : OUT STD_LOGIC;
    m_axi_RD_BUS_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_DATA_WIDTH-1 downto 0);
    m_axi_RD_BUS_RLAST : IN STD_LOGIC;
    m_axi_RD_BUS_RID : IN STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ID_WIDTH-1 downto 0);
    m_axi_RD_BUS_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_RUSER_WIDTH-1 downto 0);
    m_axi_RD_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_BVALID : IN STD_LOGIC;
    m_axi_RD_BUS_BREADY : OUT STD_LOGIC;
    m_axi_RD_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_BID : IN STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_ID_WIDTH-1 downto 0);
    m_axi_RD_BUS_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RD_BUS_BUSER_WIDTH-1 downto 0);
    m_axi_WR_BUS_AWVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_AWREADY : IN STD_LOGIC;
    m_axi_WR_BUS_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_WR_BUS_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ID_WIDTH-1 downto 0);
    m_axi_WR_BUS_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_WR_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_AWUSER_WIDTH-1 downto 0);
    m_axi_WR_BUS_WVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_WREADY : IN STD_LOGIC;
    m_axi_WR_BUS_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_DATA_WIDTH-1 downto 0);
    m_axi_WR_BUS_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_DATA_WIDTH/8-1 downto 0);
    m_axi_WR_BUS_WLAST : OUT STD_LOGIC;
    m_axi_WR_BUS_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ID_WIDTH-1 downto 0);
    m_axi_WR_BUS_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_WUSER_WIDTH-1 downto 0);
    m_axi_WR_BUS_ARVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_ARREADY : IN STD_LOGIC;
    m_axi_WR_BUS_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_WR_BUS_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ID_WIDTH-1 downto 0);
    m_axi_WR_BUS_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_WR_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ARUSER_WIDTH-1 downto 0);
    m_axi_WR_BUS_RVALID : IN STD_LOGIC;
    m_axi_WR_BUS_RREADY : OUT STD_LOGIC;
    m_axi_WR_BUS_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_DATA_WIDTH-1 downto 0);
    m_axi_WR_BUS_RLAST : IN STD_LOGIC;
    m_axi_WR_BUS_RID : IN STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ID_WIDTH-1 downto 0);
    m_axi_WR_BUS_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_RUSER_WIDTH-1 downto 0);
    m_axi_WR_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_BVALID : IN STD_LOGIC;
    m_axi_WR_BUS_BREADY : OUT STD_LOGIC;
    m_axi_WR_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_BID : IN STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_ID_WIDTH-1 downto 0);
    m_axi_WR_BUS_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_WR_BUS_BUSER_WIDTH-1 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of upsample_engine is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "upsample_engine_upsample_engine,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=45490,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=2512,HLS_SYN_LUT=2898,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (17 downto 0) := "000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (17 downto 0) := "000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (17 downto 0) := "000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (17 downto 0) := "001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (17 downto 0) := "010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal ifmap : STD_LOGIC_VECTOR (63 downto 0);
    signal ofmap : STD_LOGIC_VECTOR (63 downto 0);
    signal img_h : STD_LOGIC_VECTOR (15 downto 0);
    signal img_w : STD_LOGIC_VECTOR (15 downto 0);
    signal ch : STD_LOGIC_VECTOR (15 downto 0);
    signal RD_BUS_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal img_w_read_reg_392 : STD_LOGIC_VECTOR (15 downto 0);
    signal img_h_read_reg_399 : STD_LOGIC_VECTOR (15 downto 0);
    signal ofmap_read_reg_404 : STD_LOGIC_VECTOR (63 downto 0);
    signal ifmap_read_reg_409 : STD_LOGIC_VECTOR (63 downto 0);
    signal ch_words_reg_414 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln41_fu_237_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln41_reg_424 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln41_fu_243_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln41_reg_430 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln41_1_fu_247_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal and_ln41_1_reg_435 : STD_LOGIC_VECTOR (14 downto 0);
    signal and_ln41_cast_fu_254_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal and_ln41_cast_reg_440 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_27_fu_266_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal empty_27_reg_445 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_cast7_fu_282_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast7_reg_450 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_286_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_455 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln41_1_fu_301_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln41_1_reg_466 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mul_ln41_2_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln41_2_reg_471 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln44_1_reg_476 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal shl_ln_fu_352_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_reg_487 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal c_1_fu_365_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_1_reg_495 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_379_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_reg_505 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal px_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal px_ce0 : STD_LOGIC;
    signal px_we0 : STD_LOGIC;
    signal px_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_idle : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_ready : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWVALID : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WVALID : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WLAST : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARVALID : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_RREADY : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_BREADY : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_ce0 : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_we0 : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_idle : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_ready : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWVALID : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WVALID : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WLAST : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARVALID : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_RREADY : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_BREADY : STD_LOGIC;
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_ce0 : STD_LOGIC;
    signal RD_BUS_0_AWREADY : STD_LOGIC;
    signal RD_BUS_0_WREADY : STD_LOGIC;
    signal RD_BUS_0_ARVALID : STD_LOGIC;
    signal RD_BUS_0_ARREADY : STD_LOGIC;
    signal RD_BUS_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal RD_BUS_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal RD_BUS_0_RVALID : STD_LOGIC;
    signal RD_BUS_0_RREADY : STD_LOGIC;
    signal RD_BUS_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal RD_BUS_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal RD_BUS_0_BVALID : STD_LOGIC;
    signal WR_BUS_0_AWVALID : STD_LOGIC;
    signal WR_BUS_0_AWREADY : STD_LOGIC;
    signal WR_BUS_0_WVALID : STD_LOGIC;
    signal WR_BUS_0_WREADY : STD_LOGIC;
    signal WR_BUS_0_ARREADY : STD_LOGIC;
    signal WR_BUS_0_RVALID : STD_LOGIC;
    signal WR_BUS_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal WR_BUS_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal WR_BUS_0_BVALID : STD_LOGIC;
    signal WR_BUS_0_BREADY : STD_LOGIC;
    signal c_reg_164 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln44_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm_state17 : STD_LOGIC;
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal sext_ln44_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_120 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal mul_ln41_2_fu_198_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln41_2_fu_198_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln41_1_fu_202_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln41_fu_237_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln41_fu_237_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal cmp92_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp58_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_258_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_28_fu_274_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal shl_ln41_1_fu_312_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln41_3_fu_319_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln41_fu_323_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln41_1_fu_202_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_379_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_379_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal icmp_ln41_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_379_ce : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal grp_fu_379_p00 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln41_1_fu_202_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln41_2_fu_198_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln41_fu_237_p00 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln41_fu_237_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component upsample_engine_upsample_engine_Pipeline_UPSAMPLE_READ IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_RD_BUS_0_AWVALID : OUT STD_LOGIC;
        m_axi_RD_BUS_0_AWREADY : IN STD_LOGIC;
        m_axi_RD_BUS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_RD_BUS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_RD_BUS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_RD_BUS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_RD_BUS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_RD_BUS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_RD_BUS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_WVALID : OUT STD_LOGIC;
        m_axi_RD_BUS_0_WREADY : IN STD_LOGIC;
        m_axi_RD_BUS_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_RD_BUS_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_WLAST : OUT STD_LOGIC;
        m_axi_RD_BUS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_ARVALID : OUT STD_LOGIC;
        m_axi_RD_BUS_0_ARREADY : IN STD_LOGIC;
        m_axi_RD_BUS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_RD_BUS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_RD_BUS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_RD_BUS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_RD_BUS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_RD_BUS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_RD_BUS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_RD_BUS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_RVALID : IN STD_LOGIC;
        m_axi_RD_BUS_0_RREADY : OUT STD_LOGIC;
        m_axi_RD_BUS_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_RD_BUS_0_RLAST : IN STD_LOGIC;
        m_axi_RD_BUS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_RD_BUS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_RD_BUS_0_BVALID : IN STD_LOGIC;
        m_axi_RD_BUS_0_BREADY : OUT STD_LOGIC;
        m_axi_RD_BUS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_RD_BUS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_RD_BUS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        ch_words : IN STD_LOGIC_VECTOR (13 downto 0);
        sext_ln44 : IN STD_LOGIC_VECTOR (61 downto 0);
        px_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        px_ce0 : OUT STD_LOGIC;
        px_we0 : OUT STD_LOGIC;
        px_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component upsample_engine_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_WR_BUS_0_AWVALID : OUT STD_LOGIC;
        m_axi_WR_BUS_0_AWREADY : IN STD_LOGIC;
        m_axi_WR_BUS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_WR_BUS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_WR_BUS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WR_BUS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WR_BUS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WR_BUS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WR_BUS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_WVALID : OUT STD_LOGIC;
        m_axi_WR_BUS_0_WREADY : IN STD_LOGIC;
        m_axi_WR_BUS_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_WR_BUS_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_WLAST : OUT STD_LOGIC;
        m_axi_WR_BUS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_ARVALID : OUT STD_LOGIC;
        m_axi_WR_BUS_0_ARREADY : IN STD_LOGIC;
        m_axi_WR_BUS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_WR_BUS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_WR_BUS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WR_BUS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WR_BUS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WR_BUS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_WR_BUS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_WR_BUS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_RVALID : IN STD_LOGIC;
        m_axi_WR_BUS_0_RREADY : OUT STD_LOGIC;
        m_axi_WR_BUS_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_WR_BUS_0_RLAST : IN STD_LOGIC;
        m_axi_WR_BUS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_WR_BUS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WR_BUS_0_BVALID : IN STD_LOGIC;
        m_axi_WR_BUS_0_BREADY : OUT STD_LOGIC;
        m_axi_WR_BUS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_WR_BUS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_WR_BUS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        ch_words : IN STD_LOGIC_VECTOR (13 downto 0);
        zext_ln4_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        px_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        px_ce0 : OUT STD_LOGIC;
        px_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln41_1 : IN STD_LOGIC_VECTOR (14 downto 0);
        zext_ln4 : IN STD_LOGIC_VECTOR (14 downto 0);
        mul_ln41 : IN STD_LOGIC_VECTOR (29 downto 0);
        add_ln44 : IN STD_LOGIC_VECTOR (31 downto 0);
        ofmap : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component upsample_engine_mul_16ns_30ns_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (29 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component upsample_engine_mul_30s_16ns_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component upsample_engine_mul_14ns_16ns_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component upsample_engine_mac_muladd_16ns_15ns_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component upsample_engine_px_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component upsample_engine_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ifmap : OUT STD_LOGIC_VECTOR (63 downto 0);
        ofmap : OUT STD_LOGIC_VECTOR (63 downto 0);
        img_h : OUT STD_LOGIC_VECTOR (15 downto 0);
        img_w : OUT STD_LOGIC_VECTOR (15 downto 0);
        ch : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component upsample_engine_RD_BUS_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component upsample_engine_WR_BUS_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    px_U : component upsample_engine_px_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => px_address0,
        ce0 => px_ce0,
        we0 => px_we0,
        d0 => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_d0,
        q0 => px_q0);

    grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175 : component upsample_engine_upsample_engine_Pipeline_UPSAMPLE_READ
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start,
        ap_done => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done,
        ap_idle => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_idle,
        ap_ready => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_ready,
        m_axi_RD_BUS_0_AWVALID => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWVALID,
        m_axi_RD_BUS_0_AWREADY => ap_const_logic_0,
        m_axi_RD_BUS_0_AWADDR => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWADDR,
        m_axi_RD_BUS_0_AWID => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWID,
        m_axi_RD_BUS_0_AWLEN => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWLEN,
        m_axi_RD_BUS_0_AWSIZE => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWSIZE,
        m_axi_RD_BUS_0_AWBURST => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWBURST,
        m_axi_RD_BUS_0_AWLOCK => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWLOCK,
        m_axi_RD_BUS_0_AWCACHE => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWCACHE,
        m_axi_RD_BUS_0_AWPROT => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWPROT,
        m_axi_RD_BUS_0_AWQOS => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWQOS,
        m_axi_RD_BUS_0_AWREGION => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWREGION,
        m_axi_RD_BUS_0_AWUSER => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_AWUSER,
        m_axi_RD_BUS_0_WVALID => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WVALID,
        m_axi_RD_BUS_0_WREADY => ap_const_logic_0,
        m_axi_RD_BUS_0_WDATA => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WDATA,
        m_axi_RD_BUS_0_WSTRB => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WSTRB,
        m_axi_RD_BUS_0_WLAST => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WLAST,
        m_axi_RD_BUS_0_WID => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WID,
        m_axi_RD_BUS_0_WUSER => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_WUSER,
        m_axi_RD_BUS_0_ARVALID => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARVALID,
        m_axi_RD_BUS_0_ARREADY => RD_BUS_0_ARREADY,
        m_axi_RD_BUS_0_ARADDR => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARADDR,
        m_axi_RD_BUS_0_ARID => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARID,
        m_axi_RD_BUS_0_ARLEN => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARLEN,
        m_axi_RD_BUS_0_ARSIZE => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARSIZE,
        m_axi_RD_BUS_0_ARBURST => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARBURST,
        m_axi_RD_BUS_0_ARLOCK => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARLOCK,
        m_axi_RD_BUS_0_ARCACHE => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARCACHE,
        m_axi_RD_BUS_0_ARPROT => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARPROT,
        m_axi_RD_BUS_0_ARQOS => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARQOS,
        m_axi_RD_BUS_0_ARREGION => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARREGION,
        m_axi_RD_BUS_0_ARUSER => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARUSER,
        m_axi_RD_BUS_0_RVALID => RD_BUS_0_RVALID,
        m_axi_RD_BUS_0_RREADY => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_RREADY,
        m_axi_RD_BUS_0_RDATA => RD_BUS_0_RDATA,
        m_axi_RD_BUS_0_RLAST => ap_const_logic_0,
        m_axi_RD_BUS_0_RID => ap_const_lv1_0,
        m_axi_RD_BUS_0_RFIFONUM => RD_BUS_0_RFIFONUM,
        m_axi_RD_BUS_0_RUSER => ap_const_lv1_0,
        m_axi_RD_BUS_0_RRESP => ap_const_lv2_0,
        m_axi_RD_BUS_0_BVALID => ap_const_logic_0,
        m_axi_RD_BUS_0_BREADY => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_BREADY,
        m_axi_RD_BUS_0_BRESP => ap_const_lv2_0,
        m_axi_RD_BUS_0_BID => ap_const_lv1_0,
        m_axi_RD_BUS_0_BUSER => ap_const_lv1_0,
        ch_words => ch_words_reg_414,
        sext_ln44 => trunc_ln44_1_reg_476,
        px_address0 => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_address0,
        px_ce0 => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_ce0,
        px_we0 => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_we0,
        px_d0 => grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_d0);

    grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184 : component upsample_engine_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start,
        ap_done => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done,
        ap_idle => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_idle,
        ap_ready => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_ready,
        m_axi_WR_BUS_0_AWVALID => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWVALID,
        m_axi_WR_BUS_0_AWREADY => WR_BUS_0_AWREADY,
        m_axi_WR_BUS_0_AWADDR => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWADDR,
        m_axi_WR_BUS_0_AWID => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWID,
        m_axi_WR_BUS_0_AWLEN => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWLEN,
        m_axi_WR_BUS_0_AWSIZE => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWSIZE,
        m_axi_WR_BUS_0_AWBURST => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWBURST,
        m_axi_WR_BUS_0_AWLOCK => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWLOCK,
        m_axi_WR_BUS_0_AWCACHE => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWCACHE,
        m_axi_WR_BUS_0_AWPROT => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWPROT,
        m_axi_WR_BUS_0_AWQOS => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWQOS,
        m_axi_WR_BUS_0_AWREGION => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWREGION,
        m_axi_WR_BUS_0_AWUSER => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWUSER,
        m_axi_WR_BUS_0_WVALID => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WVALID,
        m_axi_WR_BUS_0_WREADY => WR_BUS_0_WREADY,
        m_axi_WR_BUS_0_WDATA => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WDATA,
        m_axi_WR_BUS_0_WSTRB => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WSTRB,
        m_axi_WR_BUS_0_WLAST => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WLAST,
        m_axi_WR_BUS_0_WID => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WID,
        m_axi_WR_BUS_0_WUSER => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WUSER,
        m_axi_WR_BUS_0_ARVALID => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARVALID,
        m_axi_WR_BUS_0_ARREADY => ap_const_logic_0,
        m_axi_WR_BUS_0_ARADDR => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARADDR,
        m_axi_WR_BUS_0_ARID => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARID,
        m_axi_WR_BUS_0_ARLEN => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARLEN,
        m_axi_WR_BUS_0_ARSIZE => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARSIZE,
        m_axi_WR_BUS_0_ARBURST => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARBURST,
        m_axi_WR_BUS_0_ARLOCK => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARLOCK,
        m_axi_WR_BUS_0_ARCACHE => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARCACHE,
        m_axi_WR_BUS_0_ARPROT => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARPROT,
        m_axi_WR_BUS_0_ARQOS => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARQOS,
        m_axi_WR_BUS_0_ARREGION => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARREGION,
        m_axi_WR_BUS_0_ARUSER => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_ARUSER,
        m_axi_WR_BUS_0_RVALID => ap_const_logic_0,
        m_axi_WR_BUS_0_RREADY => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_RREADY,
        m_axi_WR_BUS_0_RDATA => ap_const_lv32_0,
        m_axi_WR_BUS_0_RLAST => ap_const_logic_0,
        m_axi_WR_BUS_0_RID => ap_const_lv1_0,
        m_axi_WR_BUS_0_RFIFONUM => ap_const_lv9_0,
        m_axi_WR_BUS_0_RUSER => ap_const_lv1_0,
        m_axi_WR_BUS_0_RRESP => ap_const_lv2_0,
        m_axi_WR_BUS_0_BVALID => WR_BUS_0_BVALID,
        m_axi_WR_BUS_0_BREADY => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_BREADY,
        m_axi_WR_BUS_0_BRESP => ap_const_lv2_0,
        m_axi_WR_BUS_0_BID => ap_const_lv1_0,
        m_axi_WR_BUS_0_BUSER => ap_const_lv1_0,
        ch_words => ch_words_reg_414,
        zext_ln4_1 => tmp_4_reg_455,
        px_address0 => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_address0,
        px_ce0 => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_ce0,
        px_q0 => px_q0,
        zext_ln41_1 => empty_27_reg_445,
        zext_ln4 => and_ln41_1_reg_435,
        mul_ln41 => mul_ln41_reg_424,
        add_ln44 => add_ln44_reg_505,
        ofmap => ofmap_read_reg_404);

    CTRL_s_axi_U : component upsample_engine_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ifmap => ifmap,
        ofmap => ofmap,
        img_h => img_h,
        img_w => img_w,
        ch => ch,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    RD_BUS_m_axi_U : component upsample_engine_RD_BUS_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_RD_BUS_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_RD_BUS_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_RD_BUS_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_RD_BUS_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_RD_BUS_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_RD_BUS_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_RD_BUS_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_RD_BUS_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_RD_BUS_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_RD_BUS_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_RD_BUS_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_RD_BUS_AWVALID,
        AWREADY => m_axi_RD_BUS_AWREADY,
        AWADDR => m_axi_RD_BUS_AWADDR,
        AWID => m_axi_RD_BUS_AWID,
        AWLEN => m_axi_RD_BUS_AWLEN,
        AWSIZE => m_axi_RD_BUS_AWSIZE,
        AWBURST => m_axi_RD_BUS_AWBURST,
        AWLOCK => m_axi_RD_BUS_AWLOCK,
        AWCACHE => m_axi_RD_BUS_AWCACHE,
        AWPROT => m_axi_RD_BUS_AWPROT,
        AWQOS => m_axi_RD_BUS_AWQOS,
        AWREGION => m_axi_RD_BUS_AWREGION,
        AWUSER => m_axi_RD_BUS_AWUSER,
        WVALID => m_axi_RD_BUS_WVALID,
        WREADY => m_axi_RD_BUS_WREADY,
        WDATA => m_axi_RD_BUS_WDATA,
        WSTRB => m_axi_RD_BUS_WSTRB,
        WLAST => m_axi_RD_BUS_WLAST,
        WID => m_axi_RD_BUS_WID,
        WUSER => m_axi_RD_BUS_WUSER,
        ARVALID => m_axi_RD_BUS_ARVALID,
        ARREADY => m_axi_RD_BUS_ARREADY,
        ARADDR => m_axi_RD_BUS_ARADDR,
        ARID => m_axi_RD_BUS_ARID,
        ARLEN => m_axi_RD_BUS_ARLEN,
        ARSIZE => m_axi_RD_BUS_ARSIZE,
        ARBURST => m_axi_RD_BUS_ARBURST,
        ARLOCK => m_axi_RD_BUS_ARLOCK,
        ARCACHE => m_axi_RD_BUS_ARCACHE,
        ARPROT => m_axi_RD_BUS_ARPROT,
        ARQOS => m_axi_RD_BUS_ARQOS,
        ARREGION => m_axi_RD_BUS_ARREGION,
        ARUSER => m_axi_RD_BUS_ARUSER,
        RVALID => m_axi_RD_BUS_RVALID,
        RREADY => m_axi_RD_BUS_RREADY,
        RDATA => m_axi_RD_BUS_RDATA,
        RLAST => m_axi_RD_BUS_RLAST,
        RID => m_axi_RD_BUS_RID,
        RUSER => m_axi_RD_BUS_RUSER,
        RRESP => m_axi_RD_BUS_RRESP,
        BVALID => m_axi_RD_BUS_BVALID,
        BREADY => m_axi_RD_BUS_BREADY,
        BRESP => m_axi_RD_BUS_BRESP,
        BID => m_axi_RD_BUS_BID,
        BUSER => m_axi_RD_BUS_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => RD_BUS_0_ARVALID,
        I_CH0_ARREADY => RD_BUS_0_ARREADY,
        I_CH0_ARADDR => RD_BUS_0_ARADDR,
        I_CH0_ARLEN => RD_BUS_0_ARLEN,
        I_CH0_RVALID => RD_BUS_0_RVALID,
        I_CH0_RREADY => RD_BUS_0_RREADY,
        I_CH0_RDATA => RD_BUS_0_RDATA,
        I_CH0_RFIFONUM => RD_BUS_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => RD_BUS_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => RD_BUS_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => RD_BUS_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    WR_BUS_m_axi_U : component upsample_engine_WR_BUS_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_WR_BUS_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_WR_BUS_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_WR_BUS_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_WR_BUS_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_WR_BUS_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_WR_BUS_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_WR_BUS_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_WR_BUS_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_WR_BUS_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_WR_BUS_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_WR_BUS_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_WR_BUS_AWVALID,
        AWREADY => m_axi_WR_BUS_AWREADY,
        AWADDR => m_axi_WR_BUS_AWADDR,
        AWID => m_axi_WR_BUS_AWID,
        AWLEN => m_axi_WR_BUS_AWLEN,
        AWSIZE => m_axi_WR_BUS_AWSIZE,
        AWBURST => m_axi_WR_BUS_AWBURST,
        AWLOCK => m_axi_WR_BUS_AWLOCK,
        AWCACHE => m_axi_WR_BUS_AWCACHE,
        AWPROT => m_axi_WR_BUS_AWPROT,
        AWQOS => m_axi_WR_BUS_AWQOS,
        AWREGION => m_axi_WR_BUS_AWREGION,
        AWUSER => m_axi_WR_BUS_AWUSER,
        WVALID => m_axi_WR_BUS_WVALID,
        WREADY => m_axi_WR_BUS_WREADY,
        WDATA => m_axi_WR_BUS_WDATA,
        WSTRB => m_axi_WR_BUS_WSTRB,
        WLAST => m_axi_WR_BUS_WLAST,
        WID => m_axi_WR_BUS_WID,
        WUSER => m_axi_WR_BUS_WUSER,
        ARVALID => m_axi_WR_BUS_ARVALID,
        ARREADY => m_axi_WR_BUS_ARREADY,
        ARADDR => m_axi_WR_BUS_ARADDR,
        ARID => m_axi_WR_BUS_ARID,
        ARLEN => m_axi_WR_BUS_ARLEN,
        ARSIZE => m_axi_WR_BUS_ARSIZE,
        ARBURST => m_axi_WR_BUS_ARBURST,
        ARLOCK => m_axi_WR_BUS_ARLOCK,
        ARCACHE => m_axi_WR_BUS_ARCACHE,
        ARPROT => m_axi_WR_BUS_ARPROT,
        ARQOS => m_axi_WR_BUS_ARQOS,
        ARREGION => m_axi_WR_BUS_ARREGION,
        ARUSER => m_axi_WR_BUS_ARUSER,
        RVALID => m_axi_WR_BUS_RVALID,
        RREADY => m_axi_WR_BUS_RREADY,
        RDATA => m_axi_WR_BUS_RDATA,
        RLAST => m_axi_WR_BUS_RLAST,
        RID => m_axi_WR_BUS_RID,
        RUSER => m_axi_WR_BUS_RUSER,
        RRESP => m_axi_WR_BUS_RRESP,
        BVALID => m_axi_WR_BUS_BVALID,
        BREADY => m_axi_WR_BUS_BREADY,
        BRESP => m_axi_WR_BUS_BRESP,
        BID => m_axi_WR_BUS_BID,
        BUSER => m_axi_WR_BUS_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => WR_BUS_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => WR_BUS_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => WR_BUS_0_RDATA,
        I_CH0_RFIFONUM => WR_BUS_0_RFIFONUM,
        I_CH0_AWVALID => WR_BUS_0_AWVALID,
        I_CH0_AWREADY => WR_BUS_0_AWREADY,
        I_CH0_AWADDR => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWADDR,
        I_CH0_AWLEN => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWLEN,
        I_CH0_WVALID => WR_BUS_0_WVALID,
        I_CH0_WREADY => WR_BUS_0_WREADY,
        I_CH0_WDATA => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WDATA,
        I_CH0_WSTRB => grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WSTRB,
        I_CH0_BVALID => WR_BUS_0_BVALID,
        I_CH0_BREADY => WR_BUS_0_BREADY);

    mul_16ns_30ns_32_1_1_U14 : component upsample_engine_mul_16ns_30ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 30,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln41_2_fu_198_p0,
        din1 => mul_ln41_2_fu_198_p1,
        dout => mul_ln41_2_fu_198_p2);

    mul_30s_16ns_30_1_1_U15 : component upsample_engine_mul_30s_16ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 30,
        din1_WIDTH => 16,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln41_reg_424,
        din1 => mul_ln41_1_fu_202_p1,
        dout => mul_ln41_1_fu_202_p2);

    mul_14ns_16ns_30_1_1_U16 : component upsample_engine_mul_14ns_16ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 16,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln41_fu_237_p0,
        din1 => mul_ln41_fu_237_p1,
        dout => mul_ln41_fu_237_p2);

    mac_muladd_16ns_15ns_32ns_32_4_1_U17 : component upsample_engine_mac_muladd_16ns_15ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_379_p0,
        din1 => grp_fu_379_p1,
        din2 => shl_ln_reg_487,
        ce => grp_fu_379_ce,
        dout => grp_fu_379_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln44_fu_360_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                    grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_ready = ap_const_logic_1)) then 
                    grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state17) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                    grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_ready = ap_const_logic_1)) then 
                    grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                c_reg_164 <= ap_const_lv16_0;
            elsif (((grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                c_reg_164 <= c_1_reg_495;
            end if; 
        end if;
    end process;

    r_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_fu_120 <= ap_const_lv16_0;
            elsif (((icmp_ln44_fu_360_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                r_fu_120 <= add_ln41_1_reg_466;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln41_1_reg_466 <= add_ln41_1_fu_301_p2;
                mul_ln41_2_reg_471 <= mul_ln41_2_fu_198_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                add_ln44_reg_505 <= grp_fu_379_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    and_ln41_1_reg_435(14 downto 1) <= and_ln41_1_fu_247_p3(14 downto 1);
                    and_ln41_cast_reg_440(14 downto 1) <= and_ln41_cast_fu_254_p1(14 downto 1);
                    empty_27_reg_445(14 downto 1) <= empty_27_fu_266_p3(14 downto 1);
                mul_ln41_reg_424 <= mul_ln41_fu_237_p2;
                    p_cast7_reg_450(29 downto 0) <= p_cast7_fu_282_p1(29 downto 0);
                    tmp_4_reg_455(15 downto 2) <= tmp_4_fu_286_p3(15 downto 2);
                    zext_ln41_reg_430(29 downto 0) <= zext_ln41_fu_243_p1(29 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                c_1_reg_495 <= c_1_fu_365_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                ch_words_reg_414 <= ch(15 downto 2);
                ifmap_read_reg_409 <= ifmap;
                img_h_read_reg_399 <= img_h;
                img_w_read_reg_392 <= img_w;
                ofmap_read_reg_404 <= ofmap;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                    shl_ln_reg_487(31 downto 2) <= shl_ln_fu_352_p3(31 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln44_1_reg_476 <= add_ln41_fu_323_p2(63 downto 2);
            end if;
        end if;
    end process;
    zext_ln41_reg_430(31 downto 30) <= "00";
    and_ln41_1_reg_435(0) <= '0';
    and_ln41_cast_reg_440(0) <= '0';
    and_ln41_cast_reg_440(30 downto 15) <= "0000000000000000";
    empty_27_reg_445(0) <= '0';
    p_cast7_reg_450(63 downto 30) <= "0000000000000000000000000000000000";
    tmp_4_reg_455(1 downto 0) <= "00";
    shl_ln_reg_487(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state3, ap_CS_fsm_state13, grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done, grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done, RD_BUS_0_ARREADY, ap_CS_fsm_state18, icmp_ln44_fu_360_p2, ap_CS_fsm_state14, icmp_ln41_fu_296_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln41_fu_296_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = RD_BUS_0_ARREADY) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((icmp_ln44_fu_360_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state14 => 
                if (((grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if (((grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXX";
        end case;
    end process;

    RD_BUS_0_ARADDR_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state13, grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARADDR, RD_BUS_0_ARREADY, ap_CS_fsm_state14, sext_ln44_fu_338_p1)
    begin
        if (((ap_const_logic_1 = RD_BUS_0_ARREADY) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            RD_BUS_0_ARADDR <= sext_ln44_fu_338_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            RD_BUS_0_ARADDR <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARADDR;
        else 
            RD_BUS_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    RD_BUS_0_ARLEN_assign_proc : process(ap_CS_fsm_state5, p_cast7_reg_450, ap_CS_fsm_state13, grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARLEN, RD_BUS_0_ARREADY, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = RD_BUS_0_ARREADY) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            RD_BUS_0_ARLEN <= p_cast7_reg_450(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            RD_BUS_0_ARLEN <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARLEN;
        else 
            RD_BUS_0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    RD_BUS_0_ARVALID_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state13, grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARVALID, RD_BUS_0_ARREADY, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = RD_BUS_0_ARREADY) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            RD_BUS_0_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            RD_BUS_0_ARVALID <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_ARVALID;
        else 
            RD_BUS_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    RD_BUS_0_RREADY_assign_proc : process(ap_CS_fsm_state13, grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_RREADY, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            RD_BUS_0_RREADY <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_m_axi_RD_BUS_0_RREADY;
        else 
            RD_BUS_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    RD_BUS_blk_n_AR_assign_proc : process(m_axi_RD_BUS_ARREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            RD_BUS_blk_n_AR <= m_axi_RD_BUS_ARREADY;
        else 
            RD_BUS_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    WR_BUS_0_AWVALID_assign_proc : process(grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWVALID, ap_CS_fsm_state18, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            WR_BUS_0_AWVALID <= grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_AWVALID;
        else 
            WR_BUS_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    WR_BUS_0_BREADY_assign_proc : process(grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_BREADY, ap_CS_fsm_state18, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            WR_BUS_0_BREADY <= grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_BREADY;
        else 
            WR_BUS_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    WR_BUS_0_WVALID_assign_proc : process(grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WVALID, ap_CS_fsm_state18, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            WR_BUS_0_WVALID <= grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_m_axi_WR_BUS_0_WVALID;
        else 
            WR_BUS_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    add_ln41_1_fu_301_p2 <= std_logic_vector(unsigned(r_fu_120) + unsigned(ap_const_lv16_1));
    add_ln41_fu_323_p2 <= std_logic_vector(unsigned(zext_ln41_3_fu_319_p1) + unsigned(ifmap_read_reg_409));
    and_ln41_1_fu_247_p3 <= (ch_words_reg_414 & ap_const_lv1_0);
    and_ln41_cast_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln41_1_fu_247_p3),31));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_NS_fsm_state17 <= ap_NS_fsm(16);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done)
    begin
        if ((grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;

    ap_ST_fsm_state18_blk_assign_proc : process(grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done)
    begin
        if ((grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(RD_BUS_0_ARREADY)
    begin
        if ((ap_const_logic_0 = RD_BUS_0_ARREADY)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state3, icmp_ln41_fu_296_p2)
    begin
        if (((icmp_ln41_fu_296_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln41_fu_296_p2)
    begin
        if (((icmp_ln41_fu_296_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    c_1_fu_365_p2 <= std_logic_vector(unsigned(c_reg_164) + unsigned(ap_const_lv16_1));
    cmp58_fu_227_p2 <= "0" when (img_w_read_reg_392 = ap_const_lv16_0) else "1";
    cmp92_fu_232_p2 <= "0" when (ch_words_reg_414 = ap_const_lv14_0) else "1";
    empty_27_fu_266_p3 <= 
        and_ln41_1_fu_247_p3 when (cmp92_fu_232_p2(0) = '1') else 
        ap_const_lv15_0;
    empty_28_fu_274_p3 <= 
        empty_fu_258_p3 when (cmp58_fu_227_p2(0) = '1') else 
        ap_const_lv30_0;
    empty_fu_258_p3 <= 
        mul_ln41_fu_237_p2 when (cmp92_fu_232_p2(0) = '1') else 
        ap_const_lv30_0;

    grp_fu_379_ce_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state16, grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done, ap_CS_fsm_state14, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state13) or ((grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14)))) then 
            grp_fu_379_ce <= ap_const_logic_1;
        else 
            grp_fu_379_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_379_p0 <= grp_fu_379_p00(16 - 1 downto 0);
    grp_fu_379_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_164),31));
    grp_fu_379_p1 <= and_ln41_cast_reg_440(15 - 1 downto 0);
    grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_ap_start_reg;
    grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start <= grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_ap_start_reg;
    icmp_ln41_fu_296_p2 <= "1" when (r_fu_120 = img_h_read_reg_399) else "0";
    icmp_ln44_fu_360_p2 <= "1" when (c_reg_164 = img_w_read_reg_392) else "0";
    mul_ln41_1_fu_202_p1 <= mul_ln41_1_fu_202_p10(16 - 1 downto 0);
    mul_ln41_1_fu_202_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_120),30));
    mul_ln41_2_fu_198_p0 <= mul_ln41_2_fu_198_p00(16 - 1 downto 0);
    mul_ln41_2_fu_198_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_120),32));
    mul_ln41_2_fu_198_p1 <= zext_ln41_reg_430(30 - 1 downto 0);
    mul_ln41_fu_237_p0 <= mul_ln41_fu_237_p00(14 - 1 downto 0);
    mul_ln41_fu_237_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ch_words_reg_414),30));
    mul_ln41_fu_237_p1 <= mul_ln41_fu_237_p10(16 - 1 downto 0);
    mul_ln41_fu_237_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(img_w_read_reg_392),30));
    p_cast7_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_28_fu_274_p3),64));

    px_address0_assign_proc : process(grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_address0, grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_address0, ap_CS_fsm_state18, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            px_address0 <= grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            px_address0 <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_address0;
        else 
            px_address0 <= "XXXXXX";
        end if; 
    end process;


    px_ce0_assign_proc : process(grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_ce0, grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_ce0, ap_CS_fsm_state18, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            px_ce0 <= grp_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE_fu_184_px_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            px_ce0 <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_ce0;
        else 
            px_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    px_we0_assign_proc : process(grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_we0, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            px_we0 <= grp_upsample_engine_Pipeline_UPSAMPLE_READ_fu_175_px_we0;
        else 
            px_we0 <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln44_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln44_1_reg_476),64));

    shl_ln41_1_fu_312_p3 <= (mul_ln41_2_reg_471 & ap_const_lv2_0);
    shl_ln_fu_352_p3 <= (mul_ln41_1_fu_202_p2 & ap_const_lv2_0);
    tmp_4_fu_286_p3 <= (ch_words_reg_414 & ap_const_lv2_0);
    zext_ln41_3_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln41_1_fu_312_p3),64));
    zext_ln41_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln41_fu_237_p2),32));
end behav;
