#include <algorithm>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include "maxpool_engine.h"
#include "upsample_engine.h"
#include "route_concat_engine.h"
// Real per-layer data - generated by python/real_pool_upsample_route_layers.py
// from python_teammate/darknet_golden/artifacts (NOT hand-written). See
// run_real_maxpool_layer()/run_real_upsample_layer()/run_real_route_layer()
// below - same "diffs against already-independently-verified ground truth"
// pattern conv_engine_requant/HW/conv_engine_tb.cpp's run_real_layer() uses.
#include "real_pool_upsample_route_data.h"

// Full m_axi interface depths - must match each engine's own `#pragma HLS
// INTERFACE m_axi ... depth=...` expression exactly. Only matters for
// cosim (plain C-sim never uses `depth`) - see conv_engine_tb.cpp's own
// IFMAP_DEPTH etc. for the same requirement and the SIGSEGV it avoids.
static const size_t MAXPOOL_IFMAP_DEPTH = (size_t)MAX_IMG_W * MAX_IMG_W * MAX_CH;
static const size_t MAXPOOL_OFMAP_DEPTH = (size_t)MAX_IMG_W * MAX_IMG_W * MAX_CH;
static const size_t UPSAMPLE_IFMAP_DEPTH = (size_t)MAX_UPSAMPLE_IN_W * MAX_UPSAMPLE_IN_W * MAX_UPSAMPLE_CH;
static const size_t UPSAMPLE_OFMAP_DEPTH = (size_t)(2 * MAX_UPSAMPLE_IN_W) * (2 * MAX_UPSAMPLE_IN_W) * MAX_UPSAMPLE_CH;
static const size_t ROUTE_SRC_DEPTH   = (size_t)MAX_ROUTE_W * MAX_ROUTE_W * MAX_ROUTE_SRC_CH;
static const size_t ROUTE_OFMAP_DEPTH = (size_t)MAX_ROUTE_W * MAX_ROUTE_W * MAX_ROUTE_TOTAL_CH;

// ---------------------------------------------------------------------------
// pack4 testbench helpers
//
// The engines' m_axi ports are `pack4_t` (4 int8 channels per 32-bit beat -
// see HW/pack4.h), so every device-side buffer below is allocated and
// passed in WORDS. The reference_*() models above are deliberately left
// entirely int8_t-based and completely unaware of the packing: keeping the
// golden path unpacked is what makes a PASS here evidence that the packing
// is bit-exact, rather than evidence that both sides happen to share the
// same packing bug. Same "no shared code path" reasoning this file already
// documents for reference_conv()-style independence.
//
// The *_DEPTH constants above stay in ELEMENTS, so they still read as each
// engine's own img/ch bound product and remain directly comparable against
// the baseline project's values; pack4_words() converts at each point of
// use instead.
// ---------------------------------------------------------------------------
static inline size_t pack4_words(size_t elems) {
    return (elems + PACK4_LANES - 1) / PACK4_LANES;
}

// Flat int8 element index -> (word, lane), matching pack4.h's little-endian
// lane order: lane 0 is the lowest channel index and the low byte. This is
// the same mapping the DDR byte layout already had, which is exactly why
// no PS-side repacking pass is needed in real hardware - here it is only
// spelled out explicitly because the tb holds its golden data in a
// separate int8_t vector.
static inline void pack4_put(std::vector<pack4_t> &buf, size_t elem_idx, int8_t v) {
    pack4_set(buf[elem_idx / PACK4_LANES], (unsigned)(elem_idx % PACK4_LANES), (ap_int<8>)v);
}

static inline int8_t pack4_take(const std::vector<pack4_t> &buf, size_t elem_idx) {
    return (int8_t)pack4_get(buf[elem_idx / PACK4_LANES],
                             (unsigned)(elem_idx % PACK4_LANES)).to_int();
}

// ---------------------------------------------------------------------------
// C-simulation testbench for maxpool_engine / upsample_engine /
// route_concat_engine - 3 independent top-level functions, one shared tb
// binary (see hls/pool_upsample_route implementation plan). Each op gets
// its own reference_*() implementation below, deliberately NOT sharing any
// code path with the engine .cpp files (whose helpers are file-local static
// functions anyway) - same "a bug in one has no way to silently agree with
// the other" reasoning conv_engine_tb.cpp already documents for its own
// reference_conv().
// ---------------------------------------------------------------------------

static int8_t clamp_i8(int64_t v) {
    if (v > 127)  return 127;
    if (v < -128) return -128;
    return (int8_t)v;
}

// Plain int64_t implementation of RTL_HANDOFF_KO.md section 5's
// round_shift formula - independent from route_concat_engine.cpp's own
// ap_int<64> copy, same reasoning as conv_engine_tb.cpp's round_shift_ref().
static int64_t round_shift_ref(int64_t x, unsigned s) {
    if (s == 0) return x;
    int64_t half = (int64_t)1 << (s - 1);
    return (x >= 0) ? ((x + half) >> s) : -(((-x) + half) >> s);
}

static void reference_maxpool(
    const std::vector<int8_t> &in, std::vector<int8_t> &out,
    unsigned img_h, unsigned img_w, unsigned ch,
    unsigned stride, unsigned pad_right, unsigned pad_bottom
) {
    unsigned out_h = (img_h + pad_bottom - 2) / stride + 1;
    unsigned out_w = (img_w + pad_right - 2) / stride + 1;
    out.assign((size_t)out_h * out_w * ch, 0);

    for (unsigned r = 0; r < out_h; r++) {
        for (unsigned c = 0; c < out_w; c++) {
            for (unsigned cc = 0; cc < ch; cc++) {
                int8_t mv = -128;
                for (unsigned dy = 0; dy < 2; dy++) {
                    for (unsigned dx = 0; dx < 2; dx++) {
                        unsigned in_r = r * stride + dy;
                        unsigned in_c = c * stride + dx;
                        int8_t v = -128;
                        if (in_r < img_h && in_c < img_w) {
                            v = in[((size_t)in_r * img_w + in_c) * ch + cc];
                        }
                        if (v > mv) mv = v;
                    }
                }
                out[((size_t)r * out_w + c) * ch + cc] = mv;
            }
        }
    }
}

static void reference_upsample(
    const std::vector<int8_t> &in, std::vector<int8_t> &out,
    unsigned img_h, unsigned img_w, unsigned ch
) {
    unsigned out_w = 2 * img_w;
    out.assign((size_t)(2 * img_h) * out_w * ch, 0);

    for (unsigned r = 0; r < img_h; r++) {
        for (unsigned c = 0; c < img_w; c++) {
            for (unsigned cc = 0; cc < ch; cc++) {
                int8_t v = in[((size_t)r * img_w + c) * ch + cc];
                for (unsigned dy = 0; dy < 2; dy++) {
                    for (unsigned dx = 0; dx < 2; dx++) {
                        out[((size_t)(2 * r + dy) * out_w + (2 * c + dx)) * ch + cc] = v;
                    }
                }
            }
        }
    }
}

static void reference_route_concat(
    const std::vector<int8_t> &src0, const std::vector<int8_t> &src1, std::vector<int8_t> &out,
    unsigned img_h, unsigned img_w, unsigned ch0, unsigned ch1,
    bool src0_requant_enable, int32_t src0_mult, unsigned src0_shift,
    bool src1_requant_enable, int32_t src1_mult, unsigned src1_shift
) {
    unsigned out_ch = ch0 + ch1;
    out.assign((size_t)img_h * img_w * out_ch, 0);

    for (unsigned r = 0; r < img_h; r++) {
        for (unsigned c = 0; c < img_w; c++) {
            size_t px = (size_t)r * img_w + c;
            for (unsigned cc = 0; cc < ch0; cc++) {
                int8_t v = src0[px * ch0 + cc];
                if (src0_requant_enable) {
                    int64_t scaled = (int64_t)v * (int64_t)src0_mult;
                    v = clamp_i8(round_shift_ref(scaled, src0_shift));
                }
                out[px * out_ch + cc] = v;
            }
            for (unsigned cc = 0; cc < ch1; cc++) {
                int8_t v = src1[px * ch1 + cc];
                if (src1_requant_enable) {
                    int64_t scaled = (int64_t)v * (int64_t)src1_mult;
                    v = clamp_i8(round_shift_ref(scaled, src1_shift));
                }
                out[px * out_ch + ch0 + cc] = v;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Synthetic per-config runners - build random (or deliberately-chosen)
// input, run the independent reference above, run the real engine, diff
// element-by-element. Same PASS/FAIL printf convention as
// conv_engine_tb.cpp's run_config()/run_real_layer().
// ---------------------------------------------------------------------------

static int run_maxpool_config(
    const char *name,
    unsigned img_h, unsigned img_w, unsigned ch,
    unsigned stride, unsigned pad_right, unsigned pad_bottom,
    unsigned seed, bool border_stress = false, bool pad_to_full_depth = false
) {
    srand(seed);
    std::vector<int8_t> in((size_t)img_h * img_w * ch);
    for (auto &v : in) {
        // border_stress (MP-H): real values near -100, deliberately close
        // to the -128 pad value, so a naive "pad with 0" bug (which would
        // let a real -50 value lose to a padded 0) would fail this config
        // even though it would pass every "normal" config above it.
        v = border_stress ? (int8_t)(-100 + (rand() % 20)) : (int8_t)((rand() % 200) - 100);
    }

    std::vector<int8_t> ref_out;
    reference_maxpool(in, ref_out, img_h, img_w, ch, stride, pad_right, pad_bottom);

    unsigned out_h = (img_h + pad_bottom - 2) / stride + 1;
    unsigned out_w = (img_w + pad_right - 2) / stride + 1;

    // Only the front sub-region (this config's real data) is filled when
    // pad_to_full_depth is set - maxpool_engine() never reads/writes past
    // its own img_h/img_w/ch-derived bounds, so the rest is inert padding
    // that exists purely to match the m_axi depth= pragma for cosim (see
    // MAXPOOL_IFMAP_DEPTH above / conv_engine_tb.cpp's identical convention).
    size_t ifmap_size = pad_to_full_depth ? MAXPOOL_IFMAP_DEPTH : in.size();
    size_t ofmap_size = pad_to_full_depth ? MAXPOOL_OFMAP_DEPTH : (size_t)out_h * out_w * ch;
    std::vector<pack4_t> in_hw(pack4_words(ifmap_size), (pack4_t)0);
    for (size_t i = 0; i < in.size(); i++) pack4_put(in_hw, i, in[i]);
    std::vector<pack4_t> hw_out(pack4_words(ofmap_size), (pack4_t)0);

    maxpool_engine(in_hw.data(), hw_out.data(),
                   (uint16_t)img_h, (uint16_t)img_w, (uint16_t)ch,
                   (uint8_t)stride, (uint8_t)pad_right, (uint8_t)pad_bottom);

    unsigned mismatches = 0;
    unsigned total = out_h * out_w * ch;
    for (unsigned i = 0; i < total; i++) {
        int8_t hw_val = pack4_take(hw_out, i);
        int8_t ref_val = ref_out[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%u: hw=%d ref=%d\n", name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        printf("[%s] PASS: %u output values matched the reference bit-exactly "
               "(img %ux%ux%u -> %ux%ux%u, stride=%u, pad_right=%u, pad_bottom=%u)\n",
               name, total, img_w, img_h, ch, out_w, out_h, ch, stride, pad_right, pad_bottom);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%u values mismatched\n", name, mismatches, total);
        return 1;
    }
}

static int run_upsample_config(const char *name, unsigned img_h, unsigned img_w, unsigned ch, unsigned seed,
                                bool pad_to_full_depth = false) {
    srand(seed);
    std::vector<int8_t> in((size_t)img_h * img_w * ch);
    for (auto &v : in) v = (int8_t)((rand() % 256) - 128);

    std::vector<int8_t> ref_out;
    reference_upsample(in, ref_out, img_h, img_w, ch);

    unsigned out_h = 2 * img_h, out_w = 2 * img_w;

    size_t ifmap_size = pad_to_full_depth ? UPSAMPLE_IFMAP_DEPTH : in.size();
    size_t ofmap_size = pad_to_full_depth ? UPSAMPLE_OFMAP_DEPTH : (size_t)out_h * out_w * ch;
    std::vector<pack4_t> in_hw(pack4_words(ifmap_size), (pack4_t)0);
    for (size_t i = 0; i < in.size(); i++) pack4_put(in_hw, i, in[i]);
    std::vector<pack4_t> hw_out(pack4_words(ofmap_size), (pack4_t)0);

    upsample_engine(in_hw.data(), hw_out.data(), (uint16_t)img_h, (uint16_t)img_w, (uint16_t)ch);

    unsigned mismatches = 0;
    unsigned total = out_h * out_w * ch;
    for (unsigned i = 0; i < total; i++) {
        int8_t hw_val = pack4_take(hw_out, i);
        int8_t ref_val = ref_out[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%u: hw=%d ref=%d\n", name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        printf("[%s] PASS: %u output values matched the reference bit-exactly "
               "(img %ux%ux%u -> %ux%ux%u)\n",
               name, total, img_w, img_h, ch, out_w, out_h, ch);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%u values mismatched\n", name, mismatches, total);
        return 1;
    }
}

static int run_route_config(
    const char *name,
    unsigned img_h, unsigned img_w, unsigned ch0, unsigned ch1,
    bool src0_requant_enable, int32_t src0_mult, unsigned src0_shift,
    bool src1_requant_enable, int32_t src1_mult, unsigned src1_shift,
    unsigned seed, bool saturation_stress = false, bool pad_to_full_depth = false
) {
    srand(seed);
    std::vector<int8_t> src0((size_t)img_h * img_w * ch0);
    std::vector<int8_t> src1((size_t)img_h * img_w * ch1);
    for (auto &v : src0) v = saturation_stress ? (int8_t)((rand() % 2) ? 127 : -128) : (int8_t)((rand() % 200) - 100);
    for (auto &v : src1) v = saturation_stress ? (int8_t)((rand() % 2) ? 127 : -128) : (int8_t)((rand() % 200) - 100);

    std::vector<int8_t> ref_out;
    reference_route_concat(src0, src1, ref_out, img_h, img_w, ch0, ch1,
                            src0_requant_enable, src0_mult, src0_shift,
                            src1_requant_enable, src1_mult, src1_shift);

    size_t src0_size = pad_to_full_depth ? ROUTE_SRC_DEPTH : src0.size();
    size_t src1_size = pad_to_full_depth ? ROUTE_SRC_DEPTH : src1.size();
    size_t ofmap_size = pad_to_full_depth ? ROUTE_OFMAP_DEPTH : (size_t)img_h * img_w * (ch0 + ch1);

    std::vector<pack4_t> src0_hw(pack4_words(src0_size), (pack4_t)0);
    for (size_t i = 0; i < src0.size(); i++) pack4_put(src0_hw, i, src0[i]);
    // src1_hw always allocated (even when ch1==0, size 0) - route_concat_engine
    // never dereferences it in that case (SRC1_COPY becomes a zero-trip
    // loop), but .data() on a size-0 vector is still a valid (if unused)
    // pointer to pass.
    std::vector<pack4_t> src1_hw(pack4_words(src1_size), (pack4_t)0);
    for (size_t i = 0; i < src1.size(); i++) pack4_put(src1_hw, i, src1[i]);
    std::vector<pack4_t> hw_out(pack4_words(ofmap_size), (pack4_t)0);

    route_concat_engine(src0_hw.data(), src1_hw.data(), hw_out.data(),
                         (uint16_t)img_h, (uint16_t)img_w, (uint16_t)ch0, (uint16_t)ch1,
                         (uint8_t)(src0_requant_enable ? 1 : 0), src0_mult, (uint8_t)src0_shift,
                         (uint8_t)(src1_requant_enable ? 1 : 0), src1_mult, (uint8_t)src1_shift);

    unsigned mismatches = 0;
    unsigned total = img_h * img_w * (ch0 + ch1);
    for (unsigned i = 0; i < total; i++) {
        int8_t hw_val = pack4_take(hw_out, i);
        int8_t ref_val = ref_out[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%u: hw=%d ref=%d\n", name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        printf("[%s] PASS: %u output values matched the reference bit-exactly "
               "(img %ux%u, ch0=%u, ch1=%u -> ch=%u)\n",
               name, total, img_w, img_h, ch0, ch1, ch0 + ch1);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%u values mismatched\n", name, mismatches, total);
        return 1;
    }
}

// ---------------------------------------------------------------------------
// Real-layer suite - runs each engine against the teammate's ACTUAL
// YOLOv3-tiny-ADAS activations (real_pool_upsample_route_data.h, generated
// by python/real_pool_upsample_route_layers.py from
// python_teammate/darknet_golden/), diffing directly against that layer's
// real expected output. cfg.expected is already independently-verified
// ground truth (the generator's own numpy re-implementation matched it
// bit-exact before these arrays were ever written) - a PASS here checks
// that this engine's actual synthesizable C++ agrees with that same ground
// truth, same reasoning as conv_engine_tb.cpp's run_real_layer().
// ---------------------------------------------------------------------------

static int run_real_maxpool_layer(const RealMaxpoolCfg &cfg) {
    std::vector<pack4_t> in_hw(pack4_words(cfg.input_size), (pack4_t)0);
    for (size_t i = 0; i < cfg.input_size; i++) pack4_put(in_hw, i, cfg.input[i]);
    std::vector<pack4_t> hw_out(pack4_words(cfg.expected_size), (pack4_t)0);

    maxpool_engine(in_hw.data(), hw_out.data(),
                   (uint16_t)cfg.img_h, (uint16_t)cfg.img_w, (uint16_t)cfg.ch,
                   (uint8_t)cfg.stride, (uint8_t)cfg.pad_right, (uint8_t)cfg.pad_bottom);

    unsigned mismatches = 0;
    for (size_t i = 0; i < cfg.expected_size; i++) {
        int8_t hw_val = pack4_take(hw_out, i);
        int8_t ref_val = cfg.expected[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%zu: hw=%d ref=%d\n", cfg.name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }
    if (mismatches == 0) {
        printf("[%s] PASS: %zu output values matched the real golden model bit-exactly\n",
               cfg.name, cfg.expected_size);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%zu values mismatched\n", cfg.name, mismatches, cfg.expected_size);
        return 1;
    }
}

static int run_real_upsample_layer(const RealUpsampleCfg &cfg) {
    std::vector<pack4_t> in_hw(pack4_words(cfg.input_size), (pack4_t)0);
    for (size_t i = 0; i < cfg.input_size; i++) pack4_put(in_hw, i, cfg.input[i]);
    std::vector<pack4_t> hw_out(pack4_words(cfg.expected_size), (pack4_t)0);

    upsample_engine(in_hw.data(), hw_out.data(), (uint16_t)cfg.img_h, (uint16_t)cfg.img_w, (uint16_t)cfg.ch);

    unsigned mismatches = 0;
    for (size_t i = 0; i < cfg.expected_size; i++) {
        int8_t hw_val = pack4_take(hw_out, i);
        int8_t ref_val = cfg.expected[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%zu: hw=%d ref=%d\n", cfg.name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }
    if (mismatches == 0) {
        printf("[%s] PASS: %zu output values matched the real golden model bit-exactly\n",
               cfg.name, cfg.expected_size);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%zu values mismatched\n", cfg.name, mismatches, cfg.expected_size);
        return 1;
    }
}

static int run_real_route_layer(const RealRouteCfg &cfg) {
    std::vector<pack4_t> src0_hw(pack4_words(cfg.src0_size), (pack4_t)0);
    for (size_t i = 0; i < cfg.src0_size; i++) pack4_put(src0_hw, i, cfg.src0[i]);
    std::vector<pack4_t> src1_hw(pack4_words(cfg.src1_size), (pack4_t)0);
    for (size_t i = 0; i < cfg.src1_size; i++) pack4_put(src1_hw, i, cfg.src1[i]);
    std::vector<pack4_t> hw_out(pack4_words(cfg.expected_size), (pack4_t)0);

    route_concat_engine(src0_hw.data(), src1_hw.data(), hw_out.data(),
                         (uint16_t)cfg.img_h, (uint16_t)cfg.img_w, (uint16_t)cfg.ch0, (uint16_t)cfg.ch1,
                         cfg.src0_requant_enable, cfg.src0_requant_multiplier, cfg.src0_requant_shift,
                         cfg.src1_requant_enable, cfg.src1_requant_multiplier, cfg.src1_requant_shift);

    unsigned mismatches = 0;
    for (size_t i = 0; i < cfg.expected_size; i++) {
        int8_t hw_val = pack4_take(hw_out, i);
        int8_t ref_val = cfg.expected[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%zu: hw=%d ref=%d\n", cfg.name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }
    if (mismatches == 0) {
        printf("[%s] PASS: %zu output values matched the real golden model bit-exactly\n",
               cfg.name, cfg.expected_size);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%zu values mismatched\n", cfg.name, mismatches, cfg.expected_size);
        return 1;
    }
}

int main(int argc, char **argv) {
    // C/RTL co-simulation RTL-simulates only the FIRST call the compiled
    // testbench makes to whichever top function that solution's
    // set_top picked (see run_hls.tcl) - not just the intended one. All 3
    // engines are compiled into this one tb binary, and every synthetic
    // config above uses small, non-full-depth buffers (fine for plain
    // C-sim, fatal for cosim - see MAXPOOL_IFMAP_DEPTH etc.'s comment).
    // run_hls.tcl passes --cosim-only=<engine>, so cosim only ever reaches
    // one dedicated, full-m_axi-depth call for that specific engine - same
    // "--cosim-only" convention conv_engine_tb.cpp uses, just parameterized
    // over which of the 3 engines this solution's top function is.
    if (argc > 1 && std::strncmp(argv[1], "--cosim-only=", 13) == 0) {
        const char *engine = argv[1] + 13;
        int fail;
        if (std::strcmp(engine, "maxpool") == 0) {
            fail = run_maxpool_config("cosim-maxpool: layer-11-shaped, full m_axi depth",
                                       9, 16, 512, 1, 1, 1, /*seed=*/100,
                                       /*border_stress=*/false, /*pad_to_full_depth=*/true);
        } else if (std::strcmp(engine, "upsample") == 0) {
            fail = run_upsample_config("cosim-upsample: layer-19-shaped, full m_axi depth",
                                        9, 16, 128, /*seed=*/101, /*pad_to_full_depth=*/true);
        } else if (std::strcmp(engine, "route") == 0) {
            fail = run_route_config("cosim-route: layer-20-shaped, full m_axi depth",
                                     18, 32, 128, 256,
                                     true, 1981659643, 31, true, 2105615761, 31,
                                     /*seed=*/102, /*saturation_stress=*/false, /*pad_to_full_depth=*/true);
        } else {
            printf("ERROR: unknown --cosim-only engine '%s' (expected maxpool/upsample/route)\n", engine);
            return 1;
        }
        if (!fail) {
            printf("COSIM CONFIG PASS\n");
            return 0;
        }
        printf("COSIM CONFIG FAILED\n");
        return 1;
    }

    int fail = 0;

    // ---- MaxPool configs ----
    //
    // pack4 NOTE: every `ch` argument in this section is a multiple of 4,
    // which the baseline project's versions of these configs were not
    // (MP-B used ch=1, MP-C/MP-E ch=3, MP-G ch=6). That is the ch % 4 == 0
    // contract the packed engines assert - see HW/pack4.h. Each config's
    // actual PURPOSE is unchanged: MP-C still has odd SPATIAL dims (5x7),
    // MP-B is still the minimal single-output-pixel case, MP-G is still
    // non-square. Only "channel count that is not a multiple of 4" is gone,
    // and that is now outside the supported contract rather than a case
    // these configs are failing to cover.
    //
    // MP-A: stride=2 basic case.
    fail |= run_maxpool_config("MP-A: stride2 basic", 16, 16, 8, 2, 0, 0, 1);
    // MP-B: stride=2 minimal, single output pixel.
    fail |= run_maxpool_config("MP-B: stride2 minimal (2x2x4->1x1x4)", 2, 2, 4, 2, 0, 0, 2);
    // MP-C: stride=2, odd input dim - NOT a real-network case (every real
    // stride=2 layer has even dims), but proves the integer-division
    // truncation (dropping the last row/col) is well-defined, not garbage.
    fail |= run_maxpool_config("MP-C: stride2 odd-dim (boundary only, not a real case)", 5, 7, 4, 2, 0, 0, 3);
    // MP-D: stride=1 + pad, layer-11-shaped exactly (9x16x512).
    fail |= run_maxpool_config("MP-D: stride1+pad, layer-11-shaped (9x16x512)", 9, 16, 512, 1, 1, 1, 4);
    // MP-E: stride=1 + pad on a different small shape - proves the pad
    // mechanism generalizes, isn't accidentally tied to layer 11's own numbers.
    fail |= run_maxpool_config("MP-E: stride1+pad, small synthetic shape", 5, 7, 4, 1, 1, 1, 5);
    // MP-F: ch == MAX_CH exactly.
    fail |= run_maxpool_config("MP-F: ch == MAX_CH exact", 4, 4, MAX_CH, 2, 0, 0, 6);
    // MP-G: non-square image, stride=2.
    fail |= run_maxpool_config("MP-G: non-square, stride2", 8, 12, 8, 2, 0, 0, 7);
    // MP-H: pad-value-dominance check - real values deliberately close to
    // -128 near the border, confirming -128 padding never wins a comparison
    // it shouldn't (a naive "pad with 0" bug would fail only this config).
    fail |= run_maxpool_config("MP-H: pad-value-dominance (border values near -128)",
                                9, 16, 4, 1, 1, 1, 8, /*border_stress=*/true);

    // ---- Upsample configs ----
    fail |= run_upsample_config("UP-A: basic", 4, 4, 8, 10);
    fail |= run_upsample_config("UP-B: layer-19-shaped (9x16x128->18x32x128)", 9, 16, 128, 11);
    fail |= run_upsample_config("UP-C: minimal (1x1x4->2x2x4)", 1, 1, 4, 12);
    fail |= run_upsample_config("UP-D: non-square", 5, 9, 8, 13);
    fail |= run_upsample_config("UP-E: ch == MAX_UPSAMPLE_CH exact", 3, 3, MAX_UPSAMPLE_CH, 14);

    // ---- Route/concat configs ----
    // Real per-layer multiplier/shift, layer 20 (model_manifest.json
    // source_requantization): source 19 (layer19, 128ch) and source 8
    // (layer8, 256ch).
    const int32_t LAYER20_SRC19_MULT = 1981659643, LAYER20_SRC19_SHIFT = 31;
    const int32_t LAYER20_SRC8_MULT  = 2105615761, LAYER20_SRC8_SHIFT  = 31;

    // RT-A: passthrough, layer-17-shaped (9x16x256, ch1=0).
    fail |= run_route_config("RT-A: passthrough, layer-17-shaped", 9, 16, 256, 0,
                              false, 0, 0, false, 0, 0, 20);
    // RT-B: passthrough, small synthetic shape.
    // pack4 NOTE: ch0/ch1 here are multiples of 4 where the baseline used
    // 13/0 (RT-B), 10/7 (RT-D) and 5/5 (RT-E). Same reasoning as the
    // MaxPool section above - HW/pack4.h's contract is stricter on ch0 in
    // particular, since src1's output offset ch0 must be a whole-word
    // boundary. Each config still tests what it was written to test.
    fail |= run_route_config("RT-B: passthrough, small synthetic", 5, 7, 16, 0,
                              false, 0, 0, false, 0, 0, 21);
    // RT-C: 2-source concat, layer-20-shaped, REAL multiplier/shift pairs -
    // also checks concat channel order (src0's channels land first).
    fail |= run_route_config("RT-C: 2-source concat, layer-20-shaped, real mult/shift", 18, 32, 128, 256,
                              true, LAYER20_SRC19_MULT, LAYER20_SRC19_SHIFT,
                              true, LAYER20_SRC8_MULT, LAYER20_SRC8_SHIFT, 22);
    // RT-D: 2-source concat, small synthetic shape + non-real mult/shift -
    // proves generality beyond the one real number pair.
    fail |= run_route_config("RT-D: 2-source concat, small synthetic mult/shift", 4, 5, 12, 8,
                              true, 1000000000, 20, true, 500000000, 15, 23);
    // RT-E: one source passthrough, the other requantize - not a real case
    // in this network, but the only config exercising independent
    // per-source operation as a general mechanism rather than coincidentally
    // always-both-same.
    fail |= run_route_config("RT-E: mixed passthrough+requantize", 3, 3, 8, 4,
                              false, 0, 0, true, 1500000000, 24, 25);
    // RT-F: ch0+ch1 == MAX_ROUTE_TOTAL_CH exactly.
    fail |= run_route_config("RT-F: ch0+ch1 == MAX_ROUTE_TOTAL_CH exact", 2, 2, 256, 256,
                              true, 900000000, 25, true, 900000000, 25, 26);
    // RT-G: saturation stress - extreme input values (+-128) with a small
    // shift, deliberately pushing scaled results past +-127/-128, since the
    // "normal" configs above may never hit saturate()'s clamp branches at all.
    fail |= run_route_config("RT-G: saturation stress", 3, 3, 4, 4,
                              true, 2000000000, 2, true, -2000000000, 2, 27,
                              /*saturation_stress=*/true);

    // ---- Real-layer suites ----
    int real_maxpool_fail = 0;
    for (unsigned i = 0; i < NUM_REAL_MAXPOOL_LAYERS; i++) {
        real_maxpool_fail |= run_real_maxpool_layer(REAL_MAXPOOL_LAYERS[i]);
    }
    printf(real_maxpool_fail ? "ONE OR MORE REAL MAXPOOL LAYERS FAILED\n" : "ALL REAL MAXPOOL LAYERS PASS\n");
    fail |= real_maxpool_fail;

    int real_upsample_fail = 0;
    for (unsigned i = 0; i < NUM_REAL_UPSAMPLE_LAYERS; i++) {
        real_upsample_fail |= run_real_upsample_layer(REAL_UPSAMPLE_LAYERS[i]);
    }
    printf(real_upsample_fail ? "ONE OR MORE REAL UPSAMPLE LAYERS FAILED\n" : "ALL REAL UPSAMPLE LAYERS PASS\n");
    fail |= real_upsample_fail;

    int real_route_fail = 0;
    for (unsigned i = 0; i < NUM_REAL_ROUTE_LAYERS; i++) {
        real_route_fail |= run_real_route_layer(REAL_ROUTE_LAYERS[i]);
    }
    printf(real_route_fail ? "ONE OR MORE REAL ROUTE LAYERS FAILED\n" : "ALL REAL ROUTE LAYERS PASS\n");
    fail |= real_route_fail;

    if (!fail) {
        printf("ALL CONFIGS PASS\n");
        return 0;
    }
    printf("ONE OR MORE CONFIGS FAILED\n");
    return 1;
}
