-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity maxpool_engine_maxpool_engine_Pipeline_MAXPOOL_WRITE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_WR_BUS_0_AWVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_0_AWREADY : IN STD_LOGIC;
    m_axi_WR_BUS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WR_BUS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_WVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_0_WREADY : IN STD_LOGIC;
    m_axi_WR_BUS_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_WLAST : OUT STD_LOGIC;
    m_axi_WR_BUS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_ARVALID : OUT STD_LOGIC;
    m_axi_WR_BUS_0_ARREADY : IN STD_LOGIC;
    m_axi_WR_BUS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WR_BUS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WR_BUS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WR_BUS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_RVALID : IN STD_LOGIC;
    m_axi_WR_BUS_0_RREADY : OUT STD_LOGIC;
    m_axi_WR_BUS_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WR_BUS_0_RLAST : IN STD_LOGIC;
    m_axi_WR_BUS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_WR_BUS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_BVALID : IN STD_LOGIC;
    m_axi_WR_BUS_0_BREADY : OUT STD_LOGIC;
    m_axi_WR_BUS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WR_BUS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WR_BUS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ch_words : IN STD_LOGIC_VECTOR (13 downto 0);
    sext_ln69 : IN STD_LOGIC_VECTOR (61 downto 0);
    maxval_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    maxval_ce0 : OUT STD_LOGIC;
    maxval_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of maxpool_engine_maxpool_engine_Pipeline_MAXPOOL_WRITE is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln141_fu_111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal WR_BUS_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal maxval_load_reg_160 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln141_1_fu_123_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal w_fu_58 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln141_fu_117_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_w_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal maxval_ce0_local : STD_LOGIC;
    signal zext_ln141_fu_107_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component maxpool_engine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component maxpool_engine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    w_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln141_fu_111_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    w_fu_58 <= add_ln141_fu_117_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_58 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                maxval_load_reg_160 <= maxval_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    WR_BUS_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_WR_BUS_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            WR_BUS_blk_n_W <= m_axi_WR_BUS_0_WREADY;
        else 
            WR_BUS_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln141_fu_117_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_w_1) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_WR_BUS_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_WR_BUS_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_WR_BUS_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_WR_BUS_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_WR_BUS_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_WR_BUS_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln141_fu_111_p2)
    begin
        if (((icmp_ln141_fu_111_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_w_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, w_fu_58, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_w_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_w_1 <= w_fu_58;
        end if; 
    end process;

    icmp_ln141_fu_111_p2 <= "1" when (zext_ln141_fu_107_p1 = ch_words) else "0";
    m_axi_WR_BUS_0_ARADDR <= ap_const_lv64_0;
    m_axi_WR_BUS_0_ARBURST <= ap_const_lv2_0;
    m_axi_WR_BUS_0_ARCACHE <= ap_const_lv4_0;
    m_axi_WR_BUS_0_ARID <= ap_const_lv1_0;
    m_axi_WR_BUS_0_ARLEN <= ap_const_lv32_0;
    m_axi_WR_BUS_0_ARLOCK <= ap_const_lv2_0;
    m_axi_WR_BUS_0_ARPROT <= ap_const_lv3_0;
    m_axi_WR_BUS_0_ARQOS <= ap_const_lv4_0;
    m_axi_WR_BUS_0_ARREGION <= ap_const_lv4_0;
    m_axi_WR_BUS_0_ARSIZE <= ap_const_lv3_0;
    m_axi_WR_BUS_0_ARUSER <= ap_const_lv1_0;
    m_axi_WR_BUS_0_ARVALID <= ap_const_logic_0;
    m_axi_WR_BUS_0_AWADDR <= ap_const_lv64_0;
    m_axi_WR_BUS_0_AWBURST <= ap_const_lv2_0;
    m_axi_WR_BUS_0_AWCACHE <= ap_const_lv4_0;
    m_axi_WR_BUS_0_AWID <= ap_const_lv1_0;
    m_axi_WR_BUS_0_AWLEN <= ap_const_lv32_0;
    m_axi_WR_BUS_0_AWLOCK <= ap_const_lv2_0;
    m_axi_WR_BUS_0_AWPROT <= ap_const_lv3_0;
    m_axi_WR_BUS_0_AWQOS <= ap_const_lv4_0;
    m_axi_WR_BUS_0_AWREGION <= ap_const_lv4_0;
    m_axi_WR_BUS_0_AWSIZE <= ap_const_lv3_0;
    m_axi_WR_BUS_0_AWUSER <= ap_const_lv1_0;
    m_axi_WR_BUS_0_AWVALID <= ap_const_logic_0;
    m_axi_WR_BUS_0_BREADY <= ap_const_logic_0;
    m_axi_WR_BUS_0_RREADY <= ap_const_logic_0;
    m_axi_WR_BUS_0_WDATA <= maxval_load_reg_160;
    m_axi_WR_BUS_0_WID <= ap_const_lv1_0;
    m_axi_WR_BUS_0_WLAST <= ap_const_logic_0;
    m_axi_WR_BUS_0_WSTRB <= ap_const_lv4_F;
    m_axi_WR_BUS_0_WUSER <= ap_const_lv1_0;

    m_axi_WR_BUS_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_WR_BUS_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_WR_BUS_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    maxval_address0 <= zext_ln141_1_fu_123_p1(7 - 1 downto 0);
    maxval_ce0 <= maxval_ce0_local;

    maxval_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            maxval_ce0_local <= ap_const_logic_1;
        else 
            maxval_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln141_1_fu_123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_w_1),64));
    zext_ln141_fu_107_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_w_1),14));
end behav;
