-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity maxpool_engine_maxpool_engine_Pipeline_MAXPOOL_UPDATE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_RD_BUS_0_AWVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_0_AWREADY : IN STD_LOGIC;
    m_axi_RD_BUS_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_RD_BUS_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_WVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_0_WREADY : IN STD_LOGIC;
    m_axi_RD_BUS_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_WLAST : OUT STD_LOGIC;
    m_axi_RD_BUS_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_ARVALID : OUT STD_LOGIC;
    m_axi_RD_BUS_0_ARREADY : IN STD_LOGIC;
    m_axi_RD_BUS_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_RD_BUS_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_RD_BUS_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_RD_BUS_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_RVALID : IN STD_LOGIC;
    m_axi_RD_BUS_0_RREADY : OUT STD_LOGIC;
    m_axi_RD_BUS_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_RD_BUS_0_RLAST : IN STD_LOGIC;
    m_axi_RD_BUS_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_RD_BUS_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_BVALID : IN STD_LOGIC;
    m_axi_RD_BUS_0_BREADY : OUT STD_LOGIC;
    m_axi_RD_BUS_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_RD_BUS_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_RD_BUS_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ch_words : IN STD_LOGIC_VECTOR (13 downto 0);
    sext_ln101 : IN STD_LOGIC_VECTOR (61 downto 0);
    maxval_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    maxval_ce0 : OUT STD_LOGIC;
    maxval_we0 : OUT STD_LOGIC;
    maxval_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    maxval_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    maxval_ce1 : OUT STD_LOGIC;
    maxval_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    cmp35 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln98 : IN STD_LOGIC_VECTOR (0 downto 0);
    in_c : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln58 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_r : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln57 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of maxpool_engine_maxpool_engine_Pipeline_MAXPOOL_UPDATE is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal and_ln98_reg_435 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln101_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal RD_BUS_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal and_ln98_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal maxval_addr_reg_443 : STD_LOGIC_VECTOR (6 downto 0);
    signal maxval_addr_reg_443_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal a_fu_218_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_reg_449 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_fu_222_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_455 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_1_reg_461 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_1_reg_466 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_reg_471 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_reg_476 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_2_reg_481 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_2_reg_486 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_491 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_496 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_3_reg_501 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_3_reg_506 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_511 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_reg_516 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln101_1_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal w_fu_94 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln101_fu_196_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_w_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal maxval_ce1_local : STD_LOGIC;
    signal maxval_we0_local : STD_LOGIC;
    signal nm_2_fu_414_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal maxval_ce0_local : STD_LOGIC;
    signal zext_ln101_fu_186_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln128_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal nm_1_in_fu_338_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln128_1_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_348_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_355_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal nm_5_in_fu_362_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln128_2_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_374_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_5_fu_381_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal nm_3_in_fu_388_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln128_3_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal nm_fu_400_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal nm_1_fu_407_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component maxpool_engine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component maxpool_engine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    w_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln101_fu_190_p2 = ap_const_lv1_0))) then 
                    w_fu_94 <= add_ln101_fu_196_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_94 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_1_reg_461 <= m_axi_RD_BUS_0_RDATA(15 downto 8);
                a_2_reg_481 <= m_axi_RD_BUS_0_RDATA(23 downto 16);
                a_3_reg_501 <= m_axi_RD_BUS_0_RDATA(31 downto 24);
                a_reg_449 <= a_fu_218_p1;
                and_ln98_reg_435 <= and_ln98_fu_172_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                b_1_reg_466 <= maxval_q1(15 downto 8);
                b_2_reg_486 <= maxval_q1(23 downto 16);
                b_3_reg_506 <= maxval_q1(31 downto 24);
                b_reg_455 <= b_fu_222_p1;
                maxval_addr_reg_443 <= zext_ln101_1_fu_202_p1(7 - 1 downto 0);
                maxval_addr_reg_443_pp0_iter1_reg <= maxval_addr_reg_443;
                tmp_1_reg_491 <= m_axi_RD_BUS_0_RDATA(23 downto 16);
                tmp_2_reg_496 <= maxval_q1(23 downto 16);
                tmp_4_reg_511 <= m_axi_RD_BUS_0_RDATA(31 downto 24);
                tmp_6_reg_516 <= maxval_q1(31 downto 24);
                tmp_9_reg_471 <= m_axi_RD_BUS_0_RDATA(15 downto 8);
                tmp_s_reg_476 <= maxval_q1(15 downto 8);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    RD_BUS_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_RD_BUS_0_RVALID, and_ln98_reg_435, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_lv1_1 = and_ln98_reg_435) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            RD_BUS_blk_n_R <= m_axi_RD_BUS_0_RVALID;
        else 
            RD_BUS_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    a_fu_218_p1 <= m_axi_RD_BUS_0_RDATA(8 - 1 downto 0);
    add_ln101_fu_196_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_w_2) + unsigned(ap_const_lv8_1));
    and_ln98_fu_172_p2 <= (icmp_ln98 and cmp35);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_RD_BUS_0_RVALID, and_ln98_reg_435)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_const_lv1_1 = and_ln98_reg_435) and (m_axi_RD_BUS_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln101_fu_190_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln101_fu_190_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_w_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, w_fu_94, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_w_2 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_w_2 <= w_fu_94;
        end if; 
    end process;

    b_fu_222_p1 <= maxval_q1(8 - 1 downto 0);
    icmp_ln101_fu_190_p2 <= "1" when (zext_ln101_fu_186_p1 = ch_words) else "0";
    icmp_ln128_1_fu_344_p2 <= "1" when (signed(a_1_reg_461) > signed(b_1_reg_466)) else "0";
    icmp_ln128_2_fu_370_p2 <= "1" when (signed(a_2_reg_481) > signed(b_2_reg_486)) else "0";
    icmp_ln128_3_fu_396_p2 <= "1" when (signed(a_3_reg_501) > signed(b_3_reg_506)) else "0";
    icmp_ln128_fu_334_p2 <= "1" when (signed(a_reg_449) > signed(b_reg_455)) else "0";
    m_axi_RD_BUS_0_ARADDR <= ap_const_lv64_0;
    m_axi_RD_BUS_0_ARBURST <= ap_const_lv2_0;
    m_axi_RD_BUS_0_ARCACHE <= ap_const_lv4_0;
    m_axi_RD_BUS_0_ARID <= ap_const_lv1_0;
    m_axi_RD_BUS_0_ARLEN <= ap_const_lv32_0;
    m_axi_RD_BUS_0_ARLOCK <= ap_const_lv2_0;
    m_axi_RD_BUS_0_ARPROT <= ap_const_lv3_0;
    m_axi_RD_BUS_0_ARQOS <= ap_const_lv4_0;
    m_axi_RD_BUS_0_ARREGION <= ap_const_lv4_0;
    m_axi_RD_BUS_0_ARSIZE <= ap_const_lv3_0;
    m_axi_RD_BUS_0_ARUSER <= ap_const_lv1_0;
    m_axi_RD_BUS_0_ARVALID <= ap_const_logic_0;
    m_axi_RD_BUS_0_AWADDR <= ap_const_lv64_0;
    m_axi_RD_BUS_0_AWBURST <= ap_const_lv2_0;
    m_axi_RD_BUS_0_AWCACHE <= ap_const_lv4_0;
    m_axi_RD_BUS_0_AWID <= ap_const_lv1_0;
    m_axi_RD_BUS_0_AWLEN <= ap_const_lv32_0;
    m_axi_RD_BUS_0_AWLOCK <= ap_const_lv2_0;
    m_axi_RD_BUS_0_AWPROT <= ap_const_lv3_0;
    m_axi_RD_BUS_0_AWQOS <= ap_const_lv4_0;
    m_axi_RD_BUS_0_AWREGION <= ap_const_lv4_0;
    m_axi_RD_BUS_0_AWSIZE <= ap_const_lv3_0;
    m_axi_RD_BUS_0_AWUSER <= ap_const_lv1_0;
    m_axi_RD_BUS_0_AWVALID <= ap_const_logic_0;
    m_axi_RD_BUS_0_BREADY <= ap_const_logic_0;

    m_axi_RD_BUS_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln98_reg_435, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln98_reg_435) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_RD_BUS_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_RD_BUS_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_RD_BUS_0_WDATA <= ap_const_lv32_0;
    m_axi_RD_BUS_0_WID <= ap_const_lv1_0;
    m_axi_RD_BUS_0_WLAST <= ap_const_logic_0;
    m_axi_RD_BUS_0_WSTRB <= ap_const_lv4_0;
    m_axi_RD_BUS_0_WUSER <= ap_const_lv1_0;
    m_axi_RD_BUS_0_WVALID <= ap_const_logic_0;
    maxval_address0 <= maxval_addr_reg_443_pp0_iter1_reg;
    maxval_address1 <= zext_ln101_1_fu_202_p1(7 - 1 downto 0);
    maxval_ce0 <= maxval_ce0_local;

    maxval_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            maxval_ce0_local <= ap_const_logic_1;
        else 
            maxval_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    maxval_ce1 <= maxval_ce1_local;

    maxval_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            maxval_ce1_local <= ap_const_logic_1;
        else 
            maxval_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    maxval_d0 <= nm_2_fu_414_p3;
    maxval_we0 <= maxval_we0_local;

    maxval_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, and_ln98_reg_435, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln98_reg_435) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            maxval_we0_local <= ap_const_logic_1;
        else 
            maxval_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    nm_1_fu_407_p3 <= (tmp_6_reg_516 & nm_3_in_fu_388_p3);
    nm_1_in_fu_338_p3 <= 
        a_reg_449 when (icmp_ln128_fu_334_p2(0) = '1') else 
        b_reg_455;
    nm_2_fu_414_p3 <= 
        nm_fu_400_p3 when (icmp_ln128_3_fu_396_p2(0) = '1') else 
        nm_1_fu_407_p3;
    nm_3_in_fu_388_p3 <= 
        tmp_3_fu_374_p3 when (icmp_ln128_2_fu_370_p2(0) = '1') else 
        tmp_5_fu_381_p3;
    nm_5_in_fu_362_p3 <= 
        tmp_7_fu_348_p3 when (icmp_ln128_1_fu_344_p2(0) = '1') else 
        tmp_8_fu_355_p3;
    nm_fu_400_p3 <= (tmp_4_reg_511 & nm_3_in_fu_388_p3);
    tmp_3_fu_374_p3 <= (tmp_1_reg_491 & nm_5_in_fu_362_p3);
    tmp_5_fu_381_p3 <= (tmp_2_reg_496 & nm_5_in_fu_362_p3);
    tmp_7_fu_348_p3 <= (tmp_9_reg_471 & nm_1_in_fu_338_p3);
    tmp_8_fu_355_p3 <= (tmp_s_reg_476 & nm_1_in_fu_338_p3);
    zext_ln101_1_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_w_2),64));
    zext_ln101_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_w_2),14));
end behav;
