// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module upsample_engine_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_WR_BUS_0_AWVALID,
        m_axi_WR_BUS_0_AWREADY,
        m_axi_WR_BUS_0_AWADDR,
        m_axi_WR_BUS_0_AWID,
        m_axi_WR_BUS_0_AWLEN,
        m_axi_WR_BUS_0_AWSIZE,
        m_axi_WR_BUS_0_AWBURST,
        m_axi_WR_BUS_0_AWLOCK,
        m_axi_WR_BUS_0_AWCACHE,
        m_axi_WR_BUS_0_AWPROT,
        m_axi_WR_BUS_0_AWQOS,
        m_axi_WR_BUS_0_AWREGION,
        m_axi_WR_BUS_0_AWUSER,
        m_axi_WR_BUS_0_WVALID,
        m_axi_WR_BUS_0_WREADY,
        m_axi_WR_BUS_0_WDATA,
        m_axi_WR_BUS_0_WSTRB,
        m_axi_WR_BUS_0_WLAST,
        m_axi_WR_BUS_0_WID,
        m_axi_WR_BUS_0_WUSER,
        m_axi_WR_BUS_0_ARVALID,
        m_axi_WR_BUS_0_ARREADY,
        m_axi_WR_BUS_0_ARADDR,
        m_axi_WR_BUS_0_ARID,
        m_axi_WR_BUS_0_ARLEN,
        m_axi_WR_BUS_0_ARSIZE,
        m_axi_WR_BUS_0_ARBURST,
        m_axi_WR_BUS_0_ARLOCK,
        m_axi_WR_BUS_0_ARCACHE,
        m_axi_WR_BUS_0_ARPROT,
        m_axi_WR_BUS_0_ARQOS,
        m_axi_WR_BUS_0_ARREGION,
        m_axi_WR_BUS_0_ARUSER,
        m_axi_WR_BUS_0_RVALID,
        m_axi_WR_BUS_0_RREADY,
        m_axi_WR_BUS_0_RDATA,
        m_axi_WR_BUS_0_RLAST,
        m_axi_WR_BUS_0_RID,
        m_axi_WR_BUS_0_RFIFONUM,
        m_axi_WR_BUS_0_RUSER,
        m_axi_WR_BUS_0_RRESP,
        m_axi_WR_BUS_0_BVALID,
        m_axi_WR_BUS_0_BREADY,
        m_axi_WR_BUS_0_BRESP,
        m_axi_WR_BUS_0_BID,
        m_axi_WR_BUS_0_BUSER,
        ch_words,
        zext_ln4_1,
        px_address0,
        px_ce0,
        px_q0,
        zext_ln41_1,
        zext_ln4,
        mul_ln41,
        add_ln44,
        ofmap
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_WR_BUS_0_AWVALID;
input   m_axi_WR_BUS_0_AWREADY;
output  [63:0] m_axi_WR_BUS_0_AWADDR;
output  [0:0] m_axi_WR_BUS_0_AWID;
output  [31:0] m_axi_WR_BUS_0_AWLEN;
output  [2:0] m_axi_WR_BUS_0_AWSIZE;
output  [1:0] m_axi_WR_BUS_0_AWBURST;
output  [1:0] m_axi_WR_BUS_0_AWLOCK;
output  [3:0] m_axi_WR_BUS_0_AWCACHE;
output  [2:0] m_axi_WR_BUS_0_AWPROT;
output  [3:0] m_axi_WR_BUS_0_AWQOS;
output  [3:0] m_axi_WR_BUS_0_AWREGION;
output  [0:0] m_axi_WR_BUS_0_AWUSER;
output   m_axi_WR_BUS_0_WVALID;
input   m_axi_WR_BUS_0_WREADY;
output  [31:0] m_axi_WR_BUS_0_WDATA;
output  [3:0] m_axi_WR_BUS_0_WSTRB;
output   m_axi_WR_BUS_0_WLAST;
output  [0:0] m_axi_WR_BUS_0_WID;
output  [0:0] m_axi_WR_BUS_0_WUSER;
output   m_axi_WR_BUS_0_ARVALID;
input   m_axi_WR_BUS_0_ARREADY;
output  [63:0] m_axi_WR_BUS_0_ARADDR;
output  [0:0] m_axi_WR_BUS_0_ARID;
output  [31:0] m_axi_WR_BUS_0_ARLEN;
output  [2:0] m_axi_WR_BUS_0_ARSIZE;
output  [1:0] m_axi_WR_BUS_0_ARBURST;
output  [1:0] m_axi_WR_BUS_0_ARLOCK;
output  [3:0] m_axi_WR_BUS_0_ARCACHE;
output  [2:0] m_axi_WR_BUS_0_ARPROT;
output  [3:0] m_axi_WR_BUS_0_ARQOS;
output  [3:0] m_axi_WR_BUS_0_ARREGION;
output  [0:0] m_axi_WR_BUS_0_ARUSER;
input   m_axi_WR_BUS_0_RVALID;
output   m_axi_WR_BUS_0_RREADY;
input  [31:0] m_axi_WR_BUS_0_RDATA;
input   m_axi_WR_BUS_0_RLAST;
input  [0:0] m_axi_WR_BUS_0_RID;
input  [8:0] m_axi_WR_BUS_0_RFIFONUM;
input  [0:0] m_axi_WR_BUS_0_RUSER;
input  [1:0] m_axi_WR_BUS_0_RRESP;
input   m_axi_WR_BUS_0_BVALID;
output   m_axi_WR_BUS_0_BREADY;
input  [1:0] m_axi_WR_BUS_0_BRESP;
input  [0:0] m_axi_WR_BUS_0_BID;
input  [0:0] m_axi_WR_BUS_0_BUSER;
input  [13:0] ch_words;
input  [15:0] zext_ln4_1;
output  [5:0] px_address0;
output   px_ce0;
input  [31:0] px_q0;
input  [14:0] zext_ln41_1;
input  [14:0] zext_ln4;
input  [29:0] mul_ln41;
input  [31:0] add_ln44;
input  [63:0] ofmap;

reg ap_idle;
reg m_axi_WR_BUS_0_AWVALID;
reg m_axi_WR_BUS_0_WVALID;
reg m_axi_WR_BUS_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_595;
reg   [0:0] first_iter_1_mid2_reg_591;
reg    ap_predicate_op93_writereq_state3;
reg    ap_block_state3_io_grp1;
reg   [0:0] icmp_ln70_2_reg_604;
reg   [0:0] icmp_ln70_2_reg_604_pp0_iter7_reg;
reg   [0:0] icmp_ln66_1_reg_608;
reg   [0:0] icmp_ln66_1_reg_608_pp0_iter7_reg;
reg    ap_predicate_op103_writeresp_state9;
reg    ap_block_state9_pp0_stage0_iter8_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln65_fu_251_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    WR_BUS_blk_n_B;
wire    ap_block_pp0_stage0_grp1;
reg    WR_BUS_blk_n_W;
reg    WR_BUS_blk_n_AW;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] zext_ln4_cast_fu_200_p1;
reg   [15:0] zext_ln4_cast_reg_572;
wire   [63:0] zext_ln41_1_cast_fu_204_p1;
reg   [63:0] zext_ln41_1_cast_reg_577;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [61:0] sext_ln66_mid2_v_reg_586;
wire   [0:0] first_iter_1_mid2_fu_407_p3;
wire   [0:0] first_iter_0_fu_423_p2;
wire   [0:0] icmp_ln70_2_fu_444_p2;
reg   [0:0] icmp_ln70_2_reg_604_pp0_iter2_reg;
reg   [0:0] icmp_ln70_2_reg_604_pp0_iter3_reg;
reg   [0:0] icmp_ln70_2_reg_604_pp0_iter4_reg;
reg   [0:0] icmp_ln70_2_reg_604_pp0_iter5_reg;
reg   [0:0] icmp_ln70_2_reg_604_pp0_iter6_reg;
wire   [0:0] icmp_ln66_1_fu_449_p2;
reg   [0:0] icmp_ln66_1_reg_608_pp0_iter2_reg;
reg   [0:0] icmp_ln66_1_reg_608_pp0_iter3_reg;
reg   [0:0] icmp_ln66_1_reg_608_pp0_iter4_reg;
reg   [0:0] icmp_ln66_1_reg_608_pp0_iter5_reg;
reg   [0:0] icmp_ln66_1_reg_608_pp0_iter6_reg;
reg   [31:0] px_load_reg_612;
wire   [63:0] zext_ln70_1_fu_429_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln65_fu_494_p1;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [6:0] w_fu_106;
wire   [6:0] add_ln70_fu_434_p2;
wire    ap_loop_init;
reg   [1:0] dx_fu_110;
wire   [1:0] select_ln66_fu_415_p3;
reg   [15:0] indvar_flatten_fu_114;
wire   [15:0] select_ln66_1_fu_461_p3;
reg   [1:0] dy_fu_118;
wire   [1:0] select_ln65_1_fu_287_p3;
reg   [15:0] indvar_flatten35_fu_122;
wire   [15:0] add_ln65_fu_256_p2;
reg    px_ce0_local;
wire   [13:0] zext_ln70_fu_242_p1;
wire   [0:0] icmp_ln66_fu_268_p2;
wire   [1:0] add_ln65_3_fu_281_p2;
wire   [0:0] trunc_ln65_fu_295_p1;
wire   [29:0] select_ln65_3_fu_299_p3;
wire   [29:0] and_ln65_fu_307_p2;
wire   [30:0] sext_ln66_mid2_v_v_v_v_v_v_v_v_v_fu_312_p3;
wire   [31:0] zext_ln65_fu_320_p1;
wire   [31:0] add_ln65_1_fu_324_p2;
wire   [33:0] sext_ln66_mid2_v_v_v_v_v_fu_329_p3;
wire   [63:0] zext_ln65_1_fu_337_p1;
wire   [63:0] add_ln65_2_fu_341_p2;
wire   [0:0] first_iter_145_fu_356_p2;
wire   [0:0] icmp_ln70_1_fu_368_p2;
wire   [0:0] icmp_ln70_fu_246_p2;
wire   [1:0] select_ln65_fu_273_p3;
wire   [0:0] select_ln65_2_fu_373_p3;
wire   [0:0] empty_26_fu_387_p2;
wire   [1:0] dx_2_fu_381_p2;
wire   [0:0] first_iter_1_mid1_fu_401_p2;
wire   [0:0] or_ln65_fu_362_p2;
wire   [6:0] w_1_mid2_fu_393_p3;
wire   [13:0] zext_ln70_2_fu_440_p1;
wire   [15:0] add_ln66_1_fu_455_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 w_fu_106 = 7'd0;
#0 dx_fu_110 = 2'd0;
#0 indvar_flatten_fu_114 = 16'd0;
#0 dy_fu_118 = 2'd0;
#0 indvar_flatten35_fu_122 = 16'd0;
#0 ap_done_reg = 1'b0;
end

upsample_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            dx_fu_110 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln65_fu_251_p2 == 1'd0))) begin
            dx_fu_110 <= select_ln66_fu_415_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            dy_fu_118 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln65_fu_251_p2 == 1'd0))) begin
            dy_fu_118 <= select_ln65_1_fu_287_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten35_fu_122 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln65_fu_251_p2 == 1'd0))) begin
            indvar_flatten35_fu_122 <= add_ln65_fu_256_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_114 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln65_fu_251_p2 == 1'd0))) begin
            indvar_flatten_fu_114 <= select_ln66_1_fu_461_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_106 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln65_fu_251_p2 == 1'd0))) begin
            w_fu_106 <= add_ln70_fu_434_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        first_iter_0_reg_595 <= first_iter_0_fu_423_p2;
        first_iter_1_mid2_reg_591 <= first_iter_1_mid2_fu_407_p3;
        icmp_ln66_1_reg_608 <= icmp_ln66_1_fu_449_p2;
        icmp_ln70_2_reg_604 <= icmp_ln70_2_fu_444_p2;
        sext_ln66_mid2_v_reg_586 <= {{add_ln65_2_fu_341_p2[63:2]}};
        zext_ln4_cast_reg_572[14 : 0] <= zext_ln4_cast_fu_200_p1[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln66_1_reg_608_pp0_iter2_reg <= icmp_ln66_1_reg_608;
        icmp_ln66_1_reg_608_pp0_iter3_reg <= icmp_ln66_1_reg_608_pp0_iter2_reg;
        icmp_ln66_1_reg_608_pp0_iter4_reg <= icmp_ln66_1_reg_608_pp0_iter3_reg;
        icmp_ln66_1_reg_608_pp0_iter5_reg <= icmp_ln66_1_reg_608_pp0_iter4_reg;
        icmp_ln66_1_reg_608_pp0_iter6_reg <= icmp_ln66_1_reg_608_pp0_iter5_reg;
        icmp_ln66_1_reg_608_pp0_iter7_reg <= icmp_ln66_1_reg_608_pp0_iter6_reg;
        icmp_ln70_2_reg_604_pp0_iter2_reg <= icmp_ln70_2_reg_604;
        icmp_ln70_2_reg_604_pp0_iter3_reg <= icmp_ln70_2_reg_604_pp0_iter2_reg;
        icmp_ln70_2_reg_604_pp0_iter4_reg <= icmp_ln70_2_reg_604_pp0_iter3_reg;
        icmp_ln70_2_reg_604_pp0_iter5_reg <= icmp_ln70_2_reg_604_pp0_iter4_reg;
        icmp_ln70_2_reg_604_pp0_iter6_reg <= icmp_ln70_2_reg_604_pp0_iter5_reg;
        icmp_ln70_2_reg_604_pp0_iter7_reg <= icmp_ln70_2_reg_604_pp0_iter6_reg;
        px_load_reg_612 <= px_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        zext_ln41_1_cast_reg_577[14 : 0] <= zext_ln41_1_cast_fu_204_p1[14 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op93_writereq_state3 == 1'b1))) begin
        WR_BUS_blk_n_AW = m_axi_WR_BUS_0_AWREADY;
    end else begin
        WR_BUS_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op103_writeresp_state9 == 1'b1))) begin
        WR_BUS_blk_n_B = m_axi_WR_BUS_0_BVALID;
    end else begin
        WR_BUS_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        WR_BUS_blk_n_W = m_axi_WR_BUS_0_WREADY;
    end else begin
        WR_BUS_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln65_fu_251_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op93_writereq_state3 == 1'b1))) begin
        m_axi_WR_BUS_0_AWVALID = 1'b1;
    end else begin
        m_axi_WR_BUS_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op103_writeresp_state9 == 1'b1))) begin
        m_axi_WR_BUS_0_BREADY = 1'b1;
    end else begin
        m_axi_WR_BUS_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_WR_BUS_0_WVALID = 1'b1;
    end else begin
        m_axi_WR_BUS_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_ce0_local = 1'b1;
    end else begin
        px_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln65_1_fu_324_p2 = (zext_ln65_fu_320_p1 + add_ln44);

assign add_ln65_2_fu_341_p2 = (zext_ln65_1_fu_337_p1 + ofmap);

assign add_ln65_3_fu_281_p2 = (dy_fu_118 + 2'd1);

assign add_ln65_fu_256_p2 = (indvar_flatten35_fu_122 + 16'd1);

assign add_ln66_1_fu_455_p2 = (indvar_flatten_fu_114 + 16'd1);

assign add_ln70_fu_434_p2 = (w_1_mid2_fu_393_p3 + 7'd1);

assign and_ln65_fu_307_p2 = (select_ln65_3_fu_299_p3 & mul_ln41);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8_grp1)) | ((m_axi_WR_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8_grp1)) | ((m_axi_WR_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8_grp1)) | ((m_axi_WR_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io_grp1)));
end

always @ (*) begin
    ap_block_state3_io_grp1 = ((m_axi_WR_BUS_0_AWREADY == 1'b0) & (ap_predicate_op93_writereq_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8_grp1 = ((m_axi_WR_BUS_0_BVALID == 1'b0) & (ap_predicate_op103_writeresp_state9 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op103_writeresp_state9 = ((icmp_ln66_1_reg_608_pp0_iter7_reg == 1'd1) & (icmp_ln70_2_reg_604_pp0_iter7_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op93_writereq_state3 = ((first_iter_1_mid2_reg_591 == 1'd1) & (first_iter_0_reg_595 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign dx_2_fu_381_p2 = (select_ln65_fu_273_p3 + 2'd1);

assign empty_26_fu_387_p2 = (select_ln65_2_fu_373_p3 | icmp_ln66_fu_268_p2);

assign first_iter_0_fu_423_p2 = ((w_1_mid2_fu_393_p3 == 7'd0) ? 1'b1 : 1'b0);

assign first_iter_145_fu_356_p2 = ((dx_fu_110 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_401_p2 = ((dx_2_fu_381_p2 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid2_fu_407_p3 = ((select_ln65_2_fu_373_p3[0:0] == 1'b1) ? first_iter_1_mid1_fu_401_p2 : or_ln65_fu_362_p2);

assign icmp_ln65_fu_251_p2 = ((indvar_flatten35_fu_122 == zext_ln4_1) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_449_p2 = ((select_ln66_fu_415_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_268_p2 = ((indvar_flatten_fu_114 == zext_ln4_cast_reg_572) ? 1'b1 : 1'b0);

assign icmp_ln70_1_fu_368_p2 = ((ch_words == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln70_2_fu_444_p2 = ((zext_ln70_2_fu_440_p1 == ch_words) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_246_p2 = ((zext_ln70_fu_242_p1 == ch_words) ? 1'b1 : 1'b0);

assign m_axi_WR_BUS_0_ARADDR = 64'd0;

assign m_axi_WR_BUS_0_ARBURST = 2'd0;

assign m_axi_WR_BUS_0_ARCACHE = 4'd0;

assign m_axi_WR_BUS_0_ARID = 1'd0;

assign m_axi_WR_BUS_0_ARLEN = 32'd0;

assign m_axi_WR_BUS_0_ARLOCK = 2'd0;

assign m_axi_WR_BUS_0_ARPROT = 3'd0;

assign m_axi_WR_BUS_0_ARQOS = 4'd0;

assign m_axi_WR_BUS_0_ARREGION = 4'd0;

assign m_axi_WR_BUS_0_ARSIZE = 3'd0;

assign m_axi_WR_BUS_0_ARUSER = 1'd0;

assign m_axi_WR_BUS_0_ARVALID = 1'b0;

assign m_axi_WR_BUS_0_AWADDR = sext_ln65_fu_494_p1;

assign m_axi_WR_BUS_0_AWBURST = 2'd0;

assign m_axi_WR_BUS_0_AWCACHE = 4'd0;

assign m_axi_WR_BUS_0_AWID = 1'd0;

assign m_axi_WR_BUS_0_AWLEN = zext_ln41_1_cast_reg_577;

assign m_axi_WR_BUS_0_AWLOCK = 2'd0;

assign m_axi_WR_BUS_0_AWPROT = 3'd0;

assign m_axi_WR_BUS_0_AWQOS = 4'd0;

assign m_axi_WR_BUS_0_AWREGION = 4'd0;

assign m_axi_WR_BUS_0_AWSIZE = 3'd0;

assign m_axi_WR_BUS_0_AWUSER = 1'd0;

assign m_axi_WR_BUS_0_RREADY = 1'b0;

assign m_axi_WR_BUS_0_WDATA = px_load_reg_612;

assign m_axi_WR_BUS_0_WID = 1'd0;

assign m_axi_WR_BUS_0_WLAST = 1'b0;

assign m_axi_WR_BUS_0_WSTRB = 4'd15;

assign m_axi_WR_BUS_0_WUSER = 1'd0;

assign or_ln65_fu_362_p2 = (icmp_ln66_fu_268_p2 | first_iter_145_fu_356_p2);

assign px_address0 = zext_ln70_1_fu_429_p1;

assign px_ce0 = px_ce0_local;

assign select_ln65_1_fu_287_p3 = ((icmp_ln66_fu_268_p2[0:0] == 1'b1) ? add_ln65_3_fu_281_p2 : dy_fu_118);

assign select_ln65_2_fu_373_p3 = ((icmp_ln66_fu_268_p2[0:0] == 1'b1) ? icmp_ln70_1_fu_368_p2 : icmp_ln70_fu_246_p2);

assign select_ln65_3_fu_299_p3 = ((trunc_ln65_fu_295_p1[0:0] == 1'b1) ? 30'd1073741823 : 30'd0);

assign select_ln65_fu_273_p3 = ((icmp_ln66_fu_268_p2[0:0] == 1'b1) ? 2'd0 : dx_fu_110);

assign select_ln66_1_fu_461_p3 = ((icmp_ln66_fu_268_p2[0:0] == 1'b1) ? 16'd1 : add_ln66_1_fu_455_p2);

assign select_ln66_fu_415_p3 = ((select_ln65_2_fu_373_p3[0:0] == 1'b1) ? dx_2_fu_381_p2 : select_ln65_fu_273_p3);

assign sext_ln65_fu_494_p1 = $signed(sext_ln66_mid2_v_reg_586);

assign sext_ln66_mid2_v_v_v_v_v_fu_329_p3 = {{add_ln65_1_fu_324_p2}, {2'd0}};

assign sext_ln66_mid2_v_v_v_v_v_v_v_v_v_fu_312_p3 = {{and_ln65_fu_307_p2}, {1'd0}};

assign trunc_ln65_fu_295_p1 = select_ln65_1_fu_287_p3[0:0];

assign w_1_mid2_fu_393_p3 = ((empty_26_fu_387_p2[0:0] == 1'b1) ? 7'd0 : w_fu_106);

assign zext_ln41_1_cast_fu_204_p1 = zext_ln41_1;

assign zext_ln4_cast_fu_200_p1 = zext_ln4;

assign zext_ln65_1_fu_337_p1 = sext_ln66_mid2_v_v_v_v_v_fu_329_p3;

assign zext_ln65_fu_320_p1 = sext_ln66_mid2_v_v_v_v_v_v_v_v_v_fu_312_p3;

assign zext_ln70_1_fu_429_p1 = w_1_mid2_fu_393_p3;

assign zext_ln70_2_fu_440_p1 = add_ln70_fu_434_p2;

assign zext_ln70_fu_242_p1 = w_fu_106;

always @ (posedge ap_clk) begin
    zext_ln4_cast_reg_572[15] <= 1'b0;
    zext_ln41_1_cast_reg_577[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //upsample_engine_upsample_engine_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_66_2_UPSAMPLE_WRITE
