// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv_engine_conv_engine_Pipeline_READ_CH_ELEMS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_RD_BUS_0_AWVALID,
        m_axi_RD_BUS_0_AWREADY,
        m_axi_RD_BUS_0_AWADDR,
        m_axi_RD_BUS_0_AWID,
        m_axi_RD_BUS_0_AWLEN,
        m_axi_RD_BUS_0_AWSIZE,
        m_axi_RD_BUS_0_AWBURST,
        m_axi_RD_BUS_0_AWLOCK,
        m_axi_RD_BUS_0_AWCACHE,
        m_axi_RD_BUS_0_AWPROT,
        m_axi_RD_BUS_0_AWQOS,
        m_axi_RD_BUS_0_AWREGION,
        m_axi_RD_BUS_0_AWUSER,
        m_axi_RD_BUS_0_WVALID,
        m_axi_RD_BUS_0_WREADY,
        m_axi_RD_BUS_0_WDATA,
        m_axi_RD_BUS_0_WSTRB,
        m_axi_RD_BUS_0_WLAST,
        m_axi_RD_BUS_0_WID,
        m_axi_RD_BUS_0_WUSER,
        m_axi_RD_BUS_0_ARVALID,
        m_axi_RD_BUS_0_ARREADY,
        m_axi_RD_BUS_0_ARADDR,
        m_axi_RD_BUS_0_ARID,
        m_axi_RD_BUS_0_ARLEN,
        m_axi_RD_BUS_0_ARSIZE,
        m_axi_RD_BUS_0_ARBURST,
        m_axi_RD_BUS_0_ARLOCK,
        m_axi_RD_BUS_0_ARCACHE,
        m_axi_RD_BUS_0_ARPROT,
        m_axi_RD_BUS_0_ARQOS,
        m_axi_RD_BUS_0_ARREGION,
        m_axi_RD_BUS_0_ARUSER,
        m_axi_RD_BUS_0_RVALID,
        m_axi_RD_BUS_0_RREADY,
        m_axi_RD_BUS_0_RDATA,
        m_axi_RD_BUS_0_RLAST,
        m_axi_RD_BUS_0_RID,
        m_axi_RD_BUS_0_RFIFONUM,
        m_axi_RD_BUS_0_RUSER,
        m_axi_RD_BUS_0_RRESP,
        m_axi_RD_BUS_0_BVALID,
        m_axi_RD_BUS_0_BREADY,
        m_axi_RD_BUS_0_BRESP,
        m_axi_RD_BUS_0_BID,
        m_axi_RD_BUS_0_BUSER,
        sext_ln1272_1,
        px_address0,
        px_ce0,
        px_we0,
        px_d0,
        px_1_address0,
        px_1_ce0,
        px_1_we0,
        px_1_d0,
        px_2_address0,
        px_2_ce0,
        px_2_we0,
        px_2_d0,
        px_3_address0,
        px_3_ce0,
        px_3_we0,
        px_3_d0,
        px_4_address0,
        px_4_ce0,
        px_4_we0,
        px_4_d0,
        px_5_address0,
        px_5_ce0,
        px_5_we0,
        px_5_d0,
        px_6_address0,
        px_6_ce0,
        px_6_we0,
        px_6_d0,
        px_7_address0,
        px_7_ce0,
        px_7_we0,
        px_7_d0,
        px_8_address0,
        px_8_ce0,
        px_8_we0,
        px_8_d0,
        px_9_address0,
        px_9_ce0,
        px_9_we0,
        px_9_d0,
        px_10_address0,
        px_10_ce0,
        px_10_we0,
        px_10_d0,
        px_11_address0,
        px_11_ce0,
        px_11_we0,
        px_11_d0,
        px_12_address0,
        px_12_ce0,
        px_12_we0,
        px_12_d0,
        px_13_address0,
        px_13_ce0,
        px_13_we0,
        px_13_d0,
        px_14_address0,
        px_14_ce0,
        px_14_we0,
        px_14_d0,
        px_15_address0,
        px_15_ce0,
        px_15_we0,
        px_15_d0,
        zext_ln1275,
        mul_ln471,
        ifmap,
        and_ln365_1,
        and_ln365,
        rev,
        rev325,
        c,
        pad_cast324,
        r,
        cmp12_i,
        icmp_ln366_1,
        add15_i,
        add11_i
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_RD_BUS_0_AWVALID;
input   m_axi_RD_BUS_0_AWREADY;
output  [63:0] m_axi_RD_BUS_0_AWADDR;
output  [0:0] m_axi_RD_BUS_0_AWID;
output  [31:0] m_axi_RD_BUS_0_AWLEN;
output  [2:0] m_axi_RD_BUS_0_AWSIZE;
output  [1:0] m_axi_RD_BUS_0_AWBURST;
output  [1:0] m_axi_RD_BUS_0_AWLOCK;
output  [3:0] m_axi_RD_BUS_0_AWCACHE;
output  [2:0] m_axi_RD_BUS_0_AWPROT;
output  [3:0] m_axi_RD_BUS_0_AWQOS;
output  [3:0] m_axi_RD_BUS_0_AWREGION;
output  [0:0] m_axi_RD_BUS_0_AWUSER;
output   m_axi_RD_BUS_0_WVALID;
input   m_axi_RD_BUS_0_WREADY;
output  [31:0] m_axi_RD_BUS_0_WDATA;
output  [3:0] m_axi_RD_BUS_0_WSTRB;
output   m_axi_RD_BUS_0_WLAST;
output  [0:0] m_axi_RD_BUS_0_WID;
output  [0:0] m_axi_RD_BUS_0_WUSER;
output   m_axi_RD_BUS_0_ARVALID;
input   m_axi_RD_BUS_0_ARREADY;
output  [63:0] m_axi_RD_BUS_0_ARADDR;
output  [0:0] m_axi_RD_BUS_0_ARID;
output  [31:0] m_axi_RD_BUS_0_ARLEN;
output  [2:0] m_axi_RD_BUS_0_ARSIZE;
output  [1:0] m_axi_RD_BUS_0_ARBURST;
output  [1:0] m_axi_RD_BUS_0_ARLOCK;
output  [3:0] m_axi_RD_BUS_0_ARCACHE;
output  [2:0] m_axi_RD_BUS_0_ARPROT;
output  [3:0] m_axi_RD_BUS_0_ARQOS;
output  [3:0] m_axi_RD_BUS_0_ARREGION;
output  [0:0] m_axi_RD_BUS_0_ARUSER;
input   m_axi_RD_BUS_0_RVALID;
output   m_axi_RD_BUS_0_RREADY;
input  [31:0] m_axi_RD_BUS_0_RDATA;
input   m_axi_RD_BUS_0_RLAST;
input  [0:0] m_axi_RD_BUS_0_RID;
input  [8:0] m_axi_RD_BUS_0_RFIFONUM;
input  [0:0] m_axi_RD_BUS_0_RUSER;
input  [1:0] m_axi_RD_BUS_0_RRESP;
input   m_axi_RD_BUS_0_BVALID;
output   m_axi_RD_BUS_0_BREADY;
input  [1:0] m_axi_RD_BUS_0_BRESP;
input  [0:0] m_axi_RD_BUS_0_BID;
input  [0:0] m_axi_RD_BUS_0_BUSER;
input  [17:0] sext_ln1272_1;
output  [2:0] px_address0;
output   px_ce0;
output   px_we0;
output  [7:0] px_d0;
output  [2:0] px_1_address0;
output   px_1_ce0;
output   px_1_we0;
output  [7:0] px_1_d0;
output  [2:0] px_2_address0;
output   px_2_ce0;
output   px_2_we0;
output  [7:0] px_2_d0;
output  [2:0] px_3_address0;
output   px_3_ce0;
output   px_3_we0;
output  [7:0] px_3_d0;
output  [2:0] px_4_address0;
output   px_4_ce0;
output   px_4_we0;
output  [7:0] px_4_d0;
output  [2:0] px_5_address0;
output   px_5_ce0;
output   px_5_we0;
output  [7:0] px_5_d0;
output  [2:0] px_6_address0;
output   px_6_ce0;
output   px_6_we0;
output  [7:0] px_6_d0;
output  [2:0] px_7_address0;
output   px_7_ce0;
output   px_7_we0;
output  [7:0] px_7_d0;
output  [2:0] px_8_address0;
output   px_8_ce0;
output   px_8_we0;
output  [7:0] px_8_d0;
output  [2:0] px_9_address0;
output   px_9_ce0;
output   px_9_we0;
output  [7:0] px_9_d0;
output  [2:0] px_10_address0;
output   px_10_ce0;
output   px_10_we0;
output  [7:0] px_10_d0;
output  [2:0] px_11_address0;
output   px_11_ce0;
output   px_11_we0;
output  [7:0] px_11_d0;
output  [2:0] px_12_address0;
output   px_12_ce0;
output   px_12_we0;
output  [7:0] px_12_d0;
output  [2:0] px_13_address0;
output   px_13_ce0;
output   px_13_we0;
output  [7:0] px_13_d0;
output  [2:0] px_14_address0;
output   px_14_ce0;
output   px_14_we0;
output  [7:0] px_14_d0;
output  [2:0] px_15_address0;
output   px_15_ce0;
output   px_15_we0;
output  [7:0] px_15_d0;
input  [15:0] zext_ln1275;
input  [31:0] mul_ln471;
input  [63:0] ifmap;
input  [0:0] and_ln365_1;
input  [0:0] and_ln365;
input  [0:0] rev;
input  [0:0] rev325;
input  [16:0] c;
input  [7:0] pad_cast324;
input  [16:0] r;
input  [0:0] cmp12_i;
input  [0:0] icmp_ln366_1;
input  [16:0] add15_i;
input  [16:0] add11_i;

reg ap_idle;
reg m_axi_RD_BUS_0_ARVALID;
reg m_axi_RD_BUS_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln497_reg_685;
reg   [0:0] and_ln365_3_reg_681;
reg    ap_predicate_op57_readreq_state2;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] icmp_ln497_reg_685_pp0_iter8_reg;
reg    ap_predicate_op65_read_state10;
reg    ap_block_state10_pp0_stage0_iter9;
wire   [0:0] icmp_ln497_fu_541_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    RD_BUS_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    RD_BUS_blk_n_R;
wire    ap_block_pp0_stage0;
wire   [0:0] and_ln365_3_fu_527_p2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln497_reg_685_pp0_iter1_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter2_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter3_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter4_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter5_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter6_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter7_reg;
reg   [0:0] icmp_ln497_reg_685_pp0_iter9_reg;
wire   [3:0] trunc_ln497_fu_553_p1;
reg   [3:0] trunc_ln497_reg_689;
reg   [3:0] trunc_ln497_reg_689_pp0_iter1_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter2_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter3_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter4_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter5_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter6_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter7_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter8_reg;
reg   [3:0] trunc_ln497_reg_689_pp0_iter9_reg;
reg   [2:0] lshr_ln1_reg_693;
reg   [2:0] lshr_ln1_reg_693_pp0_iter1_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter2_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter3_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter4_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter5_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter6_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter7_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter8_reg;
reg   [2:0] lshr_ln1_reg_693_pp0_iter9_reg;
reg   [63:0] RD_BUS_addr_reg_698;
wire   [1:0] trunc_ln91_fu_627_p1;
reg   [1:0] trunc_ln91_reg_704;
reg   [1:0] trunc_ln91_reg_704_pp0_iter1_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter2_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter3_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter4_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter5_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter6_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter7_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter8_reg;
reg   [1:0] trunc_ln91_reg_704_pp0_iter9_reg;
reg   [31:0] w_reg_709;
reg   [7:0] ap_phi_mux_val_1_phi_fu_496_p4;
wire   [7:0] v_fu_666_p3;
reg   [7:0] ap_phi_reg_pp0_iter10_val_1_reg_492;
wire   [7:0] ap_phi_reg_pp0_iter0_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter1_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter2_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter3_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter4_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter5_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter6_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter7_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter8_val_1_reg_492;
reg   [7:0] ap_phi_reg_pp0_iter9_val_1_reg_492;
wire   [63:0] zext_ln497_fu_636_p1;
wire  signed [63:0] p_cast_cast_fu_617_p1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [31:0] ic_fu_178;
wire   [31:0] add_ln497_fu_547_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_ic_1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    px_14_we0_local;
reg    px_14_ce0_local;
reg    px_13_we0_local;
reg    px_13_ce0_local;
reg    px_12_we0_local;
reg    px_12_ce0_local;
reg    px_11_we0_local;
reg    px_11_ce0_local;
reg    px_10_we0_local;
reg    px_10_ce0_local;
reg    px_9_we0_local;
reg    px_9_ce0_local;
reg    px_8_we0_local;
reg    px_8_ce0_local;
reg    px_7_we0_local;
reg    px_7_ce0_local;
reg    px_6_we0_local;
reg    px_6_ce0_local;
reg    px_5_we0_local;
reg    px_5_ce0_local;
reg    px_4_we0_local;
reg    px_4_ce0_local;
reg    px_3_we0_local;
reg    px_3_ce0_local;
reg    px_2_we0_local;
reg    px_2_ce0_local;
reg    px_1_we0_local;
reg    px_1_ce0_local;
reg    px_we0_local;
reg    px_ce0_local;
reg    px_15_we0_local;
reg    px_15_ce0_local;
wire  signed [31:0] sext_ln1272_1_cast_fu_523_p1;
wire   [31:0] zext_ln1275_cast_fu_519_p1;
wire   [31:0] add_ln503_fu_567_p2;
wire   [31:0] flat_fu_573_p2;
wire   [29:0] tmp_7_fu_579_p4;
wire   [31:0] and_ln1_fu_589_p3;
wire   [63:0] zext_ln504_fu_597_p1;
wire   [63:0] add_ln504_fu_601_p2;
wire   [61:0] p_cast_fu_607_p4;
wire   [4:0] shl_ln7_fu_655_p3;
wire   [31:0] v_fu_666_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_391;
wire   [7:0] v_fu_666_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ic_fu_178 = 32'd0;
#0 ap_done_reg = 1'b0;
end

conv_engine_partselect_8ns_32ns_32ns_8_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 32 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_32ns_32ns_8_1_1_U216(
    .din(w_reg_709),
    .sel(v_fu_666_p2),
    .dout(v_fu_666_p3)
);

conv_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_391)) begin
        if (((icmp_ln497_fu_541_p2 == 1'd0) & (1'd0 == and_ln365_3_fu_527_p2))) begin
            ap_phi_reg_pp0_iter1_val_1_reg_492 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_val_1_reg_492 <= ap_phi_reg_pp0_iter0_val_1_reg_492;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln497_fu_541_p2 == 1'd0))) begin
            ic_fu_178 <= add_ln497_fu_547_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_178 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RD_BUS_addr_reg_698 <= p_cast_cast_fu_617_p1;
        and_ln365_3_reg_681 <= and_ln365_3_fu_527_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln497_reg_685 <= icmp_ln497_fu_541_p2;
        icmp_ln497_reg_685_pp0_iter1_reg <= icmp_ln497_reg_685;
        lshr_ln1_reg_693 <= {{ap_sig_allocacmp_ic_1[6:4]}};
        lshr_ln1_reg_693_pp0_iter1_reg <= lshr_ln1_reg_693;
        trunc_ln497_reg_689 <= trunc_ln497_fu_553_p1;
        trunc_ln497_reg_689_pp0_iter1_reg <= trunc_ln497_reg_689;
        trunc_ln91_reg_704 <= trunc_ln91_fu_627_p1;
        trunc_ln91_reg_704_pp0_iter1_reg <= trunc_ln91_reg_704;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln497_reg_685_pp0_iter2_reg <= icmp_ln497_reg_685_pp0_iter1_reg;
        icmp_ln497_reg_685_pp0_iter3_reg <= icmp_ln497_reg_685_pp0_iter2_reg;
        icmp_ln497_reg_685_pp0_iter4_reg <= icmp_ln497_reg_685_pp0_iter3_reg;
        icmp_ln497_reg_685_pp0_iter5_reg <= icmp_ln497_reg_685_pp0_iter4_reg;
        icmp_ln497_reg_685_pp0_iter6_reg <= icmp_ln497_reg_685_pp0_iter5_reg;
        icmp_ln497_reg_685_pp0_iter7_reg <= icmp_ln497_reg_685_pp0_iter6_reg;
        icmp_ln497_reg_685_pp0_iter8_reg <= icmp_ln497_reg_685_pp0_iter7_reg;
        icmp_ln497_reg_685_pp0_iter9_reg <= icmp_ln497_reg_685_pp0_iter8_reg;
        lshr_ln1_reg_693_pp0_iter2_reg <= lshr_ln1_reg_693_pp0_iter1_reg;
        lshr_ln1_reg_693_pp0_iter3_reg <= lshr_ln1_reg_693_pp0_iter2_reg;
        lshr_ln1_reg_693_pp0_iter4_reg <= lshr_ln1_reg_693_pp0_iter3_reg;
        lshr_ln1_reg_693_pp0_iter5_reg <= lshr_ln1_reg_693_pp0_iter4_reg;
        lshr_ln1_reg_693_pp0_iter6_reg <= lshr_ln1_reg_693_pp0_iter5_reg;
        lshr_ln1_reg_693_pp0_iter7_reg <= lshr_ln1_reg_693_pp0_iter6_reg;
        lshr_ln1_reg_693_pp0_iter8_reg <= lshr_ln1_reg_693_pp0_iter7_reg;
        lshr_ln1_reg_693_pp0_iter9_reg <= lshr_ln1_reg_693_pp0_iter8_reg;
        trunc_ln497_reg_689_pp0_iter2_reg <= trunc_ln497_reg_689_pp0_iter1_reg;
        trunc_ln497_reg_689_pp0_iter3_reg <= trunc_ln497_reg_689_pp0_iter2_reg;
        trunc_ln497_reg_689_pp0_iter4_reg <= trunc_ln497_reg_689_pp0_iter3_reg;
        trunc_ln497_reg_689_pp0_iter5_reg <= trunc_ln497_reg_689_pp0_iter4_reg;
        trunc_ln497_reg_689_pp0_iter6_reg <= trunc_ln497_reg_689_pp0_iter5_reg;
        trunc_ln497_reg_689_pp0_iter7_reg <= trunc_ln497_reg_689_pp0_iter6_reg;
        trunc_ln497_reg_689_pp0_iter8_reg <= trunc_ln497_reg_689_pp0_iter7_reg;
        trunc_ln497_reg_689_pp0_iter9_reg <= trunc_ln497_reg_689_pp0_iter8_reg;
        trunc_ln91_reg_704_pp0_iter2_reg <= trunc_ln91_reg_704_pp0_iter1_reg;
        trunc_ln91_reg_704_pp0_iter3_reg <= trunc_ln91_reg_704_pp0_iter2_reg;
        trunc_ln91_reg_704_pp0_iter4_reg <= trunc_ln91_reg_704_pp0_iter3_reg;
        trunc_ln91_reg_704_pp0_iter5_reg <= trunc_ln91_reg_704_pp0_iter4_reg;
        trunc_ln91_reg_704_pp0_iter6_reg <= trunc_ln91_reg_704_pp0_iter5_reg;
        trunc_ln91_reg_704_pp0_iter7_reg <= trunc_ln91_reg_704_pp0_iter6_reg;
        trunc_ln91_reg_704_pp0_iter8_reg <= trunc_ln91_reg_704_pp0_iter7_reg;
        trunc_ln91_reg_704_pp0_iter9_reg <= trunc_ln91_reg_704_pp0_iter8_reg;
        w_reg_709 <= m_axi_RD_BUS_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_val_1_reg_492 <= ap_phi_reg_pp0_iter9_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_val_1_reg_492 <= ap_phi_reg_pp0_iter1_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_val_1_reg_492 <= ap_phi_reg_pp0_iter2_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_val_1_reg_492 <= ap_phi_reg_pp0_iter3_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_val_1_reg_492 <= ap_phi_reg_pp0_iter4_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_val_1_reg_492 <= ap_phi_reg_pp0_iter5_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_val_1_reg_492 <= ap_phi_reg_pp0_iter6_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_val_1_reg_492 <= ap_phi_reg_pp0_iter7_val_1_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_val_1_reg_492 <= ap_phi_reg_pp0_iter8_val_1_reg_492;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_predicate_op57_readreq_state2 == 1'b1))) begin
        RD_BUS_blk_n_AR = m_axi_RD_BUS_0_ARREADY;
    end else begin
        RD_BUS_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (ap_predicate_op65_read_state10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        RD_BUS_blk_n_R = m_axi_RD_BUS_0_RVALID;
    end else begin
        RD_BUS_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln497_fu_541_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln497_reg_685_pp0_iter9_reg == 1'd0) & (1'd1 == and_ln365_3_reg_681))) begin
        ap_phi_mux_val_1_phi_fu_496_p4 = v_fu_666_p3;
    end else begin
        ap_phi_mux_val_1_phi_fu_496_p4 = ap_phi_reg_pp0_iter10_val_1_reg_492;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_ic_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_ic_1 = ic_fu_178;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_predicate_op57_readreq_state2 == 1'b1))) begin
        m_axi_RD_BUS_0_ARVALID = 1'b1;
    end else begin
        m_axi_RD_BUS_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (ap_predicate_op65_read_state10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_RD_BUS_0_RREADY = 1'b1;
    end else begin
        m_axi_RD_BUS_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_10_ce0_local = 1'b1;
    end else begin
        px_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_10_we0_local = 1'b1;
    end else begin
        px_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_11_ce0_local = 1'b1;
    end else begin
        px_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_11_we0_local = 1'b1;
    end else begin
        px_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_12_ce0_local = 1'b1;
    end else begin
        px_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_12_we0_local = 1'b1;
    end else begin
        px_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_13_ce0_local = 1'b1;
    end else begin
        px_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_13_we0_local = 1'b1;
    end else begin
        px_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_14_ce0_local = 1'b1;
    end else begin
        px_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_14_we0_local = 1'b1;
    end else begin
        px_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_15_ce0_local = 1'b1;
    end else begin
        px_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_15_we0_local = 1'b1;
    end else begin
        px_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_1_ce0_local = 1'b1;
    end else begin
        px_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_1_we0_local = 1'b1;
    end else begin
        px_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_2_ce0_local = 1'b1;
    end else begin
        px_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_2_we0_local = 1'b1;
    end else begin
        px_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_3_ce0_local = 1'b1;
    end else begin
        px_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_3_we0_local = 1'b1;
    end else begin
        px_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_4_ce0_local = 1'b1;
    end else begin
        px_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_4_we0_local = 1'b1;
    end else begin
        px_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_5_ce0_local = 1'b1;
    end else begin
        px_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_5_we0_local = 1'b1;
    end else begin
        px_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_6_ce0_local = 1'b1;
    end else begin
        px_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_6_we0_local = 1'b1;
    end else begin
        px_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_7_ce0_local = 1'b1;
    end else begin
        px_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_7_we0_local = 1'b1;
    end else begin
        px_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_8_ce0_local = 1'b1;
    end else begin
        px_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_8_we0_local = 1'b1;
    end else begin
        px_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_9_ce0_local = 1'b1;
    end else begin
        px_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_9_we0_local = 1'b1;
    end else begin
        px_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_ce0_local = 1'b1;
    end else begin
        px_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln497_reg_689_pp0_iter9_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        px_we0_local = 1'b1;
    end else begin
        px_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln497_fu_547_p2 = (ap_sig_allocacmp_ic_1 + 32'd1);

assign add_ln503_fu_567_p2 = (zext_ln1275_cast_fu_519_p1 + mul_ln471);

assign add_ln504_fu_601_p2 = (zext_ln504_fu_597_p1 + ifmap);

assign and_ln1_fu_589_p3 = {{tmp_7_fu_579_p4}, {2'd0}};

assign and_ln365_3_fu_527_p2 = (and_ln365_1 & and_ln365);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = ((m_axi_RD_BUS_0_RVALID == 1'b0) & (ap_predicate_op65_read_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_RD_BUS_0_ARREADY == 1'b0) & (ap_predicate_op57_readreq_state2 == 1'b1));
end

always @ (*) begin
    ap_condition_391 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_val_1_reg_492 = 'bx;

always @ (*) begin
    ap_predicate_op57_readreq_state2 = ((1'd1 == and_ln365_3_reg_681) & (icmp_ln497_reg_685 == 1'd0));
end

always @ (*) begin
    ap_predicate_op65_read_state10 = ((icmp_ln497_reg_685_pp0_iter8_reg == 1'd0) & (1'd1 == and_ln365_3_reg_681));
end

assign ap_ready = ap_ready_sig;

assign flat_fu_573_p2 = (add_ln503_fu_567_p2 + ap_sig_allocacmp_ic_1);

assign icmp_ln497_fu_541_p2 = ((ap_sig_allocacmp_ic_1 == sext_ln1272_1_cast_fu_523_p1) ? 1'b1 : 1'b0);

assign m_axi_RD_BUS_0_ARADDR = RD_BUS_addr_reg_698;

assign m_axi_RD_BUS_0_ARBURST = 2'd0;

assign m_axi_RD_BUS_0_ARCACHE = 4'd0;

assign m_axi_RD_BUS_0_ARID = 1'd0;

assign m_axi_RD_BUS_0_ARLEN = 64'd1;

assign m_axi_RD_BUS_0_ARLOCK = 2'd0;

assign m_axi_RD_BUS_0_ARPROT = 3'd0;

assign m_axi_RD_BUS_0_ARQOS = 4'd0;

assign m_axi_RD_BUS_0_ARREGION = 4'd0;

assign m_axi_RD_BUS_0_ARSIZE = 3'd0;

assign m_axi_RD_BUS_0_ARUSER = 1'd0;

assign m_axi_RD_BUS_0_AWADDR = 64'd0;

assign m_axi_RD_BUS_0_AWBURST = 2'd0;

assign m_axi_RD_BUS_0_AWCACHE = 4'd0;

assign m_axi_RD_BUS_0_AWID = 1'd0;

assign m_axi_RD_BUS_0_AWLEN = 32'd0;

assign m_axi_RD_BUS_0_AWLOCK = 2'd0;

assign m_axi_RD_BUS_0_AWPROT = 3'd0;

assign m_axi_RD_BUS_0_AWQOS = 4'd0;

assign m_axi_RD_BUS_0_AWREGION = 4'd0;

assign m_axi_RD_BUS_0_AWSIZE = 3'd0;

assign m_axi_RD_BUS_0_AWUSER = 1'd0;

assign m_axi_RD_BUS_0_AWVALID = 1'b0;

assign m_axi_RD_BUS_0_BREADY = 1'b0;

assign m_axi_RD_BUS_0_WDATA = 32'd0;

assign m_axi_RD_BUS_0_WID = 1'd0;

assign m_axi_RD_BUS_0_WLAST = 1'b0;

assign m_axi_RD_BUS_0_WSTRB = 4'd0;

assign m_axi_RD_BUS_0_WUSER = 1'd0;

assign m_axi_RD_BUS_0_WVALID = 1'b0;

assign p_cast_cast_fu_617_p1 = $signed(p_cast_fu_607_p4);

assign p_cast_fu_607_p4 = {{add_ln504_fu_601_p2[63:2]}};

assign px_10_address0 = zext_ln497_fu_636_p1;

assign px_10_ce0 = px_10_ce0_local;

assign px_10_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_10_we0 = px_10_we0_local;

assign px_11_address0 = zext_ln497_fu_636_p1;

assign px_11_ce0 = px_11_ce0_local;

assign px_11_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_11_we0 = px_11_we0_local;

assign px_12_address0 = zext_ln497_fu_636_p1;

assign px_12_ce0 = px_12_ce0_local;

assign px_12_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_12_we0 = px_12_we0_local;

assign px_13_address0 = zext_ln497_fu_636_p1;

assign px_13_ce0 = px_13_ce0_local;

assign px_13_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_13_we0 = px_13_we0_local;

assign px_14_address0 = zext_ln497_fu_636_p1;

assign px_14_ce0 = px_14_ce0_local;

assign px_14_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_14_we0 = px_14_we0_local;

assign px_15_address0 = zext_ln497_fu_636_p1;

assign px_15_ce0 = px_15_ce0_local;

assign px_15_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_15_we0 = px_15_we0_local;

assign px_1_address0 = zext_ln497_fu_636_p1;

assign px_1_ce0 = px_1_ce0_local;

assign px_1_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_1_we0 = px_1_we0_local;

assign px_2_address0 = zext_ln497_fu_636_p1;

assign px_2_ce0 = px_2_ce0_local;

assign px_2_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_2_we0 = px_2_we0_local;

assign px_3_address0 = zext_ln497_fu_636_p1;

assign px_3_ce0 = px_3_ce0_local;

assign px_3_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_3_we0 = px_3_we0_local;

assign px_4_address0 = zext_ln497_fu_636_p1;

assign px_4_ce0 = px_4_ce0_local;

assign px_4_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_4_we0 = px_4_we0_local;

assign px_5_address0 = zext_ln497_fu_636_p1;

assign px_5_ce0 = px_5_ce0_local;

assign px_5_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_5_we0 = px_5_we0_local;

assign px_6_address0 = zext_ln497_fu_636_p1;

assign px_6_ce0 = px_6_ce0_local;

assign px_6_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_6_we0 = px_6_we0_local;

assign px_7_address0 = zext_ln497_fu_636_p1;

assign px_7_ce0 = px_7_ce0_local;

assign px_7_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_7_we0 = px_7_we0_local;

assign px_8_address0 = zext_ln497_fu_636_p1;

assign px_8_ce0 = px_8_ce0_local;

assign px_8_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_8_we0 = px_8_we0_local;

assign px_9_address0 = zext_ln497_fu_636_p1;

assign px_9_ce0 = px_9_ce0_local;

assign px_9_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_9_we0 = px_9_we0_local;

assign px_address0 = zext_ln497_fu_636_p1;

assign px_ce0 = px_ce0_local;

assign px_d0 = ap_phi_mux_val_1_phi_fu_496_p4;

assign px_we0 = px_we0_local;

assign sext_ln1272_1_cast_fu_523_p1 = $signed(sext_ln1272_1);

assign shl_ln7_fu_655_p3 = {{trunc_ln91_reg_704_pp0_iter9_reg}, {3'd0}};

assign tmp_7_fu_579_p4 = {{flat_fu_573_p2[31:2]}};

assign trunc_ln497_fu_553_p1 = ap_sig_allocacmp_ic_1[3:0];

assign trunc_ln91_fu_627_p1 = flat_fu_573_p2[1:0];

assign v_fu_666_p2 = shl_ln7_fu_655_p3;

assign zext_ln1275_cast_fu_519_p1 = zext_ln1275;

assign zext_ln497_fu_636_p1 = lshr_ln1_reg_693_pp0_iter9_reg;

assign zext_ln504_fu_597_p1 = and_ln1_fu_589_p3;

endmodule //conv_engine_conv_engine_Pipeline_READ_CH_ELEMS
