// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv_engine_conv_engine_Pipeline_ACCUM_WR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_WR_BUS_0_AWVALID,
        m_axi_WR_BUS_0_AWREADY,
        m_axi_WR_BUS_0_AWADDR,
        m_axi_WR_BUS_0_AWID,
        m_axi_WR_BUS_0_AWLEN,
        m_axi_WR_BUS_0_AWSIZE,
        m_axi_WR_BUS_0_AWBURST,
        m_axi_WR_BUS_0_AWLOCK,
        m_axi_WR_BUS_0_AWCACHE,
        m_axi_WR_BUS_0_AWPROT,
        m_axi_WR_BUS_0_AWQOS,
        m_axi_WR_BUS_0_AWREGION,
        m_axi_WR_BUS_0_AWUSER,
        m_axi_WR_BUS_0_WVALID,
        m_axi_WR_BUS_0_WREADY,
        m_axi_WR_BUS_0_WDATA,
        m_axi_WR_BUS_0_WSTRB,
        m_axi_WR_BUS_0_WLAST,
        m_axi_WR_BUS_0_WID,
        m_axi_WR_BUS_0_WUSER,
        m_axi_WR_BUS_0_ARVALID,
        m_axi_WR_BUS_0_ARREADY,
        m_axi_WR_BUS_0_ARADDR,
        m_axi_WR_BUS_0_ARID,
        m_axi_WR_BUS_0_ARLEN,
        m_axi_WR_BUS_0_ARSIZE,
        m_axi_WR_BUS_0_ARBURST,
        m_axi_WR_BUS_0_ARLOCK,
        m_axi_WR_BUS_0_ARCACHE,
        m_axi_WR_BUS_0_ARPROT,
        m_axi_WR_BUS_0_ARQOS,
        m_axi_WR_BUS_0_ARREGION,
        m_axi_WR_BUS_0_ARUSER,
        m_axi_WR_BUS_0_RVALID,
        m_axi_WR_BUS_0_RREADY,
        m_axi_WR_BUS_0_RDATA,
        m_axi_WR_BUS_0_RLAST,
        m_axi_WR_BUS_0_RID,
        m_axi_WR_BUS_0_RFIFONUM,
        m_axi_WR_BUS_0_RUSER,
        m_axi_WR_BUS_0_RRESP,
        m_axi_WR_BUS_0_BVALID,
        m_axi_WR_BUS_0_BREADY,
        m_axi_WR_BUS_0_BRESP,
        m_axi_WR_BUS_0_BID,
        m_axi_WR_BUS_0_BUSER,
        sext_ln1254_8,
        sext_ln1050,
        acc_fin_load_2,
        acc_fin_1_load_2,
        acc_fin_2_load_2,
        acc_fin_3_load_2,
        acc_fin_4_load_2,
        acc_fin_5_load_2,
        acc_fin_6_load_2,
        acc_fin_7_load_2,
        acc_fin_8_load_2,
        acc_fin_9_load_2,
        acc_fin_10_load_2,
        acc_fin_11_load_2,
        acc_fin_12_load_2,
        acc_fin_13_load_2,
        acc_fin_14_load_2,
        acc_fin_15_load_2,
        acc_fin_16_load_2,
        acc_fin_17_load_2,
        acc_fin_18_load_2,
        acc_fin_19_load_2,
        acc_fin_20_load_2,
        acc_fin_21_load_2,
        acc_fin_22_load_2,
        acc_fin_23_load_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_WR_BUS_0_AWVALID;
input   m_axi_WR_BUS_0_AWREADY;
output  [63:0] m_axi_WR_BUS_0_AWADDR;
output  [0:0] m_axi_WR_BUS_0_AWID;
output  [31:0] m_axi_WR_BUS_0_AWLEN;
output  [2:0] m_axi_WR_BUS_0_AWSIZE;
output  [1:0] m_axi_WR_BUS_0_AWBURST;
output  [1:0] m_axi_WR_BUS_0_AWLOCK;
output  [3:0] m_axi_WR_BUS_0_AWCACHE;
output  [2:0] m_axi_WR_BUS_0_AWPROT;
output  [3:0] m_axi_WR_BUS_0_AWQOS;
output  [3:0] m_axi_WR_BUS_0_AWREGION;
output  [0:0] m_axi_WR_BUS_0_AWUSER;
output   m_axi_WR_BUS_0_WVALID;
input   m_axi_WR_BUS_0_WREADY;
output  [31:0] m_axi_WR_BUS_0_WDATA;
output  [3:0] m_axi_WR_BUS_0_WSTRB;
output   m_axi_WR_BUS_0_WLAST;
output  [0:0] m_axi_WR_BUS_0_WID;
output  [0:0] m_axi_WR_BUS_0_WUSER;
output   m_axi_WR_BUS_0_ARVALID;
input   m_axi_WR_BUS_0_ARREADY;
output  [63:0] m_axi_WR_BUS_0_ARADDR;
output  [0:0] m_axi_WR_BUS_0_ARID;
output  [31:0] m_axi_WR_BUS_0_ARLEN;
output  [2:0] m_axi_WR_BUS_0_ARSIZE;
output  [1:0] m_axi_WR_BUS_0_ARBURST;
output  [1:0] m_axi_WR_BUS_0_ARLOCK;
output  [3:0] m_axi_WR_BUS_0_ARCACHE;
output  [2:0] m_axi_WR_BUS_0_ARPROT;
output  [3:0] m_axi_WR_BUS_0_ARQOS;
output  [3:0] m_axi_WR_BUS_0_ARREGION;
output  [0:0] m_axi_WR_BUS_0_ARUSER;
input   m_axi_WR_BUS_0_RVALID;
output   m_axi_WR_BUS_0_RREADY;
input  [31:0] m_axi_WR_BUS_0_RDATA;
input   m_axi_WR_BUS_0_RLAST;
input  [0:0] m_axi_WR_BUS_0_RID;
input  [8:0] m_axi_WR_BUS_0_RFIFONUM;
input  [0:0] m_axi_WR_BUS_0_RUSER;
input  [1:0] m_axi_WR_BUS_0_RRESP;
input   m_axi_WR_BUS_0_BVALID;
output   m_axi_WR_BUS_0_BREADY;
input  [1:0] m_axi_WR_BUS_0_BRESP;
input  [0:0] m_axi_WR_BUS_0_BID;
input  [0:0] m_axi_WR_BUS_0_BUSER;
input  [18:0] sext_ln1254_8;
input  [61:0] sext_ln1050;
input  [31:0] acc_fin_load_2;
input  [31:0] acc_fin_1_load_2;
input  [31:0] acc_fin_2_load_2;
input  [31:0] acc_fin_3_load_2;
input  [31:0] acc_fin_4_load_2;
input  [31:0] acc_fin_5_load_2;
input  [31:0] acc_fin_6_load_2;
input  [31:0] acc_fin_7_load_2;
input  [31:0] acc_fin_8_load_2;
input  [31:0] acc_fin_9_load_2;
input  [31:0] acc_fin_10_load_2;
input  [31:0] acc_fin_11_load_2;
input  [31:0] acc_fin_12_load_2;
input  [31:0] acc_fin_13_load_2;
input  [31:0] acc_fin_14_load_2;
input  [31:0] acc_fin_15_load_2;
input  [31:0] acc_fin_16_load_2;
input  [31:0] acc_fin_17_load_2;
input  [31:0] acc_fin_18_load_2;
input  [31:0] acc_fin_19_load_2;
input  [31:0] acc_fin_20_load_2;
input  [31:0] acc_fin_21_load_2;
input  [31:0] acc_fin_22_load_2;
input  [31:0] acc_fin_23_load_2;

reg ap_idle;
reg m_axi_WR_BUS_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1050_fu_336_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    WR_BUS_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [31:0] tmp_s_fu_352_p51;
reg   [31:0] tmp_s_reg_482;
reg    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [31:0] lane_fu_152;
wire   [31:0] add_ln1050_fu_342_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_lane_2;
wire    ap_block_pp0_stage0;
wire  signed [31:0] sext_ln1254_8_cast_fu_324_p1;
wire   [31:0] tmp_s_fu_352_p49;
wire   [4:0] tmp_s_fu_352_p50;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_s_fu_352_p1;
wire   [4:0] tmp_s_fu_352_p3;
wire   [4:0] tmp_s_fu_352_p5;
wire   [4:0] tmp_s_fu_352_p7;
wire   [4:0] tmp_s_fu_352_p9;
wire   [4:0] tmp_s_fu_352_p11;
wire   [4:0] tmp_s_fu_352_p13;
wire   [4:0] tmp_s_fu_352_p15;
wire   [4:0] tmp_s_fu_352_p17;
wire   [4:0] tmp_s_fu_352_p19;
wire   [4:0] tmp_s_fu_352_p21;
wire   [4:0] tmp_s_fu_352_p23;
wire   [4:0] tmp_s_fu_352_p25;
wire   [4:0] tmp_s_fu_352_p27;
wire   [4:0] tmp_s_fu_352_p29;
wire   [4:0] tmp_s_fu_352_p31;
wire  signed [4:0] tmp_s_fu_352_p33;
wire  signed [4:0] tmp_s_fu_352_p35;
wire  signed [4:0] tmp_s_fu_352_p37;
wire  signed [4:0] tmp_s_fu_352_p39;
wire  signed [4:0] tmp_s_fu_352_p41;
wire  signed [4:0] tmp_s_fu_352_p43;
wire  signed [4:0] tmp_s_fu_352_p45;
wire  signed [4:0] tmp_s_fu_352_p47;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 lane_fu_152 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) conv_engine_sparsemux_49_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_49_5_32_1_1_U940(
    .din0(acc_fin_load_2),
    .din1(acc_fin_1_load_2),
    .din2(acc_fin_2_load_2),
    .din3(acc_fin_3_load_2),
    .din4(acc_fin_4_load_2),
    .din5(acc_fin_5_load_2),
    .din6(acc_fin_6_load_2),
    .din7(acc_fin_7_load_2),
    .din8(acc_fin_8_load_2),
    .din9(acc_fin_9_load_2),
    .din10(acc_fin_10_load_2),
    .din11(acc_fin_11_load_2),
    .din12(acc_fin_12_load_2),
    .din13(acc_fin_13_load_2),
    .din14(acc_fin_14_load_2),
    .din15(acc_fin_15_load_2),
    .din16(acc_fin_16_load_2),
    .din17(acc_fin_17_load_2),
    .din18(acc_fin_18_load_2),
    .din19(acc_fin_19_load_2),
    .din20(acc_fin_20_load_2),
    .din21(acc_fin_21_load_2),
    .din22(acc_fin_22_load_2),
    .din23(acc_fin_23_load_2),
    .def(tmp_s_fu_352_p49),
    .sel(tmp_s_fu_352_p50),
    .dout(tmp_s_fu_352_p51)
);

conv_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1050_fu_336_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            lane_fu_152 <= add_ln1050_fu_342_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            lane_fu_152 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_s_reg_482 <= tmp_s_fu_352_p51;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        WR_BUS_blk_n_W = m_axi_WR_BUS_0_WREADY;
    end else begin
        WR_BUS_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1050_fu_336_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_lane_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_lane_2 = lane_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_WR_BUS_0_WVALID = 1'b1;
    end else begin
        m_axi_WR_BUS_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1050_fu_342_p2 = (ap_sig_allocacmp_lane_2 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_WR_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_WR_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_WR_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln1050_fu_336_p2 = ((ap_sig_allocacmp_lane_2 == sext_ln1254_8_cast_fu_324_p1) ? 1'b1 : 1'b0);

assign m_axi_WR_BUS_0_ARADDR = 64'd0;

assign m_axi_WR_BUS_0_ARBURST = 2'd0;

assign m_axi_WR_BUS_0_ARCACHE = 4'd0;

assign m_axi_WR_BUS_0_ARID = 1'd0;

assign m_axi_WR_BUS_0_ARLEN = 32'd0;

assign m_axi_WR_BUS_0_ARLOCK = 2'd0;

assign m_axi_WR_BUS_0_ARPROT = 3'd0;

assign m_axi_WR_BUS_0_ARQOS = 4'd0;

assign m_axi_WR_BUS_0_ARREGION = 4'd0;

assign m_axi_WR_BUS_0_ARSIZE = 3'd0;

assign m_axi_WR_BUS_0_ARUSER = 1'd0;

assign m_axi_WR_BUS_0_ARVALID = 1'b0;

assign m_axi_WR_BUS_0_AWADDR = 64'd0;

assign m_axi_WR_BUS_0_AWBURST = 2'd0;

assign m_axi_WR_BUS_0_AWCACHE = 4'd0;

assign m_axi_WR_BUS_0_AWID = 1'd0;

assign m_axi_WR_BUS_0_AWLEN = 32'd0;

assign m_axi_WR_BUS_0_AWLOCK = 2'd0;

assign m_axi_WR_BUS_0_AWPROT = 3'd0;

assign m_axi_WR_BUS_0_AWQOS = 4'd0;

assign m_axi_WR_BUS_0_AWREGION = 4'd0;

assign m_axi_WR_BUS_0_AWSIZE = 3'd0;

assign m_axi_WR_BUS_0_AWUSER = 1'd0;

assign m_axi_WR_BUS_0_AWVALID = 1'b0;

assign m_axi_WR_BUS_0_BREADY = 1'b0;

assign m_axi_WR_BUS_0_RREADY = 1'b0;

assign m_axi_WR_BUS_0_WDATA = tmp_s_reg_482;

assign m_axi_WR_BUS_0_WID = 1'd0;

assign m_axi_WR_BUS_0_WLAST = 1'b0;

assign m_axi_WR_BUS_0_WSTRB = 4'd15;

assign m_axi_WR_BUS_0_WUSER = 1'd0;

assign sext_ln1254_8_cast_fu_324_p1 = $signed(sext_ln1254_8);

assign tmp_s_fu_352_p49 = 'bx;

assign tmp_s_fu_352_p50 = ap_sig_allocacmp_lane_2[4:0];

endmodule //conv_engine_conv_engine_Pipeline_ACCUM_WR
