// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv_engine_conv_engine_Pipeline_WINDOW_ROW_SHIFT_WINDOW_COL_SHIFT_WINDOW_ROW_SHIFT_STEP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln231_1,
        ic_count,
        mul_ln231,
        lshr_ln,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_q1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_address0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_d0,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_address1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1,
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_q1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_address0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_d0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_address1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_q1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_address0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_d0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_address1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_q1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_address0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_d0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_address1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_q1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_address0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_d0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_address1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_q1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_address0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_d0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_address1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_q1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_address0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_d0,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_address1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1,
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [42:0] mul_ln231_1;
input  [7:0] ic_count;
input  [34:0] mul_ln231;
input  [3:0] lshr_ln;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_q1;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_address0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0;
output  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_d0;
output  [6:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_address1;
output   scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1;
input  [7:0] scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_q1;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_address0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0;
output  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_d0;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_address1;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1;
input  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_q1;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_address0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0;
output  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_d0;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_address1;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1;
input  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_q1;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_address0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0;
output  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_d0;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_address1;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1;
input  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_q1;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_address0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0;
output  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_d0;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_address1;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1;
input  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_q1;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_address0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0;
output  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_d0;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_address1;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1;
input  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_q1;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_address0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0;
output  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_d0;
output  [6:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_address1;
output   p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1;
input  [7:0] p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln597_fu_617_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [35:0] mul_ln231_cast_fu_582_p1;
reg   [35:0] mul_ln231_cast_reg_1226;
wire   [0:0] icmp_ln600_fu_640_p2;
reg   [0:0] icmp_ln600_reg_1235;
wire   [0:0] select_ln597_2_fu_655_p3;
reg   [0:0] select_ln597_2_reg_1241;
wire   [6:0] add_ln611_fu_711_p2;
reg   [6:0] add_ln611_reg_1247;
wire   [0:0] icmp_ln610_fu_733_p2;
reg   [0:0] icmp_ln610_reg_1253;
reg   [0:0] icmp_ln610_reg_1253_pp0_iter2_reg;
wire   [0:0] icmp_ln610_1_fu_750_p2;
reg   [0:0] icmp_ln610_1_reg_1257;
reg   [0:0] icmp_ln610_1_reg_1257_pp0_iter2_reg;
wire   [0:0] icmp_ln610_2_fu_767_p2;
reg   [0:0] icmp_ln610_2_reg_1261;
reg   [0:0] icmp_ln610_2_reg_1261_pp0_iter2_reg;
wire   [0:0] icmp_ln610_3_fu_784_p2;
reg   [0:0] icmp_ln610_3_reg_1265;
reg   [0:0] icmp_ln610_3_reg_1265_pp0_iter2_reg;
wire   [0:0] icmp_ln610_4_fu_801_p2;
reg   [0:0] icmp_ln610_4_reg_1269;
reg   [0:0] icmp_ln610_4_reg_1269_pp0_iter2_reg;
wire   [0:0] icmp_ln610_5_fu_818_p2;
reg   [0:0] icmp_ln610_5_reg_1273;
reg   [0:0] icmp_ln610_5_reg_1273_pp0_iter2_reg;
wire   [0:0] icmp_ln610_6_fu_835_p2;
reg   [0:0] icmp_ln610_6_reg_1277;
reg   [0:0] icmp_ln610_6_reg_1277_pp0_iter2_reg;
wire   [0:0] icmp_ln610_7_fu_852_p2;
reg   [0:0] icmp_ln610_7_reg_1281;
reg   [0:0] icmp_ln610_7_reg_1281_pp0_iter2_reg;
wire   [0:0] icmp_ln610_8_fu_869_p2;
reg   [0:0] icmp_ln610_8_reg_1285;
reg   [0:0] icmp_ln610_8_reg_1285_pp0_iter2_reg;
wire   [0:0] icmp_ln610_9_fu_886_p2;
reg   [0:0] icmp_ln610_9_reg_1289;
reg   [0:0] icmp_ln610_9_reg_1289_pp0_iter2_reg;
wire   [0:0] icmp_ln610_10_fu_903_p2;
reg   [0:0] icmp_ln610_10_reg_1293;
reg   [0:0] icmp_ln610_10_reg_1293_pp0_iter2_reg;
wire   [0:0] icmp_ln610_11_fu_920_p2;
reg   [0:0] icmp_ln610_11_reg_1297;
reg   [0:0] icmp_ln610_11_reg_1297_pp0_iter2_reg;
wire   [0:0] icmp_ln610_12_fu_937_p2;
reg   [0:0] icmp_ln610_12_reg_1301;
reg   [0:0] icmp_ln610_12_reg_1301_pp0_iter2_reg;
wire   [0:0] icmp_ln610_13_fu_954_p2;
reg   [0:0] icmp_ln610_13_reg_1305;
reg   [0:0] icmp_ln610_13_reg_1305_pp0_iter2_reg;
wire   [0:0] icmp_ln610_14_fu_971_p2;
reg   [0:0] icmp_ln610_14_reg_1309;
reg   [0:0] icmp_ln610_14_reg_1309_pp0_iter2_reg;
wire   [0:0] icmp_ln610_15_fu_988_p2;
reg   [0:0] icmp_ln610_15_reg_1313;
reg   [0:0] icmp_ln610_15_reg_1313_pp0_iter2_reg;
wire   [6:0] add_ln611_2_fu_1130_p2;
reg   [6:0] add_ln611_2_reg_1322;
wire   [63:0] zext_ln611_2_fu_1110_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln611_3_fu_1141_p1;
reg   [3:0] ic_step_fu_122;
wire   [3:0] add_ln603_fu_993_p2;
wire    ap_loop_init;
reg   [31:0] kx_fu_126;
wire   [31:0] select_ln600_fu_1083_p3;
reg   [35:0] indvar_flatten23_fu_130;
wire   [35:0] select_ln600_1_fu_1005_p3;
reg   [7:0] ky_fu_134;
wire   [7:0] select_ln597_3_fu_663_p3;
reg   [42:0] indvar_flatten38_fu_138;
wire   [42:0] add_ln597_1_fu_622_p2;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0_local;
reg    scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0_local;
reg    p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0_local;
wire   [0:0] icmp_ln603_fu_645_p2;
wire   [0:0] icmp_ln603_1_fu_650_p2;
wire   [7:0] add_ln597_fu_634_p2;
wire   [0:0] empty_fu_671_p2;
wire   [3:0] ic_step_1_mid2_fu_677_p3;
wire   [5:0] p_shl_fu_693_p3;
wire   [5:0] zext_ln611_fu_689_p1;
wire   [5:0] sub_ln611_fu_701_p2;
wire   [6:0] zext_ln611_1_fu_707_p1;
wire   [6:0] trunc_ln600_1_fu_685_p1;
wire   [2:0] empty_74_fu_717_p1;
wire   [6:0] tmp_s_fu_721_p3;
wire   [7:0] zext_ln610_fu_729_p1;
wire   [6:0] or_ln1_fu_738_p3;
wire   [7:0] zext_ln610_1_fu_746_p1;
wire   [6:0] or_ln609_1_fu_755_p3;
wire   [7:0] zext_ln610_2_fu_763_p1;
wire   [6:0] or_ln609_2_fu_772_p3;
wire   [7:0] zext_ln610_3_fu_780_p1;
wire   [6:0] or_ln609_3_fu_789_p3;
wire   [7:0] zext_ln610_4_fu_797_p1;
wire   [6:0] or_ln609_4_fu_806_p3;
wire   [7:0] zext_ln610_5_fu_814_p1;
wire   [6:0] or_ln609_5_fu_823_p3;
wire   [7:0] zext_ln610_6_fu_831_p1;
wire   [6:0] or_ln609_6_fu_840_p3;
wire   [7:0] zext_ln610_7_fu_848_p1;
wire   [6:0] or_ln609_7_fu_857_p3;
wire   [7:0] zext_ln610_8_fu_865_p1;
wire   [6:0] or_ln609_8_fu_874_p3;
wire   [7:0] zext_ln610_9_fu_882_p1;
wire   [6:0] or_ln609_9_fu_891_p3;
wire   [7:0] zext_ln610_10_fu_899_p1;
wire   [6:0] or_ln609_s_fu_908_p3;
wire   [7:0] zext_ln610_11_fu_916_p1;
wire   [6:0] or_ln609_10_fu_925_p3;
wire   [7:0] zext_ln610_12_fu_933_p1;
wire   [6:0] or_ln609_11_fu_942_p3;
wire   [7:0] zext_ln610_13_fu_950_p1;
wire   [6:0] or_ln609_12_fu_959_p3;
wire   [7:0] zext_ln610_14_fu_967_p1;
wire   [6:0] or_ln609_13_fu_976_p3;
wire   [7:0] zext_ln610_15_fu_984_p1;
wire   [35:0] add_ln600_fu_999_p2;
wire   [31:0] select_ln597_fu_1040_p3;
wire   [6:0] trunc_ln597_fu_1036_p1;
wire   [6:0] indvars_iv_next1126235_fu_1051_p2;
wire   [6:0] trunc_ln600_fu_1047_p1;
wire   [6:0] indvars_iv_next1126_mid1_fu_1070_p2;
wire   [6:0] select_ln597_1_fu_1057_p3;
wire   [31:0] indvars_iv_next1126_dup_fu_1064_p2;
wire   [6:0] shl_ln611_fu_1094_p2;
wire   [6:0] sub_ln611_1_fu_1099_p2;
wire   [6:0] indvars_iv_next1126_mid2_fu_1076_p3;
wire   [6:0] add_ln611_1_fu_1104_p2;
wire   [6:0] trunc_ln603_fu_1090_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ic_step_fu_122 = 4'd0;
#0 kx_fu_126 = 32'd0;
#0 indvar_flatten23_fu_130 = 36'd0;
#0 ky_fu_134 = 8'd0;
#0 indvar_flatten38_fu_138 = 43'd0;
#0 ap_done_reg = 1'b0;
end

conv_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_step_fu_122 <= 4'd0;
        end else if (((icmp_ln597_fu_617_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ic_step_fu_122 <= add_ln603_fu_993_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten23_fu_130 <= 36'd0;
        end else if (((icmp_ln597_fu_617_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten23_fu_130 <= select_ln600_1_fu_1005_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten38_fu_138 <= 43'd0;
        end else if (((icmp_ln597_fu_617_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten38_fu_138 <= add_ln597_1_fu_622_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kx_fu_126 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            kx_fu_126 <= select_ln600_fu_1083_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ky_fu_134 <= 8'd0;
        end else if (((icmp_ln597_fu_617_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ky_fu_134 <= select_ln597_3_fu_663_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln611_2_reg_1322 <= add_ln611_2_fu_1130_p2;
        icmp_ln610_10_reg_1293_pp0_iter2_reg <= icmp_ln610_10_reg_1293;
        icmp_ln610_11_reg_1297_pp0_iter2_reg <= icmp_ln610_11_reg_1297;
        icmp_ln610_12_reg_1301_pp0_iter2_reg <= icmp_ln610_12_reg_1301;
        icmp_ln610_13_reg_1305_pp0_iter2_reg <= icmp_ln610_13_reg_1305;
        icmp_ln610_14_reg_1309_pp0_iter2_reg <= icmp_ln610_14_reg_1309;
        icmp_ln610_15_reg_1313_pp0_iter2_reg <= icmp_ln610_15_reg_1313;
        icmp_ln610_1_reg_1257_pp0_iter2_reg <= icmp_ln610_1_reg_1257;
        icmp_ln610_2_reg_1261_pp0_iter2_reg <= icmp_ln610_2_reg_1261;
        icmp_ln610_3_reg_1265_pp0_iter2_reg <= icmp_ln610_3_reg_1265;
        icmp_ln610_4_reg_1269_pp0_iter2_reg <= icmp_ln610_4_reg_1269;
        icmp_ln610_5_reg_1273_pp0_iter2_reg <= icmp_ln610_5_reg_1273;
        icmp_ln610_6_reg_1277_pp0_iter2_reg <= icmp_ln610_6_reg_1277;
        icmp_ln610_7_reg_1281_pp0_iter2_reg <= icmp_ln610_7_reg_1281;
        icmp_ln610_8_reg_1285_pp0_iter2_reg <= icmp_ln610_8_reg_1285;
        icmp_ln610_9_reg_1289_pp0_iter2_reg <= icmp_ln610_9_reg_1289;
        icmp_ln610_reg_1253_pp0_iter2_reg <= icmp_ln610_reg_1253;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln611_reg_1247 <= add_ln611_fu_711_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln600_reg_1235 <= icmp_ln600_fu_640_p2;
        icmp_ln610_10_reg_1293 <= icmp_ln610_10_fu_903_p2;
        icmp_ln610_11_reg_1297 <= icmp_ln610_11_fu_920_p2;
        icmp_ln610_12_reg_1301 <= icmp_ln610_12_fu_937_p2;
        icmp_ln610_13_reg_1305 <= icmp_ln610_13_fu_954_p2;
        icmp_ln610_14_reg_1309 <= icmp_ln610_14_fu_971_p2;
        icmp_ln610_15_reg_1313 <= icmp_ln610_15_fu_988_p2;
        icmp_ln610_1_reg_1257 <= icmp_ln610_1_fu_750_p2;
        icmp_ln610_2_reg_1261 <= icmp_ln610_2_fu_767_p2;
        icmp_ln610_3_reg_1265 <= icmp_ln610_3_fu_784_p2;
        icmp_ln610_4_reg_1269 <= icmp_ln610_4_fu_801_p2;
        icmp_ln610_5_reg_1273 <= icmp_ln610_5_fu_818_p2;
        icmp_ln610_6_reg_1277 <= icmp_ln610_6_fu_835_p2;
        icmp_ln610_7_reg_1281 <= icmp_ln610_7_fu_852_p2;
        icmp_ln610_8_reg_1285 <= icmp_ln610_8_fu_869_p2;
        icmp_ln610_9_reg_1289 <= icmp_ln610_9_fu_886_p2;
        icmp_ln610_reg_1253 <= icmp_ln610_fu_733_p2;
        mul_ln231_cast_reg_1226[34 : 0] <= mul_ln231_cast_fu_582_p1[34 : 0];
        select_ln597_2_reg_1241 <= select_ln597_2_fu_655_p3;
    end
end

always @ (*) begin
    if (((icmp_ln597_fu_617_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln610_15_reg_1313_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln610_14_reg_1309_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln610_13_reg_1305_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_12_reg_1301_pp0_iter2_reg == 1'd1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_11_reg_1297_pp0_iter2_reg == 1'd1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_10_reg_1293_pp0_iter2_reg == 1'd1))) begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0_local = 1'b1;
    end else begin
        p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_8_reg_1285_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_7_reg_1281_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_6_reg_1277_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_5_reg_1273_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_4_reg_1269_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_3_reg_1265_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_2_reg_1261_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_1_reg_1257_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_reg_1253_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln610_9_reg_1289_pp0_iter2_reg == 1'd1))) begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0_local = 1'b1;
    end else begin
        scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln597_1_fu_622_p2 = (indvar_flatten38_fu_138 + 43'd1);

assign add_ln597_fu_634_p2 = (ky_fu_134 + 8'd1);

assign add_ln600_fu_999_p2 = (indvar_flatten23_fu_130 + 36'd1);

assign add_ln603_fu_993_p2 = (ic_step_1_mid2_fu_677_p3 + 4'd1);

assign add_ln611_1_fu_1104_p2 = (sub_ln611_1_fu_1099_p2 + indvars_iv_next1126_mid2_fu_1076_p3);

assign add_ln611_2_fu_1130_p2 = (sub_ln611_1_fu_1099_p2 + trunc_ln603_fu_1090_p1);

assign add_ln611_fu_711_p2 = (zext_ln611_1_fu_707_p1 + trunc_ln600_1_fu_685_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_74_fu_717_p1 = ic_step_1_mid2_fu_677_p3[2:0];

assign empty_fu_671_p2 = (select_ln597_2_fu_655_p3 | icmp_ln600_fu_640_p2);

assign ic_step_1_mid2_fu_677_p3 = ((empty_fu_671_p2[0:0] == 1'b1) ? 4'd0 : ic_step_fu_122);

assign icmp_ln597_fu_617_p2 = ((indvar_flatten38_fu_138 == mul_ln231_1) ? 1'b1 : 1'b0);

assign icmp_ln600_fu_640_p2 = ((indvar_flatten23_fu_130 == mul_ln231_cast_reg_1226) ? 1'b1 : 1'b0);

assign icmp_ln603_1_fu_650_p2 = ((ic_step_fu_122 == lshr_ln) ? 1'b1 : 1'b0);

assign icmp_ln603_fu_645_p2 = ((lshr_ln == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln610_10_fu_903_p2 = ((zext_ln610_10_fu_899_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_11_fu_920_p2 = ((zext_ln610_11_fu_916_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_12_fu_937_p2 = ((zext_ln610_12_fu_933_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_13_fu_954_p2 = ((zext_ln610_13_fu_950_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_14_fu_971_p2 = ((zext_ln610_14_fu_967_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_15_fu_988_p2 = ((zext_ln610_15_fu_984_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_1_fu_750_p2 = ((zext_ln610_1_fu_746_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_2_fu_767_p2 = ((zext_ln610_2_fu_763_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_3_fu_784_p2 = ((zext_ln610_3_fu_780_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_4_fu_801_p2 = ((zext_ln610_4_fu_797_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_5_fu_818_p2 = ((zext_ln610_5_fu_814_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_6_fu_835_p2 = ((zext_ln610_6_fu_831_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_7_fu_852_p2 = ((zext_ln610_7_fu_848_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_8_fu_869_p2 = ((zext_ln610_8_fu_865_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_9_fu_886_p2 = ((zext_ln610_9_fu_882_p1 < ic_count) ? 1'b1 : 1'b0);

assign icmp_ln610_fu_733_p2 = ((zext_ln610_fu_729_p1 < ic_count) ? 1'b1 : 1'b0);

assign indvars_iv_next1126235_fu_1051_p2 = (trunc_ln597_fu_1036_p1 + 7'd1);

assign indvars_iv_next1126_dup_fu_1064_p2 = (select_ln597_fu_1040_p3 + 32'd1);

assign indvars_iv_next1126_mid1_fu_1070_p2 = (trunc_ln600_fu_1047_p1 + 7'd2);

assign indvars_iv_next1126_mid2_fu_1076_p3 = ((select_ln597_2_reg_1241[0:0] == 1'b1) ? indvars_iv_next1126_mid1_fu_1070_p2 : select_ln597_1_fu_1057_p3);

assign mul_ln231_cast_fu_582_p1 = mul_ln231;

assign or_ln1_fu_738_p3 = {{empty_74_fu_717_p1}, {4'd1}};

assign or_ln609_10_fu_925_p3 = {{empty_74_fu_717_p1}, {4'd12}};

assign or_ln609_11_fu_942_p3 = {{empty_74_fu_717_p1}, {4'd13}};

assign or_ln609_12_fu_959_p3 = {{empty_74_fu_717_p1}, {4'd14}};

assign or_ln609_13_fu_976_p3 = {{empty_74_fu_717_p1}, {4'd15}};

assign or_ln609_1_fu_755_p3 = {{empty_74_fu_717_p1}, {4'd2}};

assign or_ln609_2_fu_772_p3 = {{empty_74_fu_717_p1}, {4'd3}};

assign or_ln609_3_fu_789_p3 = {{empty_74_fu_717_p1}, {4'd4}};

assign or_ln609_4_fu_806_p3 = {{empty_74_fu_717_p1}, {4'd5}};

assign or_ln609_5_fu_823_p3 = {{empty_74_fu_717_p1}, {4'd6}};

assign or_ln609_6_fu_840_p3 = {{empty_74_fu_717_p1}, {4'd7}};

assign or_ln609_7_fu_857_p3 = {{empty_74_fu_717_p1}, {4'd8}};

assign or_ln609_8_fu_874_p3 = {{empty_74_fu_717_p1}, {4'd9}};

assign or_ln609_9_fu_891_p3 = {{empty_74_fu_717_p1}, {4'd10}};

assign or_ln609_s_fu_908_p3 = {{empty_74_fu_717_p1}, {4'd11}};

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_address0 = zext_ln611_3_fu_1141_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_address1 = zext_ln611_2_fu_1110_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_ce1_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_d0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_q1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_30_we0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_address0 = zext_ln611_3_fu_1141_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_address1 = zext_ln611_2_fu_1110_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_ce1_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_d0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_q1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_31_we0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_address0 = zext_ln611_3_fu_1141_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_address1 = zext_ln611_2_fu_1110_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_ce1_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_d0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_q1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_32_we0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_address0 = zext_ln611_3_fu_1141_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_address1 = zext_ln611_2_fu_1110_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_ce1_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_d0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_q1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_33_we0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_address0 = zext_ln611_3_fu_1141_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_address1 = zext_ln611_2_fu_1110_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_ce1_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_d0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_q1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_34_we0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_address0 = zext_ln611_3_fu_1141_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_address1 = zext_ln611_2_fu_1110_p1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce0_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_ce1_local;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_d0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_q1;

assign p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0 = p_ZZL16scan_and_computePK7ap_uintILi32EEP6ap_intILi32EEPS3_ILi8EEjjjjjjjjjjjPA128_35_we0_local;

assign p_shl_fu_693_p3 = {{ic_step_1_mid2_fu_677_p3}, {2'd0}};

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_1_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_2_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_3_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_4_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_5_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_6_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_7_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_8_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_9_we0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_address0 = zext_ln611_3_fu_1141_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_address1 = zext_ln611_2_fu_1110_p1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce0_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_ce1_local;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_d0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_q1;

assign scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0 = scan_and_compute_ap_uint_const_ap_int_ap_int_unsigned_int_unsigned_int_unsign_we0_local;

assign select_ln597_1_fu_1057_p3 = ((icmp_ln600_reg_1235[0:0] == 1'b1) ? 7'd1 : indvars_iv_next1126235_fu_1051_p2);

assign select_ln597_2_fu_655_p3 = ((icmp_ln600_fu_640_p2[0:0] == 1'b1) ? icmp_ln603_fu_645_p2 : icmp_ln603_1_fu_650_p2);

assign select_ln597_3_fu_663_p3 = ((icmp_ln600_fu_640_p2[0:0] == 1'b1) ? add_ln597_fu_634_p2 : ky_fu_134);

assign select_ln597_fu_1040_p3 = ((icmp_ln600_reg_1235[0:0] == 1'b1) ? 32'd0 : kx_fu_126);

assign select_ln600_1_fu_1005_p3 = ((icmp_ln600_fu_640_p2[0:0] == 1'b1) ? 36'd1 : add_ln600_fu_999_p2);

assign select_ln600_fu_1083_p3 = ((select_ln597_2_reg_1241[0:0] == 1'b1) ? indvars_iv_next1126_dup_fu_1064_p2 : select_ln597_fu_1040_p3);

assign shl_ln611_fu_1094_p2 = add_ln611_reg_1247 << 7'd2;

assign sub_ln611_1_fu_1099_p2 = (shl_ln611_fu_1094_p2 - add_ln611_reg_1247);

assign sub_ln611_fu_701_p2 = (p_shl_fu_693_p3 - zext_ln611_fu_689_p1);

assign tmp_s_fu_721_p3 = {{empty_74_fu_717_p1}, {4'd0}};

assign trunc_ln597_fu_1036_p1 = kx_fu_126[6:0];

assign trunc_ln600_1_fu_685_p1 = select_ln597_3_fu_663_p3[6:0];

assign trunc_ln600_fu_1047_p1 = select_ln597_fu_1040_p3[6:0];

assign trunc_ln603_fu_1090_p1 = select_ln600_fu_1083_p3[6:0];

assign zext_ln610_10_fu_899_p1 = or_ln609_9_fu_891_p3;

assign zext_ln610_11_fu_916_p1 = or_ln609_s_fu_908_p3;

assign zext_ln610_12_fu_933_p1 = or_ln609_10_fu_925_p3;

assign zext_ln610_13_fu_950_p1 = or_ln609_11_fu_942_p3;

assign zext_ln610_14_fu_967_p1 = or_ln609_12_fu_959_p3;

assign zext_ln610_15_fu_984_p1 = or_ln609_13_fu_976_p3;

assign zext_ln610_1_fu_746_p1 = or_ln1_fu_738_p3;

assign zext_ln610_2_fu_763_p1 = or_ln609_1_fu_755_p3;

assign zext_ln610_3_fu_780_p1 = or_ln609_2_fu_772_p3;

assign zext_ln610_4_fu_797_p1 = or_ln609_3_fu_789_p3;

assign zext_ln610_5_fu_814_p1 = or_ln609_4_fu_806_p3;

assign zext_ln610_6_fu_831_p1 = or_ln609_5_fu_823_p3;

assign zext_ln610_7_fu_848_p1 = or_ln609_6_fu_840_p3;

assign zext_ln610_8_fu_865_p1 = or_ln609_7_fu_857_p3;

assign zext_ln610_9_fu_882_p1 = or_ln609_8_fu_874_p3;

assign zext_ln610_fu_729_p1 = tmp_s_fu_721_p3;

assign zext_ln611_1_fu_707_p1 = sub_ln611_fu_701_p2;

assign zext_ln611_2_fu_1110_p1 = add_ln611_1_fu_1104_p2;

assign zext_ln611_3_fu_1141_p1 = add_ln611_2_reg_1322;

assign zext_ln611_fu_689_p1 = ic_step_1_mid2_fu_677_p3;

always @ (posedge ap_clk) begin
    mul_ln231_cast_reg_1226[35] <= 1'b0;
end

endmodule //conv_engine_conv_engine_Pipeline_WINDOW_ROW_SHIFT_WINDOW_COL_SHIFT_WINDOW_ROW_SHIFT_STEP
