/*
 * conv_engine_hw_driver.h
 *
 * AXI4-Lite driver for the conv_engine HLS IP's control bundle ("CTRL" in
 * conv_engine.cpp's INTERFACE pragmas).
 *
 * Unlike hls/conv_layer1/SW/conv_layer1_hw_driver.h (which only sets two
 * fixed base addresses because the layer's shape was baked in at compile
 * time), this driver also has to program the layer's SHAPE every run,
 * because conv_engine is reused across every layer in the network - that is
 * the entire point of this redesign (see ../README.md). See
 * network_run.c for the loop that calls conv_engine_configure() once per
 * layer.
 *
 * CONFIRMED (2026-07-24, this fork's Levers 1-4 LUT-reduction session):
 * every REG_* offset below was previously a PLACEHOLDER (guessed by
 * extrapolating conv_layer1's pattern, "2 registers per pointer, no gap").
 * That guess was WRONG from `weights_hi` onward - real csynth output
 * (`conv_engine_prj/solution1/impl/misc/drivers/conv_engine_v1_0/src/
 * xconv_engine_hw.h`, auto-generated by Vitis HLS, ground truth) inserts a
 * reserved 32-bit register after EVERY signal (each 64-bit pointer gets 2
 * data registers + 1 reserved; each scalar gets 1 data register + 1
 * reserved) - the placeholder's "no gap" assumption made every offset from
 * `weights_hi` onward wrong by a consistent +0x04 vs. the real map. Had
 * this been used as-is against real hardware, every register write from
 * `weights_hi` onward would have landed 4 bytes off from the real signal
 * (mostly hitting the "reserved" slot instead) - a silent, hard-to-debug
 * hardware misconfiguration, not a compile-time-catchable error. Now
 * copied directly from `xconv_engine_hw.h`, not re-derived by hand -
 * re-copy from that generated file again after any change to
 * conv_engine()'s parameter list (a new/removed/reordered argument shifts
 * every offset after it).
 *
 * RE-CONFIRMED (2026-07-29): `run_hls.tcl`'s `open_project -reset` /
 * `open_solution -reset` mean every invocation fully regenerates
 * `impl/misc/drivers/...xconv_engine_hw.h` from scratch, so the 2026-07-24
 * confirmation above was never actually stale - but that export was a
 * plain RTL export, not the `ip_catalog` format (`impl/ip/` +
 * `component.xml`) Vivado's IP catalog / `vivado/create_bd.tcl` needs,
 * which this project had never produced until `run_hls.bat package` ran
 * for real today. Diffed the resulting `impl/ip/drivers/conv_engine_v1_0/
 * src/xconv_engine_hw.h` against every REG_* below: byte-for-byte
 * identical to the values already here, including every requant-fork
 * register (`REQUANT_MULTIPLIER`/`REQUANT_SHIFT`/`LEAKY_RELU_ENABLE` at
 * 0x90/0x98/0xa0) - confirming both that this file's offsets were already
 * correct AND that the IP is now packaged in the format Vivado actually
 * needs.
 */

/*
 * CALLER OBLIGATION - new with the int8x4 packed `ifmap` (2026-08-04)
 * ------------------------------------------------------------------
 * conv_engine's `ifmap` m_axi port now moves 4 consecutive NHWC channels per
 * AXI beat instead of 1 (see HW/pack4.h). NOTHING IN THIS DRIVER CHANGED as
 * a result - the register map, the offsets, the port count, and the meaning
 * of every value written below are identical to the pre-packing engine, and
 * `in_ch` is still counted in CHANNELS, not words. The DDR byte layout is
 * unchanged too, because 4 consecutive int8 channels on this little-endian
 * platform already are the 4 bytes of one 32-bit word. A buffer produced by
 * the pool/upsample/route engines is a valid conv input with no conversion,
 * and vice versa.
 *
 * There is exactly ONE new requirement, and it will produce wrong output
 * (not an error) if violated:
 *
 *   `ifmap` MUST be 4-byte aligned.
 *   Any ordinary allocator result, and any cacheline-aligned CMA buffer,
 *   already is.
 *
 * Note what is deliberately NOT required: there is no `in_ch % 4 == 0`
 * obligation. READ_CH carries a per-element slow path for the remainder
 * case specifically so layer 0 (in_ch=3, RGB) keeps working without its
 * input being re-laid-out as RGBX in DDR. Every other real layer
 * (in_ch = 16/32/64/128/256/384/512/1024) takes the packed fast path
 * automatically - software does not select between them.
 *
 * The other four pointers (weights, weights_hi, bias, ofmap, accum) are
 * unaffected: their element types did not change.
 */

#pragma once
#include <stdint.h>
#include "xparameters.h"
#include "xil_io.h"
#include "xil_printf.h"

#define CE_BASE      XPAR_CONV_ENGINE_0_S_AXI_CTRL_BASEADDR
#define CE_REG(off)  (CE_BASE + (uint32_t)(off))

/* ---- ap_ctrl_hs block-level control register (fixed offset for all HLS IP) */
#define REG_CTRL         0x00
#define CTRL_AP_START    (1u << 0)
#define CTRL_AP_DONE     (1u << 1)
#define CTRL_AP_IDLE     (1u << 2)
#define CTRL_AP_READY    (1u << 3)

/* ---- m_axi base-address registers - CONFIRMED against
 * conv_engine_prj/solution1/impl/misc/drivers/conv_engine_v1_0/src/
 * xconv_engine_hw.h (see note above). Six 64-bit pointers (ifmap, weights,
 * weights_hi, bias, ofmap, accum) -> 2 x 32-bit data registers each, PLUS
 * one reserved 32-bit register after each pointer's pair - that reserved
 * slot is what the old placeholder's "no gap" assumption missed, and why
 * every offset from `weights_hi` onward was wrong by +0x04 before this
 * fix. */
#define REG_IFMAP_ADDR_LO    0x10
#define REG_IFMAP_ADDR_HI    0x14
/* 0x18 reserved */
#define REG_WEIGHTS_ADDR_LO  0x1c
#define REG_WEIGHTS_ADDR_HI  0x20
/* 0x24 reserved */
/* Added so LOAD_W_IC (conv_engine.cpp) can read a pair's y_lo/y_hi on two
 * independent AXI4 master ports in the same cycle instead of serializing two
 * reads onto one - a real csynth run measured that single-port sharing as
 * achieved II=2 against a target of II=1 (see TROUBLESHOOTING.md). Program
 * this with the EXACT SAME base address as REG_WEIGHTS_ADDR_LO/HI above -
 * this is a second physical port onto the same weights buffer, not a
 * separate copy of the data. */
#define REG_WEIGHTS_HI_ADDR_LO 0x28
#define REG_WEIGHTS_HI_ADDR_HI 0x2c
/* 0x30 reserved */
#define REG_BIAS_ADDR_LO     0x34
#define REG_BIAS_ADDR_HI     0x38
/* 0x3c reserved */
#define REG_OFMAP_ADDR_LO    0x40
#define REG_OFMAP_ADDR_HI    0x44
/* 0x48 reserved */
/* Added for input-channel tiling's DDR scratch buffer (see conv_engine.h's
 * note on the `accum` parameter) - software must allocate this buffer
 * (>= out_h*out_w*PE_OC signed INT32 elements) but never needs to
 * initialize or read its contents itself. */
#define REG_ACCUM_ADDR_LO    0x4c
#define REG_ACCUM_ADDR_HI    0x50
/* 0x54 reserved */

/* ---- scalar geometry registers - CONFIRMED (see note above). img_h/img_w/
 * in_ch/out_ch are uint16_t, k/stride/pad are uint8_t - Vitis HLS still
 * gives each its own 32-bit-aligned s_axilite register (does not pack
 * sub-word scalars together by default) PLUS a reserved register after
 * each one, same +0x04-per-slot pattern as the pointers above. */
#define REG_IMG_H    0x58
/* 0x5c reserved */
#define REG_IMG_W    0x60
/* 0x64 reserved */
#define REG_IN_CH    0x68
/* 0x6c reserved */
#define REG_OUT_CH   0x70
/* 0x74 reserved */
#define REG_K        0x78
/* 0x7c reserved */
#define REG_STRIDE   0x80
/* 0x84 reserved */
#define REG_PAD      0x88
/* 0x8c reserved */
/* Added for the real per-layer requantization (conv_engine_requant fork -
 * see ../README.md's provenance note and RTL_HANDOFF_KO.md section 5). */
#define REG_REQUANT_MULTIPLIER  0x90
/* 0x94 reserved */
#define REG_REQUANT_SHIFT       0x98
/* 0x9c reserved */
#define REG_LEAKY_RELU_ENABLE   0xa0
/* 0xa4 reserved */

/* Program one layer's DDR addresses. Call once per layer before
 * conv_engine_start(), see network_run.c. `accum` must point at a buffer
 * >= out_h*out_w*PE_OC signed INT32 elements - see conv_engine.h's note on
 * this parameter; the caller never needs to initialize or read it.
 *
 * `weights` is programmed into BOTH REG_WEIGHTS_ADDR_* and
 * REG_WEIGHTS_HI_ADDR_* - conv_engine's second weights port
 * (`weights_hi`, conv_engine.h) is a second physical AXI4 master port onto
 * the SAME DRAM region, not a separate buffer, so there is deliberately no
 * separate `weights_hi` argument here for callers to get out of sync.
 *
 * `ifmap` must be 4-byte aligned - see "CALLER OBLIGATION" at the top of
 * this file. The other addresses have no new alignment requirement. */
static inline void conv_engine_set_addrs(uint64_t ifmap, uint64_t weights,
                                          uint64_t bias, uint64_t ofmap,
                                          uint64_t accum)
{
    Xil_Out32(CE_REG(REG_IFMAP_ADDR_LO),   (uint32_t)(ifmap & 0xffffffffu));
    Xil_Out32(CE_REG(REG_IFMAP_ADDR_HI),   (uint32_t)(ifmap >> 32));
    Xil_Out32(CE_REG(REG_WEIGHTS_ADDR_LO), (uint32_t)(weights & 0xffffffffu));
    Xil_Out32(CE_REG(REG_WEIGHTS_ADDR_HI), (uint32_t)(weights >> 32));
    Xil_Out32(CE_REG(REG_WEIGHTS_HI_ADDR_LO), (uint32_t)(weights & 0xffffffffu));
    Xil_Out32(CE_REG(REG_WEIGHTS_HI_ADDR_HI), (uint32_t)(weights >> 32));
    Xil_Out32(CE_REG(REG_BIAS_ADDR_LO),    (uint32_t)(bias & 0xffffffffu));
    Xil_Out32(CE_REG(REG_BIAS_ADDR_HI),    (uint32_t)(bias >> 32));
    Xil_Out32(CE_REG(REG_OFMAP_ADDR_LO),   (uint32_t)(ofmap & 0xffffffffu));
    Xil_Out32(CE_REG(REG_OFMAP_ADDR_HI),   (uint32_t)(ofmap >> 32));
    Xil_Out32(CE_REG(REG_ACCUM_ADDR_LO),   (uint32_t)(accum & 0xffffffffu));
    Xil_Out32(CE_REG(REG_ACCUM_ADDR_HI),   (uint32_t)(accum >> 32));
}

/* Program one layer's shape. stride is always 1 in this version - see
 * conv_engine.h "design limits" (this driver still forwards whatever it's
 * given rather than silently overriding it, so a caller requesting
 * stride!=1 gets wrong hardware behavior, not a silently-ignored request -
 * that mismatch is easier to debug than a silent override). */
static inline void conv_engine_set_shape(uint16_t img_h, uint16_t img_w,
                                          uint16_t in_ch, uint16_t out_ch,
                                          uint8_t k, uint8_t stride, uint8_t pad)
{
    Xil_Out32(CE_REG(REG_IMG_H),  img_h);
    Xil_Out32(CE_REG(REG_IMG_W),  img_w);
    Xil_Out32(CE_REG(REG_IN_CH),  in_ch);
    Xil_Out32(CE_REG(REG_OUT_CH), out_ch);
    Xil_Out32(CE_REG(REG_K),      k);
    Xil_Out32(CE_REG(REG_STRIDE), stride);
    Xil_Out32(CE_REG(REG_PAD),    pad);
}

/* Program one layer's requantization (model_manifest.json's per-layer
 * requant_multiplier/requant_right_shift) and whether LeakyReLU applies -
 * "linear" head layers (RTL_HANDOFF_KO.md section 7, layers 15/22) must
 * pass leaky_relu_enable=0. */
static inline void conv_engine_set_quant(int32_t requant_multiplier,
                                          uint8_t requant_shift,
                                          uint8_t leaky_relu_enable)
{
    Xil_Out32(CE_REG(REG_REQUANT_MULTIPLIER), (uint32_t)requant_multiplier);
    Xil_Out32(CE_REG(REG_REQUANT_SHIFT),      requant_shift);
    Xil_Out32(CE_REG(REG_LEAKY_RELU_ENABLE),  leaky_relu_enable);
}

static inline void conv_engine_start(void)
{
    Xil_Out32(CE_REG(REG_CTRL), CTRL_AP_START);
}

static inline int conv_engine_wait_idle(const char *where)
{
    uint32_t tmo = 10000000u;
    while ((Xil_In32(CE_REG(REG_CTRL)) & CTRL_AP_IDLE) == 0u) {
        if (--tmo == 0u) {
            xil_printf("%s: conv_engine ap_idle timeout\r\n", where);
            return -1;
        }
    }
    return 0;
}

/* Poll ap_done. Since conv_engine re-scans the image once per (oc_tile,
 * ic_tile) pair now, not just once per oc_tile (see conv_engine.cpp
 * OC_TILE/IC_TILE), a single run over a deep, high-in_ch layer takes
 * noticeably longer than conv_layer1's single-pass design or even the
 * pre-tiling version of this file - if this timeout ever trips on real
 * hardware, check whether it's a real hang or just a layer (e.g. the real
 * network's layer 13, in_ch=1024 -> 8 ic_tiles) big enough to need a larger
 * tmo budget. */
static inline int conv_engine_wait_done(const char *where)
{
    uint32_t tmo = 200000000u;
    while ((Xil_In32(CE_REG(REG_CTRL)) & CTRL_AP_DONE) == 0u) {
        if (--tmo == 0u) {
            xil_printf("%s: conv_engine ap_done timeout\r\n", where);
            return -1;
        }
    }
    return 0;
}
