/* Auto-generated by python/export_sw_headers.py - do not edit by hand. */
#pragma once
#include <stdint.h>

#define NUM_LAYERS 13
#define MAX_IFMAP_ELEMS 589824
#define MAX_OFMAP_ELEMS 2359296
/* accum scratch buffer sizing - see conv_engine.h's note on the
 * `accum` parameter and this script's PE_OC constant (kept in sync
 * with conv_engine.h by hand, same caveat as
 * SW/conv_engine_hw_driver.h's REG_* offsets). */
#define MAX_ACCUM_ELEMS 3538944

typedef struct {
    uint16_t img_h, img_w, in_ch, out_ch;
    uint8_t  k, stride, pad;
    uint32_t weight_offset; /* element offset into WEIGHTS_BLOB */
    uint32_t bias_offset;   /* element offset into BIAS_BLOB (int32_t elements) */
    uint32_t input_offset;  /* element offset into INPUTS_BLOB - this layer's OWN
                             * real input, NOT the previous layer's conv_engine()
                             * output (see network_run.c) */
    int32_t  requant_multiplier;
    uint8_t  requant_shift;
    uint8_t  leaky_relu_enable; /* 0 = linear (detection-head layers), 1 = LeakyReLU(13/128) */
} layer_cfg_t;

static const layer_cfg_t NETWORK_LAYERS[NUM_LAYERS] = {
    { .img_h=290, .img_w=514, .in_ch=3, .out_ch=16, .k=3, .stride=1, .pad=0, .weight_offset=0, .bias_offset=0, .input_offset=0, .requant_multiplier=1264723901, .requant_shift=37, .leaky_relu_enable=1 },
    { .img_h=144, .img_w=256, .in_ch=16, .out_ch=32, .k=3, .stride=1, .pad=1, .weight_offset=432, .bias_offset=16, .input_offset=447180, .requant_multiplier=1690762378, .requant_shift=37, .leaky_relu_enable=1 },
    { .img_h=72, .img_w=128, .in_ch=32, .out_ch=64, .k=3, .stride=1, .pad=1, .weight_offset=5040, .bias_offset=48, .input_offset=1037004, .requant_multiplier=1490636759, .requant_shift=38, .leaky_relu_enable=1 },
    { .img_h=36, .img_w=64, .in_ch=64, .out_ch=128, .k=3, .stride=1, .pad=1, .weight_offset=23472, .bias_offset=112, .input_offset=1331916, .requant_multiplier=1585969364, .requant_shift=38, .leaky_relu_enable=1 },
    { .img_h=18, .img_w=32, .in_ch=128, .out_ch=256, .k=3, .stride=1, .pad=1, .weight_offset=97200, .bias_offset=240, .input_offset=1479372, .requant_multiplier=1085497666, .requant_shift=39, .leaky_relu_enable=1 },
    { .img_h=9, .img_w=16, .in_ch=256, .out_ch=512, .k=3, .stride=1, .pad=1, .weight_offset=392112, .bias_offset=496, .input_offset=1553100, .requant_multiplier=1597509700, .requant_shift=40, .leaky_relu_enable=1 },
    { .img_h=9, .img_w=16, .in_ch=512, .out_ch=1024, .k=3, .stride=1, .pad=1, .weight_offset=1571760, .bias_offset=1008, .input_offset=1589964, .requant_multiplier=1810489245, .requant_shift=42, .leaky_relu_enable=1 },
    { .img_h=9, .img_w=16, .in_ch=1024, .out_ch=256, .k=1, .stride=1, .pad=0, .weight_offset=6290352, .bias_offset=2032, .input_offset=1663692, .requant_multiplier=1429642394, .requant_shift=40, .leaky_relu_enable=1 },
    { .img_h=9, .img_w=16, .in_ch=256, .out_ch=512, .k=3, .stride=1, .pad=1, .weight_offset=6552496, .bias_offset=2288, .input_offset=1811148, .requant_multiplier=1254521939, .requant_shift=40, .leaky_relu_enable=1 },
    { .img_h=9, .img_w=16, .in_ch=512, .out_ch=30, .k=1, .stride=1, .pad=0, .weight_offset=7732144, .bias_offset=2800, .input_offset=1848012, .requant_multiplier=1576269802, .requant_shift=42, .leaky_relu_enable=0 },
    { .img_h=9, .img_w=16, .in_ch=256, .out_ch=128, .k=1, .stride=1, .pad=0, .weight_offset=7747504, .bias_offset=2830, .input_offset=1921740, .requant_multiplier=1171363238, .requant_shift=39, .leaky_relu_enable=1 },
    { .img_h=18, .img_w=32, .in_ch=384, .out_ch=256, .k=3, .stride=1, .pad=1, .weight_offset=7780272, .bias_offset=2958, .input_offset=1958604, .requant_multiplier=1468269848, .requant_shift=40, .leaky_relu_enable=1 },
    { .img_h=18, .img_w=32, .in_ch=256, .out_ch=30, .k=1, .stride=1, .pad=0, .weight_offset=8665008, .bias_offset=3214, .input_offset=2179788, .requant_multiplier=1764908694, .requant_shift=41, .leaky_relu_enable=0 },
};
